### ISSUE TITLE
Regional locales not considered during slug generation

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#5547] opened 2022-12-01 12:55 UTC
### Affected version(s)

4.9, 4.13, 5.0

### Description

If you set the slug generation settings in your website root to _ASCII numbers and lowercase letters_ for example and the language of the website root to `de` and you create a new page within that website root with the title _Übersicht_, then the automatically generated alias will be `uebersicht`, as expected.

However, if you do the same - but in a website root with a regional locale like `de_AT` for example, then the automatically generated alias will be `ubersicht` - even though it should also consider the German locale for slug generation when converting Umlauts.

/cc @ausi

**Comment by ausi** [comment] 2022-12-01 13:23
Duplicate of #2413 ?

**Closed as not planned** 2022-12-01 15:25 UTC
Labels: bug, unconfirmed
