### ISSUE TITLE
Cron-Job - Purged the unactivated member registrations 

### ISSUE THREAD

**Issue by katgirl** [contao/contao#5769] opened 2023-02-10 07:48 UTC
### Affected version(s)

4.13.15

### Description

The cron job "Purged the unactivated member registrations" should take into account the cron job or the expiration of the expired double opt-in tokens.

User Registered on 08.02.2023 19:01 -> Double opt-in token valid until 11.02.2023 19:01 -> but member already cleared on 10.02.2023 00:00. 

![image](https://user-images.githubusercontent.com/1223243/218032594-b96772ec-9f82-4f68-a841-df4f01bddd3c.png)

![image](https://user-images.githubusercontent.com/1223243/218032921-42651d8b-809a-4a48-8b14-9617b626796d.png)

**Comment by fritzmg** [comment] 2023-02-11 06:32
The token is only valid for 24 hours, thus the cronjob cleared it on 10.02.2023 00:00

**Comment by katgirl** [comment] 2023-02-11 10:59
We have restored the data set from the backup. The toll was still valid on 11.02.

**Comment by fritzmg** [comment] 2023-02-11 12:43
The token's validity is deliberately longer than needed. Nevertheless the confirm URL is only valid for 24 hours. After that the registration will be removed - either by the cronjob or by the registration module.

**Comment by fritzmg** [comment] 2023-02-14 21:52
Closing since working as intended.

**Closed as completed by fritzmg** 2023-02-14 21:52 UTC
Labels: bug, unconfirmed
