### ISSUE TITLE
Handle invalid important parts in the version 4.8.0 migration

### ISSUE THREAD

**Issue by rabauss** [contao/contao#2912] opened 2021-03-24 17:02 UTC
**Affected version(s)**

Contao 4.9+

**Description**

Since https://github.com/contao/contao/pull/2884 I got a loop in one of our contao installation, because there was a image which had the following params:
* `importantPartX > 1` and `importantPartY > 1` - checked here:
https://github.com/contao/contao/blob/c55ea60abc4046ff1e2f96ccba6be4559ec11c1f/core-bundle/src/Migration/Version408/Version480Update.php#L252-L260
* `importantPartWidth = 0` and `importantPartHeight = 0` - ignored here:
https://github.com/contao/contao/blob/c55ea60abc4046ff1e2f96ccba6be4559ec11c1f/core-bundle/src/Migration/Version408/Version480Update.php#L289-L294

The method `runImportantPart` should be improved, that all conditions of the `shouldRunImportantPart` are solved!

**Comment by fritzmg** [comment] 2021-03-24 17:06
As discussed on Slack this could happen for images under the following circumstances (in Contao versions prior to 4.8):

* Upload an image with a resolution of e.g. `2000x2000`.
* Set the important part to e.g. `600,600,100,100` (x,y,w,h).
* Then replace the image with a lower resolution of `500x500` - either via FTP or even the file manager.

Now the important part is invalid and this is not taken into account in the migration. The migration should additionally check for invalid important parts and remove those as well.

**Comment by ausi** [comment] 2021-03-24 22:36
I was not able to reproduce it that way. The invalid important part `600,600,100,100` gets converted to `1,1,0,0` correctly. 

Nevertheless invalid important parts like `10,10,0,0` did not get handled correctly, this should get fixed with #2914

**Closed as completed** 2021-05-10 09:45 UTC
Labels: bug
