### ISSUE TITLE
Individually change file management metadata for content elements

### ISSUE THREAD

**Issue by con2net** [contao/contao#4963] opened 2022-07-07 09:35 UTC
### Description

Currently it is possible to enter the metadata individually for content elements that include files (especially the content element "image"). If you change ONLY ONE meta value, e.g. the image link, ALL meta data are changed to the values used here. If you have already entered the title and the alternative text for a certain image in the file management, you would also have to enter these again here. If you forget to do this, the title and ALT tag will not be displayed later in the HTML code. This behaviour may be very inconvenient for practical work. For example, if you style a self-created image for individual navigations. The image link often has to change for this. With the previous procedure, you either have to create the image several times in the file management or give up the principle of central maintenance in the file management and instead enter everything individually in the elements.

The idea would be that when clicking on the use of the metadata in the content element, these would first be copied from the corresponding entry in the file management as start values. This would give you "everything together" and you could now decide individually whether you want to change the texts or delete them individually for this element.

**Comment by fritzmg** [comment] 2022-07-07 09:41
Duplicate of #599

**Closed as not planned by fritzmg** 2022-07-07 09:41 UTC
Labels: feature
