### ISSUE TITLE
getTemplateData() must be of the type array, null given

### ISSUE THREAD

**Issue by luger95** [contao/contao#5595] opened 2022-12-20 11:31 UTC
### Affected version(s)

4.13.0

### Description

`Argument 3 passed to Contao\CoreBundle\EventListener\DataContainer\Undo\LabelListener::getTemplateData() must be of the type array, null given, called in /vendor/contao/core-bundle/src/EventListener/DataContainer/Undo/LabelListener.php on line 5`

**Comment by fritzmg** [comment] 2022-12-20 13:11
Duplicate of #5449

**Closed as not planned by fritzmg** 2022-12-20 13:11 UTC
Labels: bug, unconfirmed
