### ISSUE TITLE
error when sending newsletter

### ISSUE THREAD

**Issue by jochi44** [contao/contao#5042] opened 2022-07-25 18:34 UTC
### Affected version(s)

5.0.0-RC1

### Description

When sending a newsletter in the Contao 5 backend, an internal server error appears.
Note: the contao-newsletter-package is installed.
Details in /var/logs:

```
[2022-07-25T20:30:54.023937+02:00] request.INFO: Matched route "contao_backend". {"route":"contao_backend","route_parameters":{"_route":"contao_backend","_scope":"backend","_token_check":true,"_controller":"Contao\\CoreBundle\\Controller\\BackendController::mainAction"},"request_uri":"https://contao5.xyz.tld/contao?do=newsletter&id=1&key=send&ref=tC3DN5Lx&rt=5e525187bb.6Uf3RpJvpAOv71-FkvPULY_AJSBZVbVqWdHx-LvubxA.mhi4P8En5zOegBLh_Kq4d9j4ZkUBPM0aMLzczuOHLUG4Hq0-vxXxS8rCPA&table=tl_newsletter","method":"GET"} []
[2022-07-25T20:30:54.029163+02:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\UndefinedMethodError: "Attempted to call an undefined method named "route" of class "Contao\Newsletter"." at /var/www/clients/web/contao5/vendor/contao/newsletter-bundle/contao/classes/Newsletter.php line 269 {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\UndefinedMethodError(code: 0): Attempted to call an undefined method named \"route\" of class \"Contao\\Newsletter\". at /var/www/clients/web/contao5/vendor/contao/newsletter-bundle/contao/classes/Newsletter.php:269)"} []
```

**Comment by fritzmg** [comment] 2022-07-25 18:40
Duplicate of #5037

**Closed as completed by fritzmg** 2022-07-25 18:40 UTC
Labels: bug, unconfirmed
