### ISSUE TITLE
tinyMCE: overwriting block('content_css') not possible 

### ISSUE THREAD

**Issue by denniserdmann** [contao/contao#2168] opened 2020-08-18 15:19 UTC
**Affected version(s)**

Contao 4.10

**Description**

I tried to change my tinyMCE.html5 template according to https://github.com/contao/contao/pull/2021
While other blocks can be overwritten, block('content_css') can not.

Code example:

```
<?php $this->extend('be_tinyMCE'); ?>

<?php $this->block('toolbar'); ?>
    toolbar: 'link unlink | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | code', // working
  <?php $this->endblock(); ?>
  
<?php $this->block('content_css'); ?>
    content_css: '/files/tinymce/tinymce.css', // not working
<?php $this->endblock(); ?>

<?php $this->block('custom'); ?>
    content_css: '/files/tinymce/tinymce.css', //  working, but additional css loading
<?php $this->endblock(); ?>
```

**Comment by frontendschlampe** [comment] 2020-08-18 15:23
see https://github.com/contao/contao/pull/2167 :-)

**Comment by leofeyer** [comment] 2020-08-18 15:23
Duplicate of #2167

**Closed as completed by leofeyer** 2020-08-18 15:23 UTC
