### ISSUE TITLE
All content items with a heading have an undefined option

### ISSUE THREAD

**Issue by minstyle** [contao/contao#2382] opened 2020-10-01 09:14 UTC
**Affected version(s)**

Contao 4.9.7 (other versions not tested)

**Description**

If you want to edit any content element with a heading in Contao, the undefined option "Unknown option" (in german: "Unbekannte Option") is shown in the select box.

![image](https://user-images.githubusercontent.com/2649562/94790569-bdf88e80-03d6-11eb-8247-5edc9dc7f652.png)

**How to reproduce**

See official Contao online demo at https://demo.contao.org

**Comment by leofeyer** [comment] 2020-10-01 09:16
Duplicate of #2360

**Closed as completed by leofeyer** 2020-10-01 09:16 UTC
