### ISSUE TITLE
Add DBAL 2.11.0 at contao-conflicts

### ISSUE THREAD

**Issue by zonky2** [contao/contao#2359] opened 2020-09-25 10:37 UTC
see https://github.com/doctrine/dbal/issues/4282

**Affected version(s)**
Contao 4.4 and Contao 4.9

**Comment by fritzmg** [comment] 2020-09-25 11:00
Does this actually affect Contao? If yes, how - or how do you reproduce it?

**Comment by aschempp** [comment] 2020-09-25 11:17
Duplicate of https://github.com/contao/conflicts/pull/13

**Closed as completed by aschempp** 2020-09-25 11:17 UTC
