### ISSUE TITLE
Content Elements of News and Event are not listed on Contao 4.13.7

### ISSUE THREAD

**Issue by taca** [contao/contao#5177] opened 2022-08-17 01:02 UTC
### Affected version(s)

4.13.7

### Description

Contant Elements of News and Event are not listed on Contao 4.13.7.
Tested on locally installed Contao 4.13.7 with Official Demo is only extension.

1. Open News or Event from left navigation.
2. Open an Event or News Archive.
3. Edit an event or news item.
4. Then, no content element is listed.

Downgrading to 4.13.6 fix this problem.

**Comment by chriza** [comment] 2022-08-17 04:34
Das kann ich bestätigen.
Beim Speichern eines Content-Inhaltes zu einer News oder eines Events wird in der Tabelle tl_content in das DB-Feld ptable der Wert tl_article geschrieben.

**Comment by aschempp** [comment] 2022-08-17 05:20
Duplicate of https://github.com/contao/contao/issues/5157

**Closed as completed by aschempp** 2022-08-17 05:20 UTC
Labels: bug, unconfirmed
