### ISSUE TITLE
Highlight elements that are not visible due to expiration date.

### ISSUE THREAD

**Issue by Kabathus** [contao/contao#5068] opened 2022-08-02 07:49 UTC
### Description

If an element is not displayed in the frontend due to an expiration date, this is not visible in the lists.

It would be nice if in the backend, next to the icons for visible and invisible, another icon would be used for such elements. For this, the eye icon would have to get a third status.

**Comment by ausi** [comment] 2022-08-02 10:02
This is probalby a duplicate of #3826

**Comment by Kabathus** [comment] 2022-08-02 10:27
> This is probalby a duplicate of #3826

yes

**Closed as not planned** 2022-08-02 10:27 UTC
Labels: feature
