### ISSUE TITLE
content-hyperlink title always shows the link text

### ISSUE THREAD

**Issue by jonnyefftek** [contao/contao#6219] opened 2023-07-16 11:59 UTC
### Affected version(s)

5.1.18, 5.1.19

### Description

I cannot set the title attribute in the hyperlink element anymore

the twig template hyperlink.html.twig only shows title="link_text" now

**Comment by fritzmg** [comment] 2023-07-16 15:53
Duplicate of #6174

**Closed as completed by fritzmg** 2023-07-16 15:53 UTC
Labels: bug, unconfirmed
