### ISSUE TITLE
301 redirect after invalidated login

### ISSUE THREAD

**Issue by 7FyOh** [contao/contao#1781] opened 2020-05-31 09:58 UTC
**Affected version(s)**

Contao 4.9

**Description**

When a member whose login is not valid anymore tries to visit a protected page, it cannot visit that page after being logged in again due to a `301 Moved Permanently` redirect.

All steps done on demo.contao.org:

1. https://demo.contao.org/en/: Login with any FE user
1. Invalidate login (e.g., delete cookies)
1. Click on "My Account" in menu
1. Redirect to https://demo.contao.org/en/login.html?_hash=MlBei5b281dTZHXinY8TBt0dLSxrnoFXzxpT1TLVawo%3D&redirect=https%3A%2F%2Fdemo.contao.org%2Fen%2Fmy-account.html with Status `301 Moved Permanently`
1. Login again
1. Click on "My Account" in menu again
1. Redirect to https://demo.contao.org/en/login.html?_hash=MlBei5b281dTZHXinY8TBt0dLSxrnoFXzxpT1TLVawo%3D&redirect=https%3A%2F%2Fdemo.contao.org%2Fen%2Fmy-account.html with Status `301 Moved Permanently`
1. (Click on "Members Area" works as expected.)

**Comment by fritzmg** [comment] 2020-05-31 10:12
Duplicate of https://github.com/contao/contao/pull/1762

The Contao online demo has the same problem.

**Closed as completed** 2020-05-31 10:15 UTC
