### ISSUE TITLE
PR #2531 leads to error for news feature toggle and core callbacks

### ISSUE THREAD

**Issue by Defcon0** [contao/contao#2798] opened 2021-02-24 12:28 UTC
**Affected version(s)**

Tested contao 4.4 only, 4.9 might be affected, as well

**Description**

The pull request https://github.com/contao/contao/pull/2531 leads to errors when using the feature toggle in news. onload_callbacks like in terminal42/contao-changelanguage also lead to this error. I hotfixed these to show that the error is also present in core code.

See attached stack trace:

![screen](https://user-images.githubusercontent.com/1485098/109000345-e04fb900-76a3-11eb-963f-9ac6766d81f3.png)

I guess in any case the correct dc needs to be passed.

Bye Defcon0

**Comment by fritzmg** [comment] 2021-02-24 12:59
Duplicate of #2574

Contao 4.4 has reached the end of its bugfix support lifetime.

**Closed as completed by fritzmg** 2021-02-24 12:59 UTC
