### ISSUE TITLE
Forms that are sent via AJAX do not work correctly if contao-mp_forms is used simultaneously

### ISSUE THREAD

**Issue by lukasbableck** [contao/contao#6609] opened 2023-12-07 09:13 UTC
### Affected version(s)

^5.1

### Description

Forms that are sent via AJAX and simultaneously use terminal42/contao-mp_forms are not continued after page 2 because the form action is incorrect. See also https://github.com/terminal42/contao-ajaxform/issues/28.
[This change](https://github.com/contao/contao/commit/56015a31a53de450a1bdb710cd610422f9205652) will fix the issue.

**Comment by fritzmg** [comment] 2023-12-07 13:35
Alternatively the mp_forms extension would need to make sure that the `action` parameter is set for the form template (at least after the first step), in order to ensure the form is sent with the correct URL. It currently only relies on the current browser URL. Not sure what solution is more "correct".

**Comment by leofeyer** [comment] 2024-01-04 15:44
@aschempp @qzminski What do you think?

**Comment by qzminski** [comment] 2024-01-08 15:44
I think the appropriate fix would be to have the correct action already present in the HTML returned from the AJAX response. The server side already knows it's an AJAX request and can adjust accordingly. Fixing this in JS is wrong in my opinion because by "definition" the returned HTML buffer should contain a valid markup. This would be patching instead of fixing and would apply only to this specific extension it seems. IMO it's the `mp_forms` that should fix the returned response. 

@Toflar

**Comment by fritzmg** [comment] 2024-01-08 15:54
> The server side already knows it's an AJAX request and can adjust accordingly

Not via `fetch` though. The action should just be output regardless.

**Comment by Toflar** [comment] 2024-01-08 15:54
Well, `mp_forms` sends an HTTP 303 redirect response because it wants to forward you to the next step. Any listener could intercept the form submission and redirect you wherever, not just `mp_forms`.
So if you had an extension that forwards to to some other page if you e.g. selected `foobar` in the form dropdown, you would have the same issue.

**Comment by fritzmg** [comment] 2024-01-08 15:58
@Toflar redirects to a completely different URL are not the problem though, only regular form submissions that return the form (or its next step) again.

**Comment by Toflar** [comment] 2024-01-08 16:00
Then I don't understand the problem. `mp_forms` always redirects unless you are on the last page.

**Comment by fritzmg** [comment] 2024-01-08 16:02
The issue is, that `mp_forms` does not set the `action` attribute on the form, thus when using the new AJAX submission functionality of Contao the POST request goes to the wrong URL on the subsequent steps, as the original URL will be used.

**Comment by Toflar** [comment] 2024-01-08 16:07
Okay, then I guess you guys need to come up with a PR for it :)

**Comment by fritzmg** [comment] 2024-01-08 16:11
If we decide that this needs to be fixed in `mp_forms` - we haven't really decided yet what is more correct. 

Personally I'm inclined to agree that making sure the `action` is correct is the right approach (i.e. it could be fixed in `mp_forms` - but Contao could always set the `action` as well).

**Comment by leofeyer** [comment] 2024-01-11 14:37
As discussed in the Contao call, 56015a31a53de450a1bdb710cd610422f9205652 could fix the issue if we additionally wrap it in an `if (!newForm.getAttribute('action'))`.

**Comment by fritzmg** [comment] 2024-01-12 12:32
See #6709

**Closed as completed by fritzmg** 2024-01-12 12:32 UTC
Labels: bug
