### ISSUE TITLE
"invalid token" when editing comment (link from email)

### ISSUE THREAD

**Issue by jochi44** [contao/contao#5084] opened 2022-08-03 18:10 UTC
### Affected version(s)

4.13.6, 5.0.0-RC1

### Description

Steps to reproduce:
1. create a new content element of element type "Comments"
2. in the "Comment settings" section check the box "Moderate"
3. save the content element
4. send a comment (newly created content element in the frontend)
5. because of the "Moderate" behaviour, the system admininstrator now receives an email with a link to check the comment and possibly publish it; the link to the corresponding comment (backend section CONTENT -> "Comments") in the email is: https://contao5.xyz.tld/contao?do=comments&act=edit&id=5
6. clicking the email link leads to the following error (the url in the browser with the error message is https://contao5.xyz.tld/contao/confirm):

![screenshot_issue_invalid_token_comment](https://user-images.githubusercontent.com/60215157/182678428-3058a72a-06ff-4ae2-bf76-72b63650343e.jpg)

7. clicking "Continue" leads to the corresponding comment in the backend with no further problems.

No errors in error.log (server) and /var/logs.

**Comment by aschempp** [comment] 2022-08-03 19:02
Duplicate of https://github.com/contao/contao/issues/2310

**Closed as completed by aschempp** 2022-08-03 19:02 UTC
Labels: bug, unconfirmed
