### ISSUE TITLE
Residual file via frontend upload when server-side form validation fails because of other field

### ISSUE THREAD

**Issue by gmpf** [contao/contao#1185] opened 2020-01-14 18:15 UTC
**Affected version(s)**
4.4, 4.8

**Description**
If a file is uploaded via a frontend form, the upload is completed and the file is retained even when server-side form validation fails because of another field in the form.

**How to reproduce**
* Create a new form in the form generator.
* Create a file upload field. Check "Store uploaded files" and select a directory.
* Create a text field. For "Input validation", select "Alphabetic characters".
* Add a send field.
* In the frontend, select a valid file, but type `123` into the text field. Send the form.

**Result:** You get an error message for the "Alphabetic characters" field, but the file from the other field is uploaded anyway.

This produces a greater issue if you also select "Preserve existing files" in the file upload field settings: A user initially selects a file, but enters something invalid in another field. They send the form. Once they get the validation error, they enter something correct and re-send the form, again with the file. Their initially-validated and already-uploaded file is now uploaded a second time and given a suffix.

**Expected result:** Ideally, the file would not be uploaded or not be moved to the selected directory if the form does not pass validation.

**Comment by aschempp** [comment] 2020-01-24 19:19
I don't think this is a Contao issue, as Contao does not offer an ajax upload in the front end?

**Comment by gmpf** [comment] 2020-01-24 20:27
@aschempp This has nothing to do with an AJAX upload. It's just the normal file upload field available in the form generator – this thing:
https://github.com/contao/contao/blob/4.8/core-bundle/src/Resources/contao/dca/tl_form_field.php#L109
https://github.com/contao/contao/blob/4.8/core-bundle/src/Resources/contao/config/config.php#L252
https://github.com/contao/contao/blob/4.8/core-bundle/src/Resources/contao/forms/FormFileUpload.php

**Comment by leofeyer** [comment] 2020-03-27 11:33
The problem is that the widgets only validate themselves and know nothing about other widgets in the same form. Thus the `FormFileUpload` widget stores the file on the server if it validates, regardless of whether another widget does not validate. We would have to defer the storing of the file (`move_uploaded_file()`) to after the form has been submitted successfully.

**Comment by leofeyer** [comment] 2020-12-16 15:55
Since Contao 4.4 is now in the "security updates only" phase of the LTS cycle, I am moving this issue to the 4.9 milestone.

**Closed as completed** 2021-10-26 21:43 UTC
Labels: bug
