### ISSUE TITLE
<p> tags around insert tag in 4.12.2 newsletter

### ISSUE THREAD

**Issue by berecont** [contao/contao#3561] opened 2021-10-07 18:10 UTC
Contao 4.12.2
Newsletter

adding insert tags, there will be added `<p>` tags around.
Contao 4.12.1 is OK,
tinyMCE in standard CE text is OK

4.12.1 `{{insert_article::59}}`
4.12.2 `<p>{{insert_article::59}}</p>`

**Comment by aschempp** [comment] 2021-10-08 04:56
As far as I know, tinyMCE always adds <p> tag on every line on the input - since always. Maybe you disabled tinyMCE in your Contao 4.12.1?

**Comment by berecont** [comment] 2021-10-08 05:24
[same issue here](https://community.contao.org/de/showthread.php?81784-Newsletter-insert-tag-nach-update-auf-4-12-2-mit-lt-p-gt-und-lt-p-gt-umklammert)  
no, i didn't disabled tinyMCE in my 4.12.1
I did two parallel tests - one in a local installtion with 4.12.1 » there's no problem, and one in an online installation with 4.12.2 » and there's the problem with `<p>` tags
note that I refer in both to newsletter

**Comment by ausi** [comment] 2021-10-08 06:54
Duplicate of #3562

**Closed as completed by ausi** 2021-10-08 06:54 UTC
