### ISSUE TITLE
ListingBundle - Missmatch between DCA Configuration and Module

### ISSUE THREAD

**Issue by b3nzin** [contao/contao#4483] opened 2022-04-07 13:41 UTC
### Affected version(s)

4.9,4.13,5.x

### Description

Hi,

in: contao/listing-bundle/src/Resources/contao/modules/ModuleListing.php
Line 78 und 79 there is no check if **list_where** and **list_info_where** has a value. This will result in an error, when nothing is entered in the Contao Backend.

In the DCA the fields **list_where** and **list_info_where** are not marked as mandatory, so the can be left blank.

This will result then in an error.

Solution:
1.) Check if $this->list_where && $this->list_info_where has an value or 
2.) make list_where && list_info_where mandatory in the Backend.

I would prefer Solution 1, cause not every there is a where field or the function has to be used.

**Comment by cliffparnitzky** [comment] 2022-04-07 14:01
I can confirm. The issue is reproducable in the demo:
- got to the module "Applications - Listing" (ID: 62) and remove the values from the fields `Condition` and `Details page condition`
- open the page: https://demo.contao.org/en/applications.html

**Comment by leofeyer** [comment] 2022-05-02 13:13
> This will result in an error, when nothing is entered in the Contao Backend.

What is the error message?

**Comment by fritzmg** [comment] 2022-05-02 13:36
See #4547 - but it was only fixed in Contao 4.13: https://github.com/contao/contao/pull/4549

**Comment by cliffparnitzky** [comment] 2022-05-02 20:30
Okay, when confirming I only checked Contao 4.13. Sorry.

Currently my Contao 4.9 test system doen't produce an error, when the conditions are not filled. So, for me it seems to be a Contao 4.13 error which may be solved with #4549

**Comment by fritzmg** [comment] 2022-05-02 20:41
> Currently my Contao 4.9 test system doen't produce an error, when the conditions are not filled

Did you test with PHP 8?

**Comment by cliffparnitzky** [comment] 2022-05-02 21:05
Yep. No problems with Contao 4.9.28 and PHP 8.1.

**Comment by leofeyer** [comment] 2022-05-03 09:23
Great, then I‘m closing this in favor of #4549.

**Closed as completed by leofeyer** 2022-05-03 09:23 UTC
Labels: bug
