### ISSUE TITLE
addDefaultLabels breaks in tl_page when using extensions

### ISSUE THREAD

**Issue by bennyborn** [contao/contao#1311] opened 2020-02-12 10:02 UTC
**Affected version(s)**
4.9.0-RC2 (reported by our users as low as 4.8)

**Description**
If any extension adds fields to `tl_page` and is still using the old way, setting the field label by reference, all core labels for `tl_page` are left empty.

As far as we've seen it seems that `tl_page` behaves a bit different to all the other DCA's. While in other DCA's the language files get loaded BEFORE the DCA itself it seems that with `tl_page` it is the opposite way.

Furthermore the `DcaLoader::addDefaultLabels` method has some kind of strange caching behaviour. 
If called once and the language file was loaded, it simply exits. https://github.com/contao/contao/blob/3a70ea01a545d97481c3120fcd847eb878dc1ad7/core-bundle/src/Resources/contao/library/Contao/DcaLoader.php#L146-L150 When debugging this we found that the method gets indeed called multiple times and on the first two calls the `$GLOBALS['TL_LANG']` is not fully populated with all translations and only seems to contain the translations of the labels defined by reference.

_Update 12.02.2020 15:21
After trying to investigate further I only got even more confused. I thought the labels being referenced is the main issue but nope. Rewrote our extension to not use the labels by reference and still not luck :(_

**How to reproduce**
Install any extension that adds fields to the `tl_page` and has it's labels defined by reference (eg. https://github.com/numero2/contao-opengraph3 or https://github.com/isotope/core). Go into the Site Structure and edit any page.

![image](https://user-images.githubusercontent.com/226890/74324278-1404bd00-4d87-11ea-8391-f6a77ba38a37.png)

**Comment by leofeyer** [comment] 2020-02-13 13:54
I cannot reproduce this issue. I have added `isotope/isotope-core` to my local Contao 4.9.0-RC2 installation and I have checked the site structure – all labels are there. 🤷‍♂

**Comment by bennyborn** [comment] 2020-02-13 20:07
@leofeyer  Strange. Could you please give it a try with the current release of `numero2/contao-marketing-suite`?

It's the same setup as with all other extensions (simple DCA additions). Maybe it has something to do with the naming or the internal order of the modules being loaded (although we strictly load our module after the core modules).

I've managed to get this behaviour a couple of times across different versions with different extensions (even on 4.8) but unfortunately I've not yet found a way to get it to break every time...

**Comment by leofeyer** [comment] 2020-02-18 07:50
It is the same with `numero2/contao-marketing-suite`. All labels are there.

**Comment by bennyborn** [comment] 2020-02-18 07:58
> It is the same with `numero2/contao-marketing-suite`. All labels are there.

Great. Fresh 4.9 RC2 here and all Core labels are missing :D
Can you tell me which PHP version you're testing this on? We're still on 7.3, maybe thats a clue...

Update: For Further investigation I just added composer.json and composer.lock as attachment - just to be on the safe side.

[composer.zip](https://github.com/contao/contao/files/4218051/composer.zip)

**Comment by dmolineus** [comment] 2020-02-27 16:30
I have an installation where this error also occurs. In this case it's caused by `pct_theme_settings` module. It loads the `tl_news` data container in the `initializeSystem` hook without loading the language file.

So it seems that the error occurs if any module calls `Contao\Controller::loadDataContainer` without `Contao\System::loadLanguageFile` called before.

/cc @timgatzky Maybe you should use the `loadDataContainer` hook instead the `initializeSystem` for that purpose

**Comment by timgatzky** [comment] 2020-02-28 07:20
If it is a system break to call loadDataContainer w/o loadLanguageFile, the loadDataContainer function should call it.

> /cc @timgatzky Maybe you should use the loadDataContainer hook instead the initializeSystem for that purpose

I could

**Comment by dmolineus** [comment] 2020-02-28 08:36
> If it is a system break to call loadDataContainer w/o loadLanguageFile, the loadDataContainer function should call it.

I agree, the origin issue should be fixed.

>> /cc @timgatzky Maybe you should use the loadDataContainer hook instead the initializeSystem  for that purpose

> I could

That's the puprose of the `loadDataContainer` hook. So in the case of the menitioned extension there is no need to manually loading the data container ;-)

**Comment by leofeyer** [comment] 2020-03-09 14:27
> If it is a system break to call loadDataContainer w/o loadLanguageFile, the loadDataContainer function should call it.

There are valid use-cases to call `loadDataContainer()` without loading the language file first, therefore those two functions are separate and have always been separate – even in Contao 4.4:

https://github.com/contao/contao/blob/3e772fce96656665311e24f11cefb50ea5b5451e/core-bundle/src/Resources/contao/library/Contao/Controller.php#L1253-L1257

If you know that you will need the labels, you have to call `loadLanguageFile()` before calling `loadDataContainer()`, just like the core does at various places:

https://github.com/contao/contao/blob/3e772fce96656665311e24f11cefb50ea5b5451e/core-bundle/src/Resources/contao/classes/Backend.php#L367-L369

https://github.com/contao/contao/blob/3e772fce96656665311e24f11cefb50ea5b5451e/core-bundle/src/Resources/contao/dca/tl_module.php#L822-L823

https://github.com/contao/contao/blob/3e772fce96656665311e24f11cefb50ea5b5451e/core-bundle/src/Resources/contao/drivers/DC_Table.php#L570-L571

**Comment by bennyborn** [comment] 2020-03-09 14:43
> There are valid use-cases to call `loadDataContainer()` without loading the language file first, therefore those two functions are separate and have always been separate – even in Contao 4.4:

Yeah, those two functions should be kept seperate from another.

@leofeyer Any update regarding https://github.com/contao/contao/issues/1311#issuecomment-587328880? It is still a serious problem since we'd like to ship Contao installations that do not look like they're broken ;)

**Comment by leofeyer** [comment] 2020-03-09 14:50
As I have said, I cannot reproduce the problem. I have already updated several websites to Contao 4.9, some run on PHP 7.2, most of them on PHP 7.3 and a few on PHP 7.4. The issue did not occur in any on them. 🤷‍♂

**Comment by bennyborn** [comment] 2020-03-10 18:38
@leofeyer Any way we can elaborate a solution in private? We can provide a testing environment for you to check it out.

**Comment by akroii** [comment] 2020-03-11 19:54
My answer does not help to solve the topic. But I'm having the same issue.
I turned on the debug mode, this is what i got:
<img width="1326" alt="Bildschirmfoto 2020-03-11 um 20 49 59" src="https://user-images.githubusercontent.com/8830861/76458188-711d7e00-63da-11ea-8c5b-c6ca665ad4c6.png">

No stacktrace... nothing

**Comment by bennyborn** [comment] 2020-03-11 19:58
> My answer does not help to solve the topic. But I'm having the same issue.

So you're also missing the field labels in `tl_page`?
If so can you tell us which extensions, if any, you've installed?

**Comment by akroii** [comment] 2020-03-11 20:01
Sure, I'am using Contao 4.9.1
```
        "alnv/catalog-manager": "^1.31",
        "christianbarkowsky/rel-canonical": "^3.3",
        "codefog/contao-instagram": "^1.1",
        "contao/calendar-bundle": "^4.4",
        "contao/comments-bundle": "^4.4",
        "contao/conflicts": "*@dev",
        "contao/manager-bundle": "^4.8",
        "contao/news-bundle": "^4.4",
        "derhaeuptling/contao-lazy-images": "^3.0",
        "dklemmt/contao_dk_mmenu": "^3.1",
        "erdmannfreunde/euf_conversion_tracking": "^0.1.1",
        "erdmannfreunde/euf_overlay": "^1.2",
        "fritzmg/contao-lightcase": "^2.1",
        "fritzmg/contao-news-related": "^1.3",
        "fritzmg/contao-sharebuttons": "^2.1",
        "fritzmg/contao-swiper": "^3.3",
        "inspiredminds/contao-wowjs": "^1.0",
        "jrgregory/m17-sticky-backend-footer": "^2.0",
        "ma3xl3/contao-easy-favicon": "^2.0",
        "madeyourday/contao-rocksolid-antispam": "^2.0",
        "marebe1602/mae_event_categories": "^1.5",
        "numero2/contao-marketing-suite": "^1.0",
        "numero2/contao-opengraph3": "^4.1",
        "oneup/contao-cache-warmup": "dev-feature/contao-4",
        "oneup/contao-mailchimp": "^4.4",
        "terminal42/contao-leads": "^1.4",
        "terminal42/contao-url-rewrite": "^1.3"
```

**Comment by akroii** [comment] 2020-03-11 20:09
Oh, I've uninstalled oneup/contao-cache-warmup and the labels are back again. 😳

**Comment by bennyborn** [comment] 2020-03-11 20:11
> Oh, I've uninstalled oneup/contao-cache-warmup and the labels are back again. 😳

Which is an indication for me that there must be something wrong in the core since we've never used that extension :\

**Comment by dmolineus** [comment] 2020-03-12 07:49
> If you know that you will need the labels, you have to call loadLanguageFile() before calling loadDataContainer(), just like the core does at various places:

Is it a requirement to call `loadLanguageFile()` before `loadDataContainer()` if you need the translations? Then this is a risky, probably broken design. Using `\Contao\PageModel::find()` will load the data container without loading the language file. So you would have to check for every page model query in the backend if you're in the context that the language file is required. I hope there will be a better solution/fix for it.

**Comment by dmolineus** [comment] 2020-03-12 08:09
I had a look on it, imho the logic in line 141 is broken:

https://github.com/contao/contao/blob/3a70ea01a545d97481c3120fcd847eb878dc1ad7/core-bundle/src/Resources/contao/library/Contao/DcaLoader.php#L141-L144

The existence of `$GLOBALS['TL_LANG'][$this->strTable]` doesn't guarantee that the language file is loaded. If any label is set by reference, the language array exists.

Probably following condition would fix it (works in my project with this issue).

```php
		if (!isset(static::$arrLanguageFiles[$this->strTable]))
		{
			return;
		}
```

**Comment by leofeyer** [comment] 2020-03-12 08:12
Thank you @dmolineus, I will look into this.

@bennyborn Does the fix solve your problem as well?

**Comment by bennyborn** [comment] 2020-03-12 08:19
@leofeyer Houston, we have a fix! :)

**Comment by leofeyer** [comment] 2020-03-27 15:53
Thanks again @dmolineus for debugging this one. 👍

**Closed as completed by leofeyer** 2020-03-27 15:53 UTC
Labels: bug
