### ISSUE TITLE
Cannot move tl_content record to nested child

### ISSUE THREAD

**Issue by aschempp** [contao/contao#6703] opened 2024-01-11 10:20 UTC
### Affected version(s)

5.3

### Description

I tried to move an element from the article (first level) to a child (second level nested), the paste operation worked but nothing happened.

**Comment by aschempp** [comment] 2024-01-11 10:21
Well that's not true. My record is gone. I guess it updated the `pid` but not `ptable`. And it is also gone in my database (I guess `reviseTable` dropped it because that article ID does not exist).

**Comment by aschempp** [comment] 2024-01-11 10:34
I can also not copy a nested element to another nested element (same `ptable`).

**Comment by leofeyer** [comment] 2024-01-11 10:43
I can confirm the issue.

We had this problem originally, and I added a workaround in 5f080130c2fc5fcc8ce35057dd5c7a81a2b916b1, which was later replaced in 77c80cba3bb7aee20cafb789ef06100ccbf54e0a. I have not had the problem since. @ausi /cc

Could this be caused by the permission changes that we merged recently?

**Closed as completed** 2024-01-12 06:18 UTC
Labels: bug
