### ISSUE TITLE
Backend Select with Icons

### ISSUE THREAD

**Issue by erikherbert** [contao/contao#4246] opened 2022-03-08 08:20 UTC
### Description

<img width="964" alt="Selects2022" src="https://user-images.githubusercontent.com/1622733/157195480-c57aefda-5da6-40c3-97b7-a90d3d7804bb.png">

After working with Wordpress Elementor for a while and being very satisfied with the graphical workflow, I asked myself whether it wouldn't make sense to also store an icon for some selections in the backend (svg, 35x35px)

**Comment by aschempp** [comment] 2022-03-08 08:23
That looks nice! I've seen something like that from @qzminski a while ago, maybe he has some input?

**Comment by asaage** [comment] 2022-03-08 08:26
duplicate of https://github.com/contao/contao/issues/721

**Closed** 2022-03-08 09:01 UTC
Labels: feature
