### ISSUE TITLE
FAQ and newsletter list broken URLs

### ISSUE THREAD

**Issue by ausi** [contao/contao#5080] opened 2022-08-03 11:41 UTC
### Affected version(s)

5.0.0-RC1

### Description

In https://github.com/contao/contao/blob/eb669536225740719a99927f1518605e4bfe2c48/faq-bundle/contao/modules/ModuleFaqList.php#L151 and in https://github.com/contao/contao/blob/eb669536225740719a99927f1518605e4bfe2c48/newsletter-bundle/contao/modules/ModuleNewsletterList.php#L108 a URL with the placeholder `%s` is created. But `getFrontendUrl()` URL encodes it to `%25s` which breaks the later `sprintf()` call.

In Contao 4.13 this was handled by `applyLegacyLogic()` https://github.com/contao/contao/blob/daee55bdc2c0c24f6d2c8a3f0c40a7fc36ad2ed8/core-bundle/src/Resources/contao/models/PageModel.php#L1495 but this no longer exists in Contao 5.0

Should we get rid of the `sprintf()` and generate the URL with the correct alias directly?

/cc @aschempp

**Comment by fritzmg** [comment] 2022-08-03 12:46
Duplicate of https://github.com/contao/contao/issues/5007

**Closed as completed** 2022-08-03 13:01 UTC
Labels: bug
