### ISSUE TITLE
Entering an event with Starttime but without Endtime does not work anymore

### ISSUE THREAD

**Issue by joehi** [contao/contao#432] opened 2019-04-10 17:46 UTC
**Affected version(s)**
Contao 4.7.3
Contao 4.4.37

**Description**  
When you create or update an event with starttime and startdate but without endtime and enddate and save it, the event will have the actual time of the moment you saved it as the endtime.

**How to reproduce**  
Just create or update an event with empty fields for endtime and enddate and save it. 

**How to (temporarily) solve this problem**
Enter the same values as the starttime into the field of the endtime before saving. Then you will get an event without endtime.

I am afraid that this problem is caused due to the fix for issue "Time "01:00" o'clock at events changes to "0" when reediting the event" #420

**Comment by OMOSde** [comment] 2019-04-10 18:35
Duplicate of https://github.com/contao/contao/issues/428

**Closed as completed** 2019-04-10 18:38 UTC
