### ISSUE TITLE
$this->figure does not render options / class in .html5 templates

### ISSUE THREAD

**Issue by xApep** [contao/contao#5525] opened 2022-11-23 15:14 UTC
### Affected version(s)

4.13.13

### Description

I have defined sizes in config.yml.

in my html5 template I print image as

`<?php echo $this->figure($item->singleSRC, [0,0, "_dummy"], ['options' => ['attr' => ['class' => 'css-class']]]);  ?>`

Now image does render correctly but there is not class.

```
<figure class="image_container">
  <picture>
    <source srcset="assets/images/e/x%20bedouin%20luxury%20villa%20tent%2007%201%20copy-42ad9699.webp" type="image/webp" width="340" height="280">
    <img src="assets/images/8/x%20bedouin%20luxury%20villa%20tent%2007%201%20copy-9189afcf.jpg" width="340" height="280" alt="" loading="lazy">
  </picture>
</figure>
```

when dumping $this in image.html5 I get this

![image](https://user-images.githubusercontent.com/1315340/203581852-8c33229a-86a7-40a5-a9a9-f59bf002d10a.png)

**Comment by fritzmg** [comment] 2022-11-23 15:40
iirc this is unsupported by the default `image.html5` template. /cc @m-vo

**Comment by m-vo** [comment] 2022-11-23 18:03
Yes. Duplicate of #5367.

**Closed as completed by m-vo** 2022-11-23 18:03 UTC
Labels: bug, unconfirmed

**Comment by xApep** [comment] 2022-11-23 19:45
I have solved this by adding `<?= $this->attr['class']; ?>` to figure html tag in image.html5

Tnx for the feedback.
