### ISSUE TITLE
TinyMCE funktioniert nach Update 4.10.0-RC2 > 4.10.0-RC3 nicht mehr (Problem 2) 

### ISSUE THREAD

**Issue by ghost** [contao/contao#2112] opened 2020-08-06 15:07 UTC
**var/logs:**

[2020-08-06 15:39:02] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\SyntaxErrorException: "An exception occurred while executing 'SELECT DISTINCT `type` FROM tl_page WHERE id IN()': SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1" at /home/xxx/www/archiv.xxx.ch/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 79 {"exception":"[object] (Doctrine\\DBAL\\Exception\\SyntaxErrorException(c ode: 0): An exception occurred while executing 'SELECT DISTINCT `type` FROM tl_page WHERE id IN()':\n\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1 at /home/xxx/www/archiv.xxx.ch/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:79, Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1 at /home/xxx/www/archiv.xxx.ch/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:83, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1 at /home/xxx/www/archiv.xxx.ch/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:78)"} [] 

**StackTrace:**

**[1/3] PDOException**

PDOException:
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1

at vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:78
at PDO->query('SELECT DISTINCT `type` FROM tl_page WHERE id IN()')
(vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:78)
at Doctrine\DBAL\Driver\PDOConnection->query('SELECT DISTINCT `type` FROM tl_page WHERE id IN()')
(vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:911)
at Doctrine\DBAL\Connection->executeQuery('SELECT DISTINCT `type` FROM tl_page WHERE id IN()')
(vendor/contao/core-bundle/src/Resources/contao/library/Contao/Database/Statement.php:274)
at Contao\Database\Statement->query()
(vendor/contao/core-bundle/src/Resources/contao/library/Contao/Database/Statement.php:248)
at Contao\Database\Statement->execute(array())
(vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php:5698)
at Contao\DC_Table->filterMenu(1)
(vendor/contao/core-bundle/src/Resources/contao/classes/DataContainer.php:1170)
at Contao\DataContainer->panel()
(vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php:352)
at Contao\DC_Table->showAll()
(vendor/contao/core-bundle/src/Resources/contao/classes/Backend.php:644)
at Contao\Backend->getBackendModule('page', null)
(vendor/contao/core-bundle/src/Resources/contao/controllers/BackendMain.php:167)
at Contao\BackendMain->run()
(vendor/contao/core-bundle/src/Controller/BackendController.php:48)
at Contao\CoreBundle\Controller\BackendController->mainAction()
(vendor/symfony/http-kernel/HttpKernel.php:158)
at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
(vendor/symfony/http-kernel/HttpKernel.php:80)
at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
(vendor/symfony/http-kernel/Kernel.php:201)
at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
(web/index.php:31)
at require('/home/peterfl/www/archiv.peter-flueckiger.ch/web/index.php')
(web/app.php:4) 

**[2/3] PDOException**

Doctrine\DBAL\Driver\PDOException:
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1

at vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:83
at Doctrine\DBAL\Driver\PDOConnection->query('SELECT DISTINCT `type` FROM tl_page WHERE id IN()')
(vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:911)
at Doctrine\DBAL\Connection->executeQuery('SELECT DISTINCT `type` FROM tl_page WHERE id IN()')
(vendor/contao/core-bundle/src/Resources/contao/library/Contao/Database/Statement.php:274)
at Contao\Database\Statement->query()
(vendor/contao/core-bundle/src/Resources/contao/library/Contao/Database/Statement.php:248)
at Contao\Database\Statement->execute(array())
(vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php:5698)
at Contao\DC_Table->filterMenu(1)
(vendor/contao/core-bundle/src/Resources/contao/classes/DataContainer.php:1170)
at Contao\DataContainer->panel()
(vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php:352)
at Contao\DC_Table->showAll()
(vendor/contao/core-bundle/src/Resources/contao/classes/Backend.php:644)
at Contao\Backend->getBackendModule('page', null)
(vendor/contao/core-bundle/src/Resources/contao/controllers/BackendMain.php:167)
at Contao\BackendMain->run()
(vendor/contao/core-bundle/src/Controller/BackendController.php:48)
at Contao\CoreBundle\Controller\BackendController->mainAction()
(vendor/symfony/http-kernel/HttpKernel.php:158)
at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
(vendor/symfony/http-kernel/HttpKernel.php:80)
at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
(vendor/symfony/http-kernel/Kernel.php:201)
at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
(web/index.php:31)
at require('/home/peterfl/www/archiv.peter-flueckiger.ch/web/index.php')
(web/app.php:4)

**[3/3] SyntaxErrorException** 

Doctrine\DBAL\Exception\SyntaxErrorException:
An exception occurred while executing 'SELECT DISTINCT `type` FROM tl_page WHERE id IN()':

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1

at vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:79
at Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception occurred while executing \'SELECT DISTINCT `type` FROM tl_page WHERE id IN()\':SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near \')\' at line 1', object(PDOException))
(vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:169)
at Doctrine\DBAL\DBALException::wrapException(object( Driver), object(PDOException), 'An exception occurred while executing \'SELECT DISTINCT `type` FROM tl_page WHERE id IN()\':SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near \')\' at line 1')
(vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:149)
at Doctrine\DBAL\DBALException::driverExceptionDuring Query(object(Driver), object(PDOException), 'SELECT DISTINCT `type` FROM tl_page WHERE id IN()', array())
(vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:914)
at Doctrine\DBAL\Connection->executeQuery('SELECT DISTINCT `type` FROM tl_page WHERE id IN()')
(vendor/contao/core-bundle/src/Resources/contao/library/Contao/Database/Statement.php:274)
at Contao\Database\Statement->query()
(vendor/contao/core-bundle/src/Resources/contao/library/Contao/Database/Statement.php:248)
at Contao\Database\Statement->execute(array())
(vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php:5698)
at Contao\DC_Table->filterMenu(1)
(vendor/contao/core-bundle/src/Resources/contao/classes/DataContainer.php:1170)
at Contao\DataContainer->panel()
(vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php:352)
at Contao\DC_Table->showAll()
(vendor/contao/core-bundle/src/Resources/contao/classes/Backend.php:644)
at Contao\Backend->getBackendModule('page', null)
(vendor/contao/core-bundle/src/Resources/contao/controllers/BackendMain.php:167)
at Contao\BackendMain->run()
(vendor/contao/core-bundle/src/Controller/BackendController.php:48)
at Contao\CoreBundle\Controller\BackendController->mainAction()
(vendor/symfony/http-kernel/HttpKernel.php:158)
at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
(vendor/symfony/http-kernel/HttpKernel.php:80)
at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
(vendor/symfony/http-kernel/Kernel.php:201)
at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
(web/index.php:31)
at require('/home/peterfl/www/archiv.peter-flueckiger.ch/web/index.php')
(web/app.php:4)

**Comment by aschempp** [comment] 2020-08-06 15:07
Duplicate of https://github.com/contao/contao/issues/2111

**Closed as completed by aschempp** 2020-08-06 15:07 UTC
