### ISSUE TITLE
Show protected pages only in sitemap for contao searchcrawler

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#2753] opened 2021-02-16 09:19 UTC
**Affected version(s)**
Contao 4.11

**Description**
With the new dynamic sitemap-generator it should be possible to fix this old ticket (https://github.com/contao/contao/issues/1407)

**How to reproduce**

1. Set `index_protected:true` in `config.yml`
2. Set robots-tag to `noindex,follow`
3. set `Protect page`

The page would appear in public sitemap.xml, but should only appear for the contaocrawler.

**Comment by leofeyer** [comment] 2021-02-16 09:22
What is the purpose of this ticket?

**Comment by fritzmg** [comment] 2021-02-16 09:23
~Duplicate of https://github.com/contao/contao/pull/2295~

**Comment by contaoacademy** [comment] 2021-02-16 09:24
Sorry, send it too fast

**Comment by fritzmg** [comment] 2021-02-16 09:24
@contaoacademy or is there a bug you noticed in the current RC?

**Comment by contaoacademy** [comment] 2021-02-16 09:25
I talked to toflar and he said, that the new sitemap-generator didn't fix the problem, but now is possible to fix the problem.

**Comment by contaoacademy** [comment] 2021-02-16 09:26
Yes, I tested this with contao 4.11.x-dev

**Comment by contaoacademy** [comment] 2021-02-16 09:41
**My wanted result:**
Protected pages should be indexed by contaocrawler but NOT appear in the public sitemap.xml for Google.

**Comment by ausi** [comment] 2021-02-16 12:49
> Set robots-tag to `noindex,follow`

This needs to be set to `index,follow` for your use case I think.

**Comment by fritzmg** [comment] 2021-02-16 13:20
> This needs to be set to `index,follow` for your use case I think.

This will also show the page in the "public" `sitemap.xml` currently (when using `contao.search.index_protected: true`). In #1407 we discussed to implement a fix for Contao 4.11, so that protected pages are not shown in the regular `sitemap.xml`, but still crawled by the crawler (and thus indexed), when using `contao.search.index_protected: true`.

This has not been implemented yet. #2295 laid the groundwork for that fix.

**Comment by leofeyer** [comment] 2021-02-16 14:10
> Protected pages should be indexed by contaocrawler but NOT appear in the public sitemap.xml for Google.

This is the case already, isn't it? Google is never logged in, so they only see the public pages in the sitemap. The Crawler, however, can use an authenticated member and thus also see protected pages.

**Comment by fritzmg** [comment] 2021-02-16 15:12
As far as I tested, this is not the case. If I set the protected page to `index,follow`, then the page is also visible in the public `sitemap.xml`. If I set the protected page to `noindex,nofollow`, then the page is not crawled by the Crawler.

**Comment by contaoacademy** [comment] 2021-02-16 15:37
> As far as I tested, this is not the case. If I set the protected page to `index,follow`, then the page is also visible in the public `sitemap.xml`. If I set the protected page to `noindex,nofollow`, then the page is not crawled by the Crawler.

Yes, this is also my result.

**Closed as completed** 2021-03-04 09:56 UTC
Labels: bug

**Comment by contaoacademy** [comment] 2021-08-11 14:56
@leofeyer Danke. In der Contao 4.11-dev läuft das jetzt wie erwartet.
