### ISSUE TITLE
Backend search for articles doesn't show all results

### ISSUE THREAD

**Issue by zoglo** [contao/contao#7366] opened 2024-07-25 12:37 UTC
### Affected version(s)

4.13

### Description

Whilst trying to search for articles with a specific title, I didn't see all results.

E.g.
![image](https://github.com/user-attachments/assets/49335cd3-fa48-4c0c-a3bc-90ef0b023975)

I've found out that it happens due to the following LOC within the eliminateNestedPages method:
https://github.com/contao/contao/blob/3cb2d3f5f021cfc60fdf3035c9727cc695912d29/core-bundle/src/Resources/contao/library/Contao/Controller.php#L1615

https://github.com/contao/contao/blob/3cb2d3f5f021cfc60fdf3035c9727cc695912d29/core-bundle/src/Resources/contao/library/Contao/Controller.php#L1601-L1618

After commenting that one out, I get all expected results.
![image](https://github.com/user-attachments/assets/46428782-6379-46ef-a700-bb2b23c34c39)

### Reproducing the issue

I wasn't able to reproduce the issue within the demo but provided an anonymous sql dump.
[contaobug.sql.gz](https://github.com/user-attachments/files/16377688/contaobug.sql.gz)

1. Select the rootpage Page_1
2. Switch to `Articles`
3. Search for the Title `Problem_`
4. Do the same search when commenting out the mentioned LoC

### Related issues

It looks like this was coded by @aschempp in 2010/2011 and is related to the following two issues:
https://github.com/contao/core/issues/2475
https://github.com/contao/core/issues/3423

**Comment by zoglo** [comment] 2024-07-25 13:19
The Page ID 7431 should appear in the normal search, however this one doesn't appear.
This is the trail
![image](https://github.com/user-attachments/assets/3d13ceb6-9390-4636-a968-cc4a9a087143)

**Comment by Toflar** [comment] 2024-07-29 08:56
The issue is that `root` is considered to work like a permission restriction. Meaning that when page `8755` is not part of `root` we also eliminate nested pages from it -> `7431` and the entire subtree is removed. That's why we have those `eliminateNestedPages()` calls in many different places.

The problem is that both, the breadcrumb but also the filters (including the search box) also use `root` to restrict the tree. But in this case, it should **not** remove nested pages because those might also have matches (like in your case). So it's a mixture between when it has to work like permissions and when it has to only restrict the view (= not removing nested pages).

I'm sorry but while I consider this to be a major bug, I don't think we'll be ever able to fix this with the current setup. Too much code, too many calls in too many places with too many possible side-effects.

**Comment by zoglo** [comment] 2024-07-29 10:21
Simply something that came up - I'll leave a query in here for people that want to search even further and don't need the backend search if anyone ever stumbles across something like that ever again.

That's an example for listing every article with the content type `module`.
```sql
SELECT
  p.title as Page,
  p.id as PageID,
  a.title as Article,
  a.id as ArticleID,
  c.type as ContentElement,
  c.id as ContentElementID
FROM `tl_content` c
LEFT JOIN `tl_article` a
  on c.pid = a.id
LEFT JOIN `tl_page` p
  on a.pid = p.id
WHERE
  c.type = 'module'
```

Should I close this as "not planned" @Toflar? Thanks for investigating as well

**Comment by leofeyer** [comment] 2024-07-29 10:57
That‘s a bummer indeed. I think @Toflar is right that we cannot fix this without causing side effects. 😞 Shall I add the "up for discussion" label anyway?

**Comment by zoglo** [comment] 2024-07-29 11:53
We kinda discussed this on Thursday but it was a newly opened issue.
If toflar has more information on it, we could add the label.

**Comment by aschempp** [comment] 2024-07-30 07:22
see https://github.com/contao/contao/pull/7380

**Comment by leofeyer** [comment] 2024-08-22 14:45
As discussed in the Contao call, this can possibly be fixed by either finding the root pages of the search results and generating them or by splitting the `root` array into a permissions array and a search results array.

**Closed as completed** 2024-08-23 12:07 UTC
Labels: bug
