### ISSUE TITLE
Broken Authentication – Session Token bug

### ISSUE THREAD

**Issue by aschempp** [contao/contao#7549] opened 2024-09-23 12:46 UTC
### Affected version(s)

all

### Description

The password reset token is not invalidated if the user password is changed. The password reset link should no longer work if the password is changed.

STEPS TO REPRODUCE:

1. Create a new account
2. Confirm your email
3. Now request a password reset
4. Don’t use the password reset link that was sent to your email
5. Login to your account, remember don’t use the reset password link you requested in 3 step
6. Change your password in the Account Settings
7. After you change your password inside your account, Check the reset password link you requested in Step 3 in your email.
8. Change your password using the reset password token you requested.

Originally reported by @kunalmhaske21212

**Comment by kunalmhaske21212** [comment] 2024-09-23 12:55
Hello @aschempp ,\
Can you please cancel the recent payment. Because my PayPal address is different.
My PayPal address: kunalmhaske2121@gmail.com

**Comment by leofeyer** [comment] 2024-09-23 13:19
Duplicate of #7510.

**Closed as not planned by leofeyer** 2024-09-23 13:19 UTC
Labels: bug
