### ISSUE TITLE
Hide / disable functions in the backend dashboard that the user is not allowed to invoke instead of showing an exception

### ISSUE THREAD

**Issue by AlexanderWillner** [contao/contao#5340] opened 2022-10-05 18:57 UTC
### Affected version(s)

4.13.10

### Description

Steps that will reproduce the problem?
1. Log into the backend as user `A`
2. Change something
3. Log into the backend a user `B`
4. Remove permissions for user `A` that was needed for change in Step 2
5. Login as user `A`
6. Have a look at the latest changes that user `A` made in the dashboard
7. Click on `edit` for the last change

What is the expected result?

* Either the edit button is greyed out
* Or the line is hidden
* Or a pop-up / warning that the user is not allowed to modify this change

What happens instead?

The user sees an AccessDeniedHttpException `Back end module "XXX" is not allowed for user "XXX"`.

Possible workaround:

n/a

Any additional information:
 
n/a

**Comment by leofeyer** [comment] 2022-10-26 15:46
Duplicate of #733

As discussed in #733, this is a known limitation until we can use permission voters to check the permissions in the version table. So this will be fixed eventually.

**Closed as completed by leofeyer** 2022-10-26 15:46 UTC
Labels: bug, unconfirmed
