### ISSUE TITLE
New version of ScssPhp breaks scss import paths for Contao

### ISSUE THREAD

**Issue by markusmilkereit** [contao/contao#2495] opened 2020-11-13 16:24 UTC
In Contao 4.9 the import of relative paths over multiple bundles breaks now, because the path handling behaviour in https://github.com/scssphp/scssphp has changed in their newest version 1.4. If the current file path is not attached (additionally to `$objCompiler->setImportPaths`) it will always be hardcoded/relative to the webroot. 

If you for example include a variable from another bundle:
```SCSS
@import '../../../../../magmell-basic/src/Resources/public/css/variables';
```
the path gets resolved to `htdocs/web/../../../../../magmell-basic/src/Resources/public/css/_variables.scss` which results in an access violation for basedir restrictions (we would try to access 3 levels below basedir).

 The developer recognizes it as breaking change, but suggests a code fix, which will actually fix the problem to Combiner.php line 419: 
```PHP
return $this->fixPaths($objCompiler->compile($content, $this->strRootDir . '/' . $arrFile['name']), $arrFile);
```

With everything updated I can confirm that this fixes the problem - but don't know how to connected the necessary fix to only be active in ScssPhp versions of 1.4+

See also https://github.com/scssphp/scssphp/issues/271

**Comment by stof** [comment] 2020-11-13 17:28
> With everything updated I can confirm that this fixes the problem - but don't know how to connected the necessary fix to only be active in ScssPhp versions of 1.4+

Adding the second argument to `compile()` won't break scssphp 1.3 (the argument was already there, but used only for error reporting and sourcemaps). If you need to keep support for scssphp 1.3, keep the configuration of `setImportPaths()` that you have currently.

**Comment by aschempp** [comment] 2020-11-16 07:17
Looks like scssphp/scssphp ^1.4 is still compatible with PHP 5.6, so we could just raise the minimum dependency for Contao 4.4, 4.9, 4.10 to version 1.4. @markusmilkereit did you mean that we don't need the `fixPaths` methods at all with version 1.4?

**Comment by markusmilkereit** [comment] 2020-11-16 07:38
@aschempp I did not look deeper into `fixpaths`, the change that works is actually this addition to the existing line, second parameter for `compile()`: 
```PHP
$this->strRootDir . '/' . $arrFile['name']
```
without changing anything around it. That was the suggestion from the scssphp developer, because the internal path resolution has been "cleaned up" and not using the second argument for `compile()` resolves relative paths differently.

**Comment by markusmilkereit** [comment] 2020-11-17 08:11
@aschempp short update on urgency: all our bigger projects break after the update, and I would guess it's not SOP (yet) to use SCSS includes over multiple bundles, but many bigger projects will have the same problem.

**Comment by ausi** [comment] 2020-11-17 08:24
@contao/developers should we add a conflict for `"scssphp/scssphp": "^1.4"` to `contao/conflicts` until we have fixed this?

**Comment by leofeyer** [comment] 2020-11-17 08:34
Yes, we probably should. 👍🏻

**Comment by ausi** [comment] 2020-11-17 08:53
`contao/conflicts` done: https://github.com/contao/conflicts/pull/14

**Comment by leofeyer** [comment] 2020-12-01 16:30
The proposed fix `$objCompiler->compile($content, $this->strRootDir . '/' . $arrFile['name'])` seems right as far as I could tell from reading the code. However, I failed to reproduce the initial problem.

@markusmilkereit Can you please elaborate on how to reproduce this?

**Comment by stof** [comment] 2020-12-01 16:51
@leofeyer do you have a basedir restriction applied ?

@markusmilkereit could you check whether https://github.com/scssphp/scssphp/pull/278 fixes the issue you faced when upgraded to scssphp 1.4.0 ?

> The proposed fix `$objCompiler->compile($content, $this->strRootDir . '/' . $arrFile['name'])` seems right as far as I could tell from reading the code.

This change is a sensible change anyway. When the content is loaded from a file, passing the file path to scssphp will provide better error messages and better sourcemaps (already in 1.3.x) and will provide a more spec-compliant resolution of imports in the file (as of 1.4.0) which might remove the need to add the folder as an import path (you might still want to add it if you want nested imports to fallback to that source folder though, which is the actual use case for import paths, not relative imports)

**Comment by leofeyer** [comment] 2020-12-01 16:56
@stof You mean `open_basedir`? Of course not. 😄

**Comment by stof** [comment] 2020-12-01 18:02
@leofeyer that's probably the missing part, given that the issue says `results in an access violation for basedir restrictions`

**Comment by markusmilkereit** [comment] 2020-12-01 19:03
The usage scenario is:
- bundle A has generic layout elements, templates and CSS files in it - including files valid for the whole project in variables.scss and mixins.scss (for example for colors defined in the CD manual)
- bundle B extends the basic bundle A with some layout elements, and includes the project-wide files variables.scss and/or mixins.scss in the SCSS files

That cross-bundle inclusion did not work anymore when scssphp 1.4 was installed. @leofeyer I can show you a couple of live usages for it - we have a couple of client projects organized like that.

**Comment by markusmilkereit** [comment] 2020-12-01 19:10
@stof I'm currently sick and can't reproduce the necessary conditions in my state, will try again when I'm back on the horse :)

**Comment by leofeyer** [comment] 2020-12-07 14:45
I actually think that we should remove the conflict from `contao/conflicts` again.

Rationale:
- The problem only occurs when `open_basedir` is set, which is an anti-pattern and should not be done anyway.
- If someone still wants to use `open_basedir`, they should set the conflict in their extension or root composer.json.
- We should not prevent users who do not use `open_basedir` from upgrading.

@contao/developers WDYT?

**Comment by ausi** [comment] 2020-12-07 16:14
I think we should keep the conflict until https://github.com/contao/contao/pull/2547 got merged and released.

The problem only shows up with `open_basedir` because scssphp tries to load a file from outside the basedir. But the fact that it tries to load the file from the wrong path is still wrong and can result in unwanted effects if that file accidentally exists there.

See https://github.com/contao/contao/issues/2495#issuecomment-736677572 :

> > The proposed fix `$objCompiler->compile($content, $this->strRootDir . '/' . $arrFile['name'])` seems right as far as I could tell from reading the code.
> 
> This change is a sensible change anyway. When the content is loaded from a file, passing the file path to scssphp will provide better error messages and better sourcemaps (already in 1.3.x) and will provide a more spec-compliant resolution of imports in the file ...

**Comment by leofeyer** [comment] 2020-12-07 16:16
Reopening this as a reminder to revert the changes in `contao/conflict`.

**Comment by leofeyer** [comment] 2020-12-11 12:07
Reverted in contao/conflicts@b1bab2b129fd122f2d9312ace260dd17abf43466.

**Closed as completed** 2020-12-11 12:07 UTC
Labels: bug
