### ISSUE TITLE
respect news redirect target

### ISSUE THREAD

**Issue by asaage** [contao/contao#2947] opened 2021-04-12 18:31 UTC
**Affected version(s)**

Tested in demo (4.9.12)

**Description**

News-Item:
Redirect target->Custom URL->Open in new window
The link does **not** open in new window (neither layout_simple nor layout_short).
It works for events though.

![image](https://user-images.githubusercontent.com/4138336/114442382-c96e1300-9bcc-11eb-986f-d383993691c0.png)

**Comment by fritzmg** [comment] 2021-04-27 07:36
This is caused by https://github.com/contao/contao/pull/2615

I'll provide a PR.

**Comment by fritzmg** [comment] 2021-04-27 07:44
Closing in favor of #2977

**Closed as completed by fritzmg** 2021-04-27 07:44 UTC
Labels: bug
