### ISSUE TITLE
Systemwartung -> Crawler -> Funktion "Den Suchindex aktualisieren" not working

### ISSUE THREAD

**Issue by jochi44** [contao/contao#5040] opened 2022-07-25 18:07 UTC
### Affected version(s)

5.0.0-RC1

### Description

Running the crawler in Systemwartung -> Crawler -> "Den Suchindex aktualisieren" the following error is shown in /var/logs:

```
[2022-07-25T20:06:35.564351+02:00] request.INFO: Matched route "contao_backend". {"route":"contao_backend","route_parameters":{"_route":"contao_backend","_scope":"backend","_token_check":true,"_controller":"Contao\\CoreBundle\\Controller\\BackendController::mainAction"},"request_uri":"https://contao5.xyz.tld/contao?act=crawl&crawl_subscriber_names%5B0%5D=search-index&do=maintenance&jobId=ec2f09e7-f1f8-4b78-bc54-60da937584f1&ref=mZnjM_HD","method":"POST"} []
[2022-07-25T20:06:35.568026+02:00] request.CRITICAL: Uncaught PHP Exception Exception: "Missing Ajax action" at /var/www/clients/web/contao5/vendor/contao/core-bundle/contao/classes/Ajax.php line 61 {"exception":"[object] (Exception(code: 0): Missing Ajax action at /var/www/clients/web/contao5/vendor/contao/core-bundle/contao/classes/Ajax.php:61)"} []
```

**Comment by leofeyer** [comment] 2022-08-05 13:38
Duplicate of #5039

**Closed as completed by leofeyer** 2022-08-05 13:38 UTC
Labels: bug, unconfirmed
