### ISSUE TITLE
Error after update of doctrine/dbal to v2.9.0

### ISSUE THREAD

**Issue by Seefahrer** [contao/contao#212] opened 2018-12-04 08:20 UTC
Contao 4.6.9:
After updating (with some difficulties) the CM to v1.1.1 I did run a package update which updated "doctrine/dbal" to v 2.9.0.

Now the contao/install route throws fllwg error:

`
2018-12-04 09:01:30] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\SyntaxErrorException: "An exception occurred while executing 'SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'xxxxx' AND TABLE_NAME = 'tl_layout' ORDER BY ORDINAL_POSITION ASC AND COLUMN_NAME = 'sections'':  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND COLUMN_NAME = 'sections'' at line 1" at .../cmsc4ME/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 79 {"exception":"[object] (Doctrine\\DBAL\\Exception\\SyntaxErrorException(code: 0): An exception occurred while executing 'SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'xxxxxxx' AND TABLE_NAME = 'tl_layout' ORDER BY ORDINAL_POSITION ASC AND COLUMN_NAME = 'sections'':\n\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND COLUMN_NAME = 'sections'' at line 1 at .../cmsc4ME/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:79, Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND COLUMN_NAME = 'sections'' at line 1 at .../cmsc4ME/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:90, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND COLUMN_NAME = 'sections'' at line 1 at .../cmsc4ME/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:88)"} []
`

After downgrading to 2.8.1 by means of adding

```
"conflict": {
    "doctrine/dbal": "2.9.0"
},
```

to my composer.json, the install route is working again.

**Comment by ausi** [comment] 2018-12-04 08:42
This is related to the following line I think: https://github.com/contao/contao/blob/1f5396301d031a2dfe5ff59f682b9d86e9caac01/installation-bundle/src/InstallTool.php#L165

Maybe we should just query all columns instead and get the entry for `sections` via PHP?

**Comment by qzminski** [comment] 2018-12-04 09:35
@ausi it is related to that line but also to others such as https://github.com/contao/installation-bundle/blob/4.4/src/Database/Version350Update.php#L36

**Comment by leofeyer** [comment] 2018-12-04 10:14
I actually cannot reproduce the issue here with MariaDB 10.3.11. Where does the `ORDER BY ORDINAL_POSITION ASC` part in the query come from?

**Comment by leofeyer** [comment] 2018-12-04 10:44
Fixed in 8be90c341c9b1cf8ee46a7ef5748f0e89cc82cd9.

**Closed as completed by leofeyer** 2018-12-04 10:44 UTC
Labels: bug

**Comment by Seefahrer** [comment] 2018-12-04 10:58
Just to get a clue ...

Where do I need to apply those changes in Contao 4.6.9 ?

**Comment by leofeyer** [comment] 2018-12-04 11:05
Just wait for Contao 4.6.10. It will be released today.
