### ISSUE TITLE
Tablesorting active icons are reverserd

### ISSUE THREAD

**Issue by teviii** [contao/contao#7427] opened 2024-08-08 17:00 UTC
### Affected version(s)

4.13.45

### Description

Just realized that icons for the active state of the tablesorter are reversed in CSS file assets/tablesorter/css/tablesorter.min.css.
`table.sortable thead th.tablesorter-headerDesc {
  background-image: url(../images/asc.svg);
}`
and
`table.sortable thead th.tablesorter-headerAsc {
  background-image: url(../images/desc.svg);
}`

**Comment by zoglo** [comment] 2024-08-08 17:31
This raises the question if it has always been wrong since:

* Ascending = Above or Up ⏶
* Descending = Down / Downwards ⏷

https://www.ibm.com/docs/en/sdse/6.3.1.5?topic=tool-sorting (this is just one of the examples, there is much [more](https://stackoverflow.com/questions/338166/which-direction-should-the-arrows-point-in-a-sorted-table)) 
> An arrow pointing up means that column is sorted in ascending order. An arrow pointing down means that column is sorted in descending order.

__

This should most likely be fixed in [contao-components/tablesorter](https://github.com/contao-components/tablesorter)
[Mentioned CSS](https://github.com/contao-components/tablesorter/blob/cf1c4191d7fd20b327d5a03f2e84a33d247801b2/css/tablesorter.css#L8)

**Comment by fritzmg** [comment] 2024-08-08 19:16
I agree that the icon should always show the _current_ state. See also the examples of different JavaScript libraries here:

* https://tofsjonas.github.io/sortable/
* https://github.hubspot.com/sortable/

**Comment by leofeyer** [comment] 2024-08-09 13:50
I cannot reproduce the issue:

<img width="293" alt="" src="https://github.com/user-attachments/assets/a8024415-7d83-4ddd-8e82-5fa487fb109a">

<img width="295" alt="" src="https://github.com/user-attachments/assets/5355a8c2-5683-4aec-8a45-0ba37bfe2e87">

Is this just about the file names?

**Comment by zoglo** [comment] 2024-08-09 14:22
Could be, IIRC I got confused when readding the sortable icons again in 5.3.

@leofeyer mind that we are using a different sortable in 5.3, did you also test it in 4.13?

**Comment by teviii** [comment] 2024-08-09 14:36
@leofeyer on the contrary, you exactly reproduced the issue. Thinking of numbers instead of letters makes it easier. You have the order ascending, getting bigger towards the bottom. But the highlighted (black) icon is bigger at the top. Since the icons are grey, when no order is applied yet, the black icon is interpreted as the active one asigned to the order applied. So it should be small at the top for order ascending ("bergauf").

**Comment by leofeyer** [comment] 2024-08-09 14:41
Ah, I see what you mean now 👍

**Comment by leofeyer** [comment] 2024-08-16 09:35
Fixed in [contao-components/tristen-tablesort#394c7078](https://github.com/contao-components/tristen-tablesort/commit/394c707861eeb091b20686750530b845eda6e676) and [contao-components/tablesorter#9b3439f5](https://github.com/contao-components/tablesorter/commit/9b3439f59c8b7aa5e2d7a136726f7c2918c11e76).

**Closed as completed by leofeyer** 2024-08-16 09:35 UTC
Labels: bug
