### ISSUE TITLE
Form rights wont be inherited

### ISSUE THREAD

**Issue by gtwone** [contao/contao#531] opened 2019-06-24 06:56 UTC
**4.4.40**

**A user with the right to create a form is not able to edit the form after creation.**  

Also metioned [here](https://community.contao.org/de/showthread.php?28174-Benutzerrechte-Anlegen-neuer-Formular-%E2%80%93-k%C3%B6nnen-danach-nicht-ge%C3%A4ndert-werden)

**Comment by leofeyer** [comment] 2019-07-11 15:03
How do I reproduce this in the [online demo](https://demo.contao.org/contao)?

**Comment by gtwone** [comment] 2019-07-22 06:47
It is not reproduceable in online demo (4.7.7) but in contao 4.4.40

**Comment by leofeyer** [comment] 2019-07-23 10:17
This has been fixed in ac6376bb5b882162d6a8559e348187386aac3856 (Contao 4.6) after discussing it in contao/core-bundle#1450. Since we had to add new DCA callbacks, the changes cannot be backported to a bugfix version (new features can only be added in minor or major versions).

**Closed as completed by leofeyer** 2019-07-23 10:17 UTC

**Comment by gtwone** [comment] 2019-07-23 10:45
Thanks a lot!
Cheers
