### ISSUE TITLE
generateRecordLabel returns an array instead of string when deleting a DC_Table

### ISSUE THREAD

**Issue by zoglo** [contao/contao#4125] opened 2022-02-14 07:55 UTC
### Affected version(s)

4.13 RC3

### Description

Hello,

we've got following issue with one of our plugins when deleting an entry in a DC_Table:

```
Contao\CoreBundle\EventListener\DataContainer\RecordPreviewListener::compilePreview(): Return value must be of type string, array returned

in **\contao413\vendor\contao\core-bundle\src\EventListener\DataContainer\RecordPreviewListener.php (line 89)

```

Contao Version: 4.13 RC3
PHP Version: 8.0.3

Stacktrace:
```
TypeError:
Contao\CoreBundle\EventListener\DataContainer\RecordPreviewListener::compilePreview(): Return value must be of type string, array returned

  at **\contao413\vendor\contao\core-bundle\src\EventListener\DataContainer\RecordPreviewListener.php:89
  at Contao\CoreBundle\EventListener\DataContainer\RecordPreviewListener->compilePreview(object(DC_Table), array('id' => '26', 'tstamp' => '1644791731', 'title' => 'asd', 'desc' => null, 'identifier' => 'asddd', 'groupAlias' => '', 'sorting' => '128'))
     (**\contao413\vendor\contao\core-bundle\src\EventListener\DataContainer\RecordPreviewListener.php:63)
  at Contao\CoreBundle\EventListener\DataContainer\RecordPreviewListener->storePrecompiledRecordPreview(object(DC_Table), '31')
     (**\contao413\vendor\contao\core-bundle\src\Resources\contao\drivers\DC_Table.php:1506)
  at Contao\DC_Table->delete()
     (**\contao413\vendor\contao\core-bundle\src\Resources\contao\classes\Backend.php:655)
  at Contao\Backend->getBackendModule('style_manager', null)
     (**\contao413\vendor\contao\core-bundle\src\Resources\contao\controllers\BackendMain.php:170)
  at Contao\BackendMain->run()
     (**\contao413\vendor\contao\core-bundle\src\Controller\BackendController.php:49)
  at Contao\CoreBundle\Controller\BackendController->mainAction()
     (**\contao413\vendor\symfony\http-kernel\HttpKernel.php:152)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (**\contao413\vendor\symfony\http-kernel\HttpKernel.php:74)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (**\contao413\vendor\symfony\http-kernel\Kernel.php:202)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (**\contao413\public\index.php:44)   

in **\contao413\vendor\contao\core-bundle\src\EventListener\DataContainer\RecordPreviewListener.php (line 89)  
```

The affected DCA:

[https://github.com/oveleon/contao-component-style-manager/blob/2aaec7be9aaafce5b9e[…]fe83505c79213f2c4/src/Resources/contao/dca/tl_style_manager.php](https://github.com/oveleon/contao-component-style-manager/blob/2aaec7be9aaafce5b9e13cdfe83505c79213f2c4/src/Resources/contao/dca/tl_style_manager.php#L8)

(Parent archive: [https://github.com/oveleon/contao-component-style-manager/blob/2aaec7be9aaafce5b9e[…]79213f2c4/src/Resources/contao/dca/tl_style_manager_archive.php](https://github.com/oveleon/contao-component-style-manager/blob/2aaec7be9aaafce5b9e13cdfe83505c79213f2c4/src/Resources/contao/dca/tl_style_manager_archive.php#L12))

**Comment by aschempp** [comment] 2022-02-14 12:19
Pretty sure the return value definition is incorrect. If the table is displayed in a column view, an array as return value is valid/expected.

**Comment by bezin** [comment] 2022-02-14 13:00
> Pretty sure the return value definition is incorrect. If the table is displayed in a column view, an array as return value is valid/expected.

Yes, the return value is all right, it simply was not handled correctly. It is now, see #4126

**Comment by fritzmg** [comment] 2022-02-14 13:21
No, the issue is in the extension (see https://github.com/oveleon/contao-component-style-manager/pull/60). However, `DC_Table::listView` is lenient to this, that's why it worked in the past (see https://github.com/contao/contao/pull/4126#pullrequestreview-881286439). In any case the `ondelete` listener should not check the DCA configuration anyway. It should just return whatever was provided by `DataContainer::generateRecordLabel`.

**Comment by aschempp** [comment] 2022-02-15 07:31
Closed in favour of https://github.com/contao/contao/pull/4126 I would say then 😊

**Closed as completed by aschempp** 2022-02-15 07:31 UTC
Labels: bug, unconfirmed
