### ISSUE TITLE
Robots tags to 'noindex, nofollow' displays sites in sitemap.xml

### ISSUE THREAD

**Issue by berecont** [contao/contao#3397] opened 2021-08-30 10:37 UTC
**Affected version(s)**

 Contao 4.12.x

**Description**

site structur: setting Robots tags to `'noindex, nofollow'` the sites will be displayed in sitemap.xml

**Comment by fritzmg** [comment] 2021-08-30 10:38
Duplicate of #3395

**Closed as completed by fritzmg** 2021-08-30 10:38 UTC
