### ISSUE TITLE
Clickable area too small/changed at the accordion toggle inside the elements

### ISSUE THREAD

**Issue by mlaubacher** [contao/contao#7538] opened 2024-09-19 07:44 UTC
### Affected version(s)

5.3.13

### Description

The padding is no more clickable only the height of the word inside the elements for the accordion "Sichtbarkeit", "Experteneinstellungen" etc. This seems to be new. Checked with 5.3.11 and there it seems ok. 
See screenshot.
![ContaoAccordionToggle](https://github.com/user-attachments/assets/c6d6e78c-0344-4e59-a7b6-d6986b30407f)

**Comment by fritzmg** [comment] 2024-09-19 08:11
Duplicate of https://github.com/contao/contao/issues/7526

**Closed as completed by fritzmg** 2024-09-19 08:11 UTC
Labels: bug, unconfirmed
