### ISSUE TITLE
Sitemap generation runs twice

### ISSUE THREAD

**Issue by rorych** [contao/contao#2142] opened 2020-08-10 14:58 UTC
**Affected version(s)**
Contao 4.9.4 (untested on <4.9)

**Description**
If you run the "generate XML Files" command via the backend, contao does two loops of all root-pages - or at least it seems like it. As visible in this screenshot and also tested with the getSearchablePages-Hook, the sitemap is being generated twice.

Here i ran the "generate XML Files" once and the root-Page-Structure has 3 pages (DE, EN, FR).
But still this shows, 6 loops where triggered.
<a href="https://ibb.co/Y3McWFK"><img src="https://i.ibb.co/c1H6vSp/Sitemapsx2.png" width="400" alt="Sitemapsx2" border="0"></a>

**Comment by fritzmg** [comment] 2020-08-10 15:03
I can confirm the issue in 4.9.x-dev

**Comment by leofeyer** [comment] 2020-08-13 10:18
Here is what happens:

* `Automator::generateXmlFiles()` calls `Automator::generateSitemap()`
* `Automator::generateXmlFiles()` then dispatches the `generateXmlFiles` hook
* Both `Calendar::generateFeeds()` and `News::generateFeeds()` are subscribed to the hook
* Both methods run `Automator::purgeXmlFiles()` and `Automator::generateSitemap()`

So when rebuilding the XML files in the maintenance module, we are in fact purging the XML files three times and recreating them three times. 🤦🏻‍♂️

**Comment by leofeyer** [comment] 2020-08-13 13:47
@contao/developers Any ideas how to fix this?

**Comment by Toflar** [comment] 2020-08-14 12:25
Nope.

**Comment by leofeyer** [comment] 2020-08-27 14:24
As discussed in Mumble on August 27th, this will be fixed when we add a SitemapController in Contao 4.11, because then the controller will generate the sitemaps.

**Closed as completed** 2020-10-16 13:54 UTC
Labels: bug
