### ISSUE TITLE
'Undefined array key' in 'public_html/vendor/contao/core-bundle/src/Resources/contao/library/Contao/Model.php' on line 155

### ISSUE THREAD

**Issue by bright-cloud-studio** [contao/contao#5818] opened 2023-02-23 18:57 UTC
### Affected version(s)

4.13.14

### Description

We have been having issues on Contao 4.13 sites using PHP 8.1 where the logs are getting as big as 10-15gb. I've been fixing the ones I can, ones caused by templates, but these system level ones I have to leave. Here is one that keeps happening a lot.

File: 'public_html/vendor/contao/core-bundle/src/Resources/contao/library/Contao/Model.php'
Line: 155

**Comment by fritzmg** [comment] 2023-02-23 19:17
Please post a full stack trace.

**Comment by aschempp** [comment] 2023-02-24 07:47
I think this should be fixed by https://github.com/contao/contao/pull/5820

**Closed as completed by aschempp** 2023-02-24 07:47 UTC
Labels: bug, unconfirmed

**Comment by fritzmg** [comment] 2023-02-24 09:30
I think we should wait for the stack trace or reproduction steps first.

**Comment by bright-cloud-studio** [comment] 2023-02-24 15:26
You may have to help me out here. I am unfamiliar with how to do a Stack Trace exactly but I think I got it. I put the site in debug mode and loaded that same page, it has a Stack Trace section on there, although its not showing that exact like it does show the same "Warning: Undefined array key" issue. Here is what I got back. If this isn't correct could you tell me how to get you what your looking for.

```
ErrorException:
Warning: Undefined array key "pry_bars_options"

  at vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Module/AbstractProductFilter.php:265
  at Isotope\Module\AbstractProductFilter->getProductTypeIdsByAttribute('pry_bars_options')
     (vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Module/AbstractProductFilter.php:83)
  at Isotope\Module\AbstractProductFilter->getUsedValuesForAttribute('pry_bars_options', array(10), 'show_all', '')
     (vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Module/CumulativeFilter.php:326)
  at Isotope\Module\CumulativeFilter->getOptionsForAttribute('pry_bars_options', 'pry_bars_options')
     (vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Module/CumulativeFilter.php:171)
  at Isotope\Module\CumulativeFilter->generateAttribute('pry_bars_options', 'and', 'none', false)
     (vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Module/CumulativeFilter.php:146)
  at Isotope\Module\CumulativeFilter->generateFilter()
     (vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Module/CumulativeFilter.php:131)
  at Isotope\Module\CumulativeFilter->compile()
     (vendor/contao/core-bundle/src/Resources/contao/modules/Module.php:214)
  at Contao\Module->generate()
     (vendor/codefog/contao-haste/library/Haste/Frontend/AbstractFrontendModule.php:52)
  at Haste\Frontend\AbstractFrontendModule->generate()
     (vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Module/Module.php:115)
  at Isotope\Module\Module->generate()
     (vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Module/CumulativeFilter.php:116)
  at Isotope\Module\CumulativeFilter->generate()
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Controller.php:435)
  at Contao\Controller::getFrontendModule(object(ModuleModel), 'left')
     (vendor/contao/core-bundle/src/Resources/contao/pages/PageRegular.php:190)
  at Contao\PageRegular->prepare(object(PageModel))
     (vendor/contao/core-bundle/src/Resources/contao/pages/PageRegular.php:60)
  at Contao\PageRegular->getResponse(object(PageModel), true)
     (vendor/contao/core-bundle/src/Resources/contao/controllers/FrontendIndex.php:320)
  at Contao\FrontendIndex->renderPage(object(PageModel))
     (vendor/symfony/http-kernel/HttpKernel.php:163)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:75)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:202)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (web/index.php:44)  
```

**Comment by bright-cloud-studio** [comment] 2023-02-24 15:28
Here we go, I was looking at a specific product and not the overall products page. Here is the stack trace.

```
ErrorException:
Warning: Undefined array key "set"

  at vendor/contao/core-bundle/src/Resources/contao/library/Contao/Model.php:155
  at Contao\Model->__construct(object(Result))
     (vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Model/TypeAgent.php:48)
  at Isotope\Model\TypeAgent->__construct(object(Result))
     (vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Model/TypeAgent.php:314)
  at Isotope\Model\TypeAgent::createModelFromDbResult(object(Result))
     (vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Model/TypeAgent.php:377)
  at Isotope\Model\TypeAgent::buildModelType(object(Result))
     (vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Model/TypeAgent.php:342)
  at Isotope\Model\TypeAgent::createCollectionFromDbResult(object(Result), 'tl_iso_product')
     (vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Model/TypeAgent.php:266)
  at Isotope\Model\TypeAgent::find(array('column' => array('tl_iso_product.published=\'1\' AND (tl_iso_product.start=\'\' OR tl_iso_product.start<\'1677252420\') AND (tl_iso_product.stop=\'\' OR tl_iso_product.stop>\'1677252480\')', 'tl_iso_product.pid=0', 'c.page_id IN (2,3,4,5,6,7,30,31,33,34,36,56,80,349,10,11,12,13,15,16,17,18,19,20,21,22,58,77,84,348,57,82,83,23,59,29,63,344,350,355,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,102,103,104,105,106,107,108,347,149,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,129,130,131,132,133,134,135,136,137,138,139,140,141,142,289,296,297,298,299,300,301,302,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,304,305,306,307,308,309,310,311,312,313,354,122,123,124,125,126,127,128,143,144,145,146,147,148,24,25,26,27,61,87,88,89,90,91,92,93,94,95,96,97,98,99,100,351,1)'), 'value' => array(), 'return' => 'Collection', 'order' => null, 'filters' => array(), 'sorting' => array(), 'group' => 'tl_iso_product.id', 'table' => 'tl_iso_product', 'limit' => 0, 'offset' => 0))
     (vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Model/Product.php:501)
  at Isotope\Model\Product::find(array('column' => array('tl_iso_product.published=\'1\' AND (tl_iso_product.start=\'\' OR tl_iso_product.start<\'1677252420\') AND (tl_iso_product.stop=\'\' OR tl_iso_product.stop>\'1677252480\')', 'tl_iso_product.pid=0', 'c.page_id IN (2,3,4,5,6,7,30,31,33,34,36,56,80,349,10,11,12,13,15,16,17,18,19,20,21,22,58,77,84,348,57,82,83,23,59,29,63,344,350,355,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,102,103,104,105,106,107,108,347,149,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,129,130,131,132,133,134,135,136,137,138,139,140,141,142,289,296,297,298,299,300,301,302,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,304,305,306,307,308,309,310,311,312,313,354,122,123,124,125,126,127,128,143,144,145,146,147,148,24,25,26,27,61,87,88,89,90,91,92,93,94,95,96,97,98,99,100,351,1)'), 'value' => array(), 'return' => 'Collection', 'order' => null, 'filters' => array(), 'sorting' => array(), 'group' => 'tl_iso_product.id'))
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Model.php:957)
  at Contao\Model::findBy(array('tl_iso_product.published=\'1\' AND (tl_iso_product.start=\'\' OR tl_iso_product.start<\'1677252420\') AND (tl_iso_product.stop=\'\' OR tl_iso_product.stop>\'1677252480\')', 'tl_iso_product.pid=0', 'c.page_id IN (2,3,4,5,6,7,30,31,33,34,36,56,80,349,10,11,12,13,15,16,17,18,19,20,21,22,58,77,84,348,57,82,83,23,59,29,63,344,350,355,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,102,103,104,105,106,107,108,347,149,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,129,130,131,132,133,134,135,136,137,138,139,140,141,142,289,296,297,298,299,300,301,302,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,304,305,306,307,308,309,310,311,312,313,354,122,123,124,125,126,127,128,143,144,145,146,147,148,24,25,26,27,61,87,88,89,90,91,92,93,94,95,96,97,98,99,100,351,1)'), array(), array('column' => array('tl_iso_product.published=\'1\' AND (tl_iso_product.start=\'\' OR tl_iso_product.start<\'1677252420\') AND (tl_iso_product.stop=\'\' OR tl_iso_product.stop>\'1677252480\')', 'tl_iso_product.pid=0', 'c.page_id IN (2,3,4,5,6,7,30,31,33,34,36,56,80,349,10,11,12,13,15,16,17,18,19,20,21,22,58,77,84,348,57,82,83,23,59,29,63,344,350,355,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,102,103,104,105,106,107,108,347,149,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,129,130,131,132,133,134,135,136,137,138,139,140,141,142,289,296,297,298,299,300,301,302,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,304,305,306,307,308,309,310,311,312,313,354,122,123,124,125,126,127,128,143,144,145,146,147,148,24,25,26,27,61,87,88,89,90,91,92,93,94,95,96,97,98,99,100,351,1)'), 'value' => array(), 'return' => 'Collection', 'order' => null, 'filters' => array(), 'sorting' => array()))
     (vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Model/Product.php:159)
  at Isotope\Model\Product::findPublishedBy(array('tl_iso_product.published=\'1\' AND (tl_iso_product.start=\'\' OR tl_iso_product.start<\'1677252420\') AND (tl_iso_product.stop=\'\' OR tl_iso_product.stop>\'1677252480\')', 'tl_iso_product.pid=0', 'c.page_id IN (2,3,4,5,6,7,30,31,33,34,36,56,80,349,10,11,12,13,15,16,17,18,19,20,21,22,58,77,84,348,57,82,83,23,59,29,63,344,350,355,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,102,103,104,105,106,107,108,347,149,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,129,130,131,132,133,134,135,136,137,138,139,140,141,142,289,296,297,298,299,300,301,302,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,304,305,306,307,308,309,310,311,312,313,354,122,123,124,125,126,127,128,143,144,145,146,147,148,24,25,26,27,61,87,88,89,90,91,92,93,94,95,96,97,98,99,100,351,1)'), array(), array('order' => null, 'filters' => array(), 'sorting' => array()))
     (vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Model/Product.php:338)
  at Isotope\Model\Product::findAvailableBy(array('tl_iso_product.pid=0', 'c.page_id IN (2,3,4,5,6,7,30,31,33,34,36,56,80,349,10,11,12,13,15,16,17,18,19,20,21,22,58,77,84,348,57,82,83,23,59,29,63,344,350,355,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,102,103,104,105,106,107,108,347,149,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,129,130,131,132,133,134,135,136,137,138,139,140,141,142,289,296,297,298,299,300,301,302,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,304,305,306,307,308,309,310,311,312,313,354,122,123,124,125,126,127,128,143,144,145,146,147,148,24,25,26,27,61,87,88,89,90,91,92,93,94,95,96,97,98,99,100,351,1)'), array(), array('order' => null, 'filters' => array(), 'sorting' => array()))
     (vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Module/ProductList.php:354)
  at Isotope\Module\ProductList->findProducts()
     (vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Module/ProductList.php:209)
  at Isotope\Module\ProductList->compile()
     (vendor/contao/core-bundle/src/Resources/contao/modules/Module.php:214)
  at Contao\Module->generate()
     (vendor/codefog/contao-haste/library/Haste/Frontend/AbstractFrontendModule.php:52)
  at Haste\Frontend\AbstractFrontendModule->generate()
     (vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Module/Module.php:115)
  at Isotope\Module\Module->generate()
     (vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Module/ProductList.php:104)
  at Isotope\Module\ProductList->generate()
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Controller.php:435)
  at Contao\Controller::getFrontendModule(object(ModuleModel), 'main')
     (vendor/contao/core-bundle/src/Resources/contao/pages/PageRegular.php:190)
  at Contao\PageRegular->prepare(object(PageModel))
     (vendor/contao/core-bundle/src/Resources/contao/pages/PageRegular.php:60)
  at Contao\PageRegular->getResponse(object(PageModel), true)
     (vendor/contao/core-bundle/src/Resources/contao/controllers/FrontendIndex.php:320)
  at Contao\FrontendIndex->renderPage(object(PageModel))
     (vendor/symfony/http-kernel/HttpKernel.php:163)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:75)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:202)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (web/index.php:44)                
```

**Comment by fritzmg** [comment] 2023-02-24 16:56
That looks like an issue with Isotope rather than Contao. Please open an issue there. But before that make sure you are using the newest version of Isotope.

**Comment by bright-cloud-studio** [comment] 2023-02-24 17:27
I've updated to their latest version, it fixed a lot of these issues. I'll report it over there. Thanks!
