### ISSUE TITLE
AbstractGuestsMigration only migrates one entry per run

### ISSUE THREAD

**Issue by ReneLuecking** [contao/contao#6964] opened 2024-03-04 22:48 UTC
### Affected version(s)

5.2.10

### Description

Maybe I'm missing something, but the AbstractGuestsMigration is currently limited to 1 entry per run:

https://github.com/contao/contao/blob/1b80fb088d1e7315bb81e7e19c7f5bc39048cfd5/core-bundle/src/Migration/Version500/AbstractGuestsMigration.php#L77-L82

This causes it to appear as open in the `contao:migrate` command over and over.

**Comment by fritzmg** [comment] 2024-03-04 22:55
Duplicate of https://github.com/contao/contao/pull/6951

This will be fixed in Contao **5.3.1**.

**Closed as not planned** 2024-03-04 22:55 UTC
Labels: bug, unconfirmed
