### ISSUE TITLE
Article bug

### ISSUE THREAD

**Issue by rawelja** [contao/contao#38] opened 2018-08-30 13:57 UTC
**Affected version(s)**
4.4.19
**Description**  
When someone opens two instances of "new article" and save one and after that try to save another, error popup {Cannot load record "tl_article.id=154".}

**Comment by fritzmg** [comment] 2018-08-30 14:00
First of all you should not report bugs which did not test in the most recent version.

Second of all this is a known limitation.

**Comment by rawelja** [comment] 2018-08-30 14:01
Can this limitation be fixed?

**Comment by leofeyer** [comment] 2018-08-31 15:06
Does the error occur in Contao 4.4.23 as well?

**Comment by xchs** [comment] 2018-09-05 22:04
I cannot reproduce it in Contao 4.4.24 (at least not with the problem description given above).

**Comment by rawelja** [comment] 2018-09-06 08:26
Hi @leofeyer,
I installed contao 4.4.24 via composer and successfully reproduced a problem.
You need to open two instances of "New Article" then to pick the position of both articles,
fill first and press save and close after that fill second and press save and close.
After pressing save and close, there will be a redirect to page with this content : https://ibb.co/f2uRAK
It's important to save pages with save and close

**Comment by xchs** [comment] 2018-09-06 08:42
I still cannot reproduce. Can you make a screencast?

That's how I tested it:
- Opened _New article_ in two browser tabs
- Switched to the first tab and pasted the first article into a page
- Entered an article title, published the article and saved the record with _Save and close_
- Then I did the same for the second tab.

What did I miss?

**Comment by fritzmg** [comment] 2018-09-06 08:53
@xchs you need to paste both articles first. The point is to have new "new article" views. One of them will be deleted from the database, once the user goes into the article tree view again - e.g. after saving and closing the first article. The same issue occurs anywhere in Contao (modules, pages, content elements within the same article etc.). It's a known limitation.

**Comment by xchs** [comment] 2018-09-06 08:58
> you need to paste both articles first.

Okay, that was exactly the right clue. Now I can reproduce the error.

However, I wonder whether such a case really can ever happen in a real situation or whether it is only constructed. 😄

**Comment by rawelja** [comment] 2018-09-06 09:00
@xchs  Happens when content editors work on same time.  :D

**Comment by fritzmg** [comment] 2018-09-06 09:02
> However, I wonder whether such a case really can ever happen in a real situation or whether it is only constructed.

I experience that often ;).

**Comment by fritzmg** [comment] 2018-09-06 09:03
> @xchs Happens when content editors work on same time. :D

That should not happen. Are your content editors not using different accounts?

**Comment by leofeyer** [comment] 2018-09-11 10:47
> The same issue occurs anywhere in Contao (modules, pages, content elements within the same article etc.). It's a known limitation.

It is indeed.

**Closed as completed by leofeyer** 2018-09-11 10:47 UTC
