### ISSUE TITLE
Unable to expand accordion on custom css class

### ISSUE THREAD

**Issue by marcfunkDE** [contao/contao#5734] opened 2023-01-27 09:58 UTC
### Affected version(s)

4.9.38

### Description

Process:
Add contentelement "accordion start" and set an individual class for toggler (screenshot).
After that, the accordion is open and cannot close. When i delete the individual css class for the toggler, the accordion can close and open.

![accordion-bug](https://user-images.githubusercontent.com/63631126/215058672-8d2ee10e-2d95-4f83-b518-a36f5d32895d.jpg)

Note:
JQuery + template js_accordion is attached in site layout. There is no individual template for accordion start, element or stop.

**Comment by marcfunkDE** [comment] 2023-01-27 10:18
Sample solution:
When i add an individuall css class for the toggler, contao still adds "toggler" and my individual toggler class.

After entering an individual CSS class, the normal toggler class should also be output in addition to the individual one.

**Comment by fritzmg** [comment] 2023-01-27 10:28
The description of this field says:

> Leave blank to use the default classes or enter a custom toggler and accordion class.

So I don't think this should be changed.

**Comment by marcfunkDE** [comment] 2023-01-27 10:32
> The description of this field says:
> 
> > Leave blank to use the default classes or enter a custom toggler and accordion class.
> 
> So I don't think this should be changed.

But when i use an custom toggler, the js does not work while he did not find the .toggler class.

**Comment by mlwebworker** [comment] 2023-01-27 10:32
Ist meiner Meinung nach auch irgendeine Anpassung und nicht Original 4.9.

**Comment by mlwebworker** [comment] 2023-01-27 10:33
Einen angepassten Toggler würdest Du m.E. für ein eigenes JS verwenden.

**Comment by fritzmg** [comment] 2023-01-27 10:40
> But when i use an custom toggler, the js does not work while he did not find the .toggler class.

The expectation is that you are using a custom accordion script, if you changed the toggler class.

> Ist meiner Meinung nach auch irgendeine Anpassung und nicht Original 4.9.

What do you mean by that?

**Comment by mlwebworker** [comment] 2023-01-27 11:07
Entschuldigung, habe falsch geschaut. Ich war bei den Klassen in den Experteneinstellungen und nicht in der Akkordeoneinstellung.

**Comment by marcfunkDE** [comment] 2023-01-27 11:17
However, there should possibly be a note that if the standard class is changed, the js_accordion no longer works because it needs the .toggler class in the element.

In my case, i don't know when i change the toggler class, that the js don't work.
My example suggestion would be a compromise: If you enter an individual toggler class, "class="toggler individualclass" appears in the source code.

**Comment by fritzmg** [comment] 2023-01-27 11:21
@marcfunkDE it's an expert setting - so it only should be changed if you are know what you are doing 🤷 

> My example suggestion would be a compromise: If you enter an individual toggler class, "class="toggler individualclass" appears in the source code.

That would be a behavior change.

**Comment by Aybee** [comment] 2023-01-28 13:15
> However, there should possibly be a note that if the standard class is changed, the js_accordion no longer works because it needs the .toggler class in the element.
> 
> In my case, i don't know when i change the toggler class, that the js don't work.

I think in general, the help texts often gladly could be a little more meaningful. 👍

**Comment by aschempp** [comment] 2023-02-02 13:54
If you use a custom CSS class, you must also have a custom accordion script. This is mostly meaningful if you want to have multiple, separately working accordions. 

Regarding the description, I think a pull request to update the (english) label would be welcomed 😊

Closing this ticket since it's not a bug.

**Closed as not planned** 2023-02-02 13:54 UTC
Labels: bug, unconfirmed

**Comment by Aybee** [comment] 2023-02-06 11:32
Aren't the languages managed on Transifex?
My proposals are:
+"Requires appropriately customized JavaScript or CSS."
or/and
+"Then it no longer works with the core j_accordion template."

**Comment by fritzmg** [comment] 2023-02-06 11:55
> Aren't the languages managed on Transifex?

Not the English translations. For these you can create a PR.

**Comment by Aybee** [comment] 2023-02-06 19:58
Ok, I do it, when someone tells me the new text.
https://github.com/contao/contao/blob/5.x/core-bundle/contao/languages/en/tl_content.xlf#L201

**Comment by fritzmg** [comment] 2023-02-06 20:55
No one can tell you the new translation. If you have a suitable suggestion then just create the PR accordingly.

**Comment by Aybee** [comment] 2023-02-07 09:45
Because nobody liked my suggestion, I'll wait and see.
