### ISSUE TITLE
cssID not available in Module

### ISSUE THREAD

**Issue by wuapaadev** [contao/contao#2840] opened 2021-03-04 14:17 UTC
**Affected version(s)**

Contao 4.9

**Description**

Die eingegebenen Werte bei CSS-id bzw. Css-Klasse für ein FE-Modul werden nicht im template ausgespielt.

Siehe: https://community.contao.org/de/showthread.php?80427-CSS-des-Inhaltselement-mit-eingeb-Modul-sind-im-Template-nicht-verf%C3%BCgbar

Referenz auf dieses Problem wohl auch hier  https://github.com/contao/contao/issues/2533#issuecomment-782172069

**Comment by fritzmg** [comment] 2021-03-04 14:45
I think we can mark this as a duplicate of #2823. See [here](https://github.com/contao/contao/issues/2823#issuecomment-790574395). @dmolineus can you confirm?

**Comment by fritzmg** [comment] 2021-03-04 15:47
@wuapaadev just to confirm: you were trying to integrate your front end module, which is implemented a fragment controller, via the `module` content element `Contao\ContentAlias`, correct?

**Comment by wuapaadev** [comment] 2021-03-04 16:06
@fritzmg no idea what you're talking about :-D. 

Just learning to get into contao4-module programming

maybe this helps - I submitted my programming-trials here: https://github.com/wuapaadev/contao-reviews-bundle

edit: Its basically some mixed code form the skeleton-bundle with contao-doc and various community-infos

**Comment by aschempp** [comment] 2021-03-08 08:21
should be fixed by https://github.com/contao/contao/pull/2851

**Closed as completed** 2021-03-15 15:34 UTC
Labels: bug
