### ISSUE TITLE
default values in DB are not applied to existing elements

### ISSUE THREAD

**Issue by frontendschlampe** [contao/contao#1064] opened 2019-12-06 01:11 UTC
**Affected version(s)**
Contao 4.8 but I think it's also for Contao 4.4

**Description**  
After debugging an extension we realized that existing elements have no default value. For example in `tl_content` an entry should have a default value for `floating` which is `above`. New elements will get the default value but existing elements don't have it. This makes the database inconsistent and could cause problems.

All columns with a default value in all tables are affected.

**How to reproduce**  
Take an updated Contao installation and compare the content of a new and an existing entry in `tl_content` for the column `floating`.

/cc @discordier

**Comment by aschempp** [comment] 2019-12-09 14:51
We have recently changed the defaults from being in the SQL instead of the DCA. This means they should be used for new elements, as well as when adding new columns to the database. We cannot update existing records, but I'm pretty sure that's not what you meant?

**Comment by frontendschlampe** [comment] 2019-12-09 15:09
It's exactly what I meant, but why you can't update existing records? The database is inconsistent now, because some (new) entries have default values and some (old) entries doesn't have one. That's not good.

**Comment by aschempp** [comment] 2019-12-09 15:24
I don't understand how this can be true, or how that's a problem. If a new column is added, all rows will have the new default value. So if an existing content element has a new setting, the default value will be used. When adding a new content element, the new value will be used as well. It's only old content elements that do not get the value, but they must not rely on it because they shouldn't know about it? Maybe I don't understand your actual problem?

**Comment by fritzmg** [comment] 2019-12-09 17:24
I think what @frontendschlampe means are edge cases, where no default value was stored in the database by either the DataContainer nor MySQL. For example when records were created by a third party, rather than the DataContainer itself.

**Comment by Toflar** [comment] 2019-12-09 19:15
That‘s how default values work?🤔

**Comment by ausi** [comment] 2019-12-10 18:50
I was not able to reproduce that. If I delete the `floating` column and run a database update all rows get the new default value.

**Comment by frontendschlampe** [comment] 2019-12-10 20:27
I don't want to delete any column and make it new. It's just not consistent, that a table of a database has rows with correct default value (new entries/rows with default value for col `floating` --> `above`) and rows with an incorrect default value (old entries/rows with an empty string for col `floating`).
The database is inconsistent and cause problems.

I find the following case:

1. open an existing "text element" which never had any image
2. add an image and choose an image
3. save the element

Result: the text element will be saved without any floating and that's not good.

I think there will be some more these quirks but maybe that could be errors, too. Maybe now a col has a default value because the column must have a value, but it's empty.

**Comment by fritzmg** [comment] 2019-12-10 22:18
@frontendschlampe I cannot reproduce that. Even if I create a text element without an image in Contao 4.4.45 (where we do not have the SQL defaults yet), the `floating` column of the `tl_content` table will be filled with `above`.

**Comment by frontendschlampe** [comment] 2019-12-10 22:23
Contao 4.8.x (updated from Contao 3.5.x --> 4.5.x --> 4.6.x --> 4.7.x --> 4.8.x)

Take an **existing** text element which has no image and no default value for `floating` - add image - choose image - save element --> no default value for `floating` is set

The problem aren't **new** elements - the problem are the **existing** elements which will be changed!!!

**Comment by fritzmg** [comment] 2019-12-10 22:23
Existing elements had to be created somewhere. How did you create those elements?

**Comment by frontendschlampe** [comment] 2019-12-10 22:25
> Existing elements had to be created somewhere. How did you create those elements?

just with an older Contao version in the backend

**Comment by fritzmg** [comment] 2019-12-10 22:26
> just with an older Contao version in the backend

Yes, but with which one? You need to provide more details in order to be reproducible. If by older Contao version you mean Contao `3.5.40` for instance: I cannot reproduce the problem there either. Text elements without an image will also have `'above'` for `floating`.

**Comment by frontendschlampe** [comment] 2019-12-10 22:31
> Yes, but with which one?

I don't know.

**Comment by fritzmg** [comment] 2019-12-10 22:35
`tl_content.floating` being empty is an invalid database state, at least from the viewpoint of Contao 3.5.40 and newer, regardless of this issue.

**Comment by frontendschlampe** [comment] 2019-12-10 22:37
`¯\_(ツ)_/¯`

**Comment by aschempp** [comment] 2020-02-24 09:33
I don't think there's much we can fix here. The original issue has been fixed in one of the later Contao versions (4.7 or later I'd say). So there's no bug to be fixed in latest Contao. If you update from an older version, the data might be _outdated_, but I don't think we can fix that for you…

**Comment by discordier** [comment] 2020-02-24 13:12
> The original issue has been fixed in one of the later Contao versions (4.7 or later I'd say).

Is there any changelog entry we can refer to? I failed to find one.

**Comment by ausi** [comment] 2020-02-24 20:27
Changelog: https://github.com/contao/contao/blob/4.8/CHANGELOG.md#L156
Commit: https://github.com/contao/contao/commit/a6fcb2ab05bfca8dbeb6e83ba90b1583f786f87e

**Closed as completed** 2020-07-02 11:23 UTC
Labels: up for discussion
