### ISSUE TITLE
Backend filter does not work when using special chars - brackets

### ISSUE THREAD

**Issue by Kahmoon** [contao/contao#2498] opened 2020-11-17 10:43 UTC
**Affected version(s)**

Contao 4.10.4

**Description**
Filter result is empty when using special chars (brackets) in backendfilter "title"

My event titles are named as follows: **MyDate (teacher's abbreviation/exam quarter)** so **terminxyz (MM/Q4)**

If I only search for "**terminxyz**" the filter is correct. As soon as I take the bracket "**terminxyz (MM**" (abbreviation for Max Muster) the result is zero.

Searching "**MM/Q4**" its working. Brackets seem to be the problem here.

greetings
Frank

**Comment by aschempp** [comment] 2020-11-24 07:51
The back end filter support regex to filter stuff. Therefore, brackets have a special meaning, you might need to escape them (`\[`)

**Comment by Kahmoon** [comment] 2020-11-24 08:26
I tried  `\(MM` which is not working

**Comment by leofeyer** [comment] 2021-01-15 14:55
I cannot reproduce the issue on contao.org: https://contao.org/de/suche.html?keywords=Show+%28Folge+1%29

<img width="1217" alt="" src="https://user-images.githubusercontent.com/1192057/104741919-1f582980-574a-11eb-8c8f-65f088538573.png">

**Comment by fritzmg** [comment] 2021-01-15 15:01
@leofeyer it's about the search in the back end. Reproduction on demo.contao.org:

1. Log into the back end of demo.contao.org.
2. Create a new news article with the title `Lorem (Ipsum)`
3. Now switch the search filter to _Title_ and search for `Lorem (Ipsum)` » nothing will be found.
4. Search for `Ipsum)` » nothing will be found.
5. Search for `Lorem (Ipsum` » no search will be exucted and the search field will be empty (weirdly).

**Comment by leofeyer** [comment] 2021-01-19 10:17
That is basically what @aschempp already explained above. The back end search supports regular expressions, therefore you have to escape the parentheses. I have tried searching for `Lorem \(ipsum` or just `\(ipsum` and it worked.

**Comment by Kahmoon** [comment] 2021-01-19 10:48
This is not working for me "`\(JP`" has no search results even there are entrys with "(JP". 

![Bildschirmfoto_2021-01-19 11 47 43](https://user-images.githubusercontent.com/6390770/105024311-3c437400-5a4c-11eb-9e4e-90108cbe9815.jpg)
![Bildschirmfoto_2021-01-19 11 48 03](https://user-images.githubusercontent.com/6390770/105024316-3d74a100-5a4c-11eb-917a-81d573e0353d.jpg)

But even with backslashes this wouldn´t be any userfriendly at all. I cannot explain our moderators/teachers what regex is and how to use this...

**Comment by fritzmg** [comment] 2021-01-19 11:25
> That is basically what @aschempp already explained above. The back end search supports regular expressions, therefore you have to escape the parentheses. I have tried searching for `Lorem \(ipsum` or just `\(ipsum` and it worked.

I cannot confirm this:

<img src="https://user-images.githubusercontent.com/4970961/105028187-9f330c00-5a48-11eb-828c-30a132f22b3c.png" width="738">

<img src="https://user-images.githubusercontent.com/4970961/105028190-a0643900-5a48-11eb-9c92-914067c01fae.png" width="744">

And even if that would be the case: this feature is likely also used by editors who do not know anything about regular expressions and how to handle them. Imho this should not be enabled by default at the very least.

Contao 4.9 also has issues with this.

**Comment by aschempp** [comment] 2021-01-19 11:27
It is most likely also related to these "entities" being encoded in the database, not sure there's much we can do about that 🤔

**Comment by leofeyer** [comment] 2021-02-11 15:52
As discussed in Mumble on February 11th, we want to keep the regex search but in case the given regex is invalid, we want to `preg_quote()` the input and try again.

**Comment by ausi** [comment] 2021-02-11 23:02
Pull request: #2735 

Is there a specific reason why this issue is assigned to the 4.10 milestone? I now fixed it in Contao 4.9.

**Comment by fritzmg** [comment] 2021-02-12 01:14
It was originally reported only for Contao 4.10, but the issue also occurs in 4.9 of course.

**Closed as completed** 2021-02-12 07:53 UTC
Labels: bug
