### ISSUE TITLE
Backend Dropdown 'Abmelden

### ISSUE THREAD

**Issue by berecont** [contao/contao#1805] opened 2020-06-10 10:23 UTC
**Affected version(s)**

Contao 4.9 - ggf. auch andere Versionen

**Description**

Dateiverwaltung - Quelltexteditor
z-index der ersten markierten Zeile überdeckt das Dropdown-Menu, den letzten Menüpunkt 'Abmelden'    
![backend-abmelden-z-index_01](https://user-images.githubusercontent.com/33038265/84256977-f2d59280-ab14-11ea-84c2-8946fbe0ec00.png)

  
**Abhilfe**
`#tmenu ul.menu_level_1 {z-index:7;} `   

z-index auf 6 reicht nicht, da .ace_srcollbar {z-index:6;}  
![backend-abmelden-z-index_02](https://user-images.githubusercontent.com/33038265/84257014-fd902780-ab14-11ea-8e91-1ea995fcc6fe.png)

**Comment by aschempp** [comment] 2020-06-10 10:40
I could not reproduce the issue in Contao 4.4, therefore I assigned it to 4.9

**Comment by leofeyer** [comment] 2020-08-05 07:06
I could not reproduce this in Contao 4.9, either. 🤷🏻‍♂️ @berecont Which Contao version are you using?

**Comment by fritzmg** [comment] 2020-08-05 07:28
I am able to reproduce this in Contao 4.9.4, Firefox 79.0, Windows 10 x64:

<img src="https://user-images.githubusercontent.com/4970961/89384125-88486980-d6f5-11ea-9745-c4021396e3d2.png" width="326">

**Comment by berecont** [comment] 2020-08-05 07:38
I have just tested 4 installations - all in Contao 4.9.3
I can reproduce the issue in one installation - three of them are OK
all on Firefox 79.0

**Closed as completed** 2020-08-05 08:42 UTC
Labels: bug
