### ISSUE TITLE
Composer HTTP 500

### ISSUE THREAD

**Issue by NKaufeld** [contao/contao#5650] opened 2023-01-09 11:50 UTC
### Affected version(s)

all versions

### Description

https://www.composer-resolver.cloud/jobs - Can't install contao with 500 error

**Comment by m-vo** [comment] 2023-01-09 12:12
Please provide a description how the error occurs including steps to reproduce and include the full error message. Like this the issue is not helpful at all.

**Comment by NKaufeld** [comment] 2023-01-09 12:14
Don't have more. I got this quick info 'HTTP request to https://www.composer-resolver.cloud/jobs failed with status code 500 ()'

**Comment by m-vo** [comment] 2023-01-09 12:28
> Don't have more. 

That's not what I meant. You seem to use the Contao manager (?) and tried to install Contao doing what exactly? You have to tell us, otherwise nobody will be able to help.

**Comment by NKaufeld** [comment] 2023-01-09 12:51
I'm installing website step by step like always from Chrome. 

link/contao-manager.phar.php/

And i can't instal 'Composer Environment' cuz i got that error .

Just open this link, and please look at message "An unexpected error occurred. Send the Accept header with "application/json" to get more information." I think you got error on API or server. I tried to install it on another servers.

**Comment by Toflar** [comment] 2023-01-09 13:38
This URL is not meant to be opened in the browser. The error message is correct.

**Comment by NKaufeld** [comment] 2023-01-09 13:40
> 

so what i should do?

**Comment by Toflar** [comment] 2023-01-09 13:59
All I can say is that the Cloud is running smoothly. It currently processes about 3-4 jobs per minute. So whatever your problem is - it's likely not related to the Cloud. Also, you still did not provide any information on what you're trying to do. It's impossible for us to help you.
I'm also assuming that your problem is also not about a bug in Contao (the software) so this place is the wrong one.
Thus, I'm closing the issue. 

Please checkout the forums or Slack for support options (https://contao.org/en/support.html) - we can help you there. Make sure you describe what you did and what exactly is not working.

**Closed as completed by Toflar** 2023-01-09 13:59 UTC
Labels: bug, unconfirmed
