### ISSUE TITLE
Using calendars with different domains: Events containing wrong combined event urls - somehow related to #2171

### ISSUE THREAD

**Issue by hwit-biz** [contao/contao#2308] opened 2020-09-17 14:35 UTC
**Affected version(s)**

Contao 4.10

**Description**

Contao calendar module generates wrong combined event urls when using calendars on different domains.

How to duplicate:

1. Create two roots with domain a.com and b.com
2. Create two calendars, assigning the forwarding page of the first to a target on a.com and the other one to b.com
3. Insert event list (e.g. formatted with event_teaser) in content sites of both pages containing both calendars.
4. Add some events to both calendars.

Now you should see that the variable $this->href on the identical domain (source page and calendar target) contains a relative path to the event (e.g. /reader/event1.html) while the event links with different domains will be created relative but with the foreign domain instead of absolute (e.g. /b.com/reader/event1.html which will become https://a.com/b.com/reader/event1.html).

A possible workaround for affected users that I am using at the moment (that only works if you have the same reader alias on every domain) is to create a new template for e.g. event_teaser and to edit the href references as following (example for 'read more'):

`<p class="more"><a href="/reader/<?= basename ($this->href) ?>" title="<?= $this->readMore ?>"<?= $this->target ?> itemprop="url"><?= $this->more ?><span class="invisible"> <?= $this->link ?></span></a></p>`

This also shows the corresponding event on the domain you currently are, completely ignoring the foreign domain - which also is a function I am using since some time. The only reason I encountered problems was the previous use of parse_url instead of basename - so parse_url did not truncate the domain part of the url anymore.

**Comment by aschempp** [comment] 2020-09-28 10:49
Duplicate of https://github.com/contao/contao/issues/2171, this has been fixed in https://github.com/contao/contao/pull/2323 (Contao 4.10.1).

**Closed as completed by aschempp** 2020-09-28 10:49 UTC
