### ISSUE TITLE
Module "eventlist" bug with running events

### ISSUE THREAD

**Issue by Total-Reality** [contao/contao#2643] opened 2021-01-15 17:38 UTC
**Affected version(s)**
Contao 4.9 & Contao 4.10

**Description**
**Events which started already are hidden**

You can reproduce it in the Demo.

The current time is 6:36 p.m. 
I created an event which starts at the current day, startTime 6 p.m. & endTime 7 p.m.
![contao-event-settings](https://user-images.githubusercontent.com/5235894/104759434-3275f400-5760-11eb-8cd3-6465123b9762.PNG)

1. The eventlist module settings in the demo has the setting of cal_noSpan = 1 ("Verkürzte Darstellung").
![contao-module-settings](https://user-images.githubusercontent.com/5235894/104759611-74069f00-5760-11eb-8db2-4925b42ee25f.PNG)

Correct result: The event is visible. 

2. Now I remove the checkbox of cal_noSpan. 

Wrong result: My event is hidden in the eventlist:
https://demo.contao.org/preview.php/en/events.html

It is possible that you confound the setting **cal_noSpan** with **cal_hideRunning** ( "Laufende Events ausblenden") in the PHP module script?

**Comment by fritzmg** [comment] 2021-01-15 17:45
Duplicate of #2455 (I think)

**Closed as completed** 2021-01-18 05:14 UTC
