### ISSUE TITLE
Content element “Downloads” - option “Full-size view/new window” has no effect

### ISSUE THREAD

**Issue by jochi44** [contao/contao#6756] opened 2024-01-21 11:17 UTC
### Affected version(s)

5.3.0-RC1

### Description

Note: I’ve tested this with 2 files of type “pdf”:

Option “Show preview images”
Checking the option “Full-size view/new window” inside has no impact, the pdf file is shown in the current browser window not in a new window.

**Comment by fritzmg** [comment] 2024-01-21 16:16
This option relates to the preview images of the download files, not the files themselves. The option works as intended as far as I tested.

**Comment by ausi** [comment] 2024-01-22 10:02
Closed in favor of #6755

**Closed as not planned by ausi** 2024-01-22 10:02 UTC
Labels: bug, unconfirmed
