### ISSUE TITLE
Site structure options seems to be broken

### ISSUE THREAD

**Issue by Cicco0** [contao/contao#1303] opened 2020-02-10 15:30 UTC
**Affected version(s)**
4.9.0-RC1

**Description**
The current implementation does not allow to set site structure options:
- XML sitemap
- Two-factor authentication
- Set cache timeouts
-  Assign access rights

If you click on the checkbox, only "Loading data" appears. The network manager shows that the POST request is delivered to NULL:
`https://test.contao.local/null`

**How to reproduce**
1. Install Contao 4.9 RC1
2. Create new page in the site structure
3. Click on above options

**Comment by fritzmg** [comment] 2020-02-10 16:33
Duplicate of https://github.com/contao/contao/issues/1214

**Closed as completed** 2020-02-10 16:43 UTC
