### ISSUE TITLE
BE login: unitize field label positions (minor issue)

### ISSUE THREAD

**Issue by Anke** [contao/contao#5257] opened 2022-09-08 11:29 UTC
### Affected version(s)

4.13.8

### Description

Hi,

I'm using a password manager that sets own icons into the user and password fields. It is covering the Contao icon in the user field, while in the password field it is on the right-hand side of Contao's icon. 

That's how I noticed that 

- the label for username ist set to 6px, 
- the labels for password and confirm to 7 px
- the lable for password to 31px
- and the label for verify to 6px.

Maybe they can eventually be set to the same "right"-value?

https://github.com/contao/contao/blob/5.x/core-bundle/contao/themes/flexible/login.css, line 81 - 119:

```
label[for="username"] {
	position: absolute;
	top: 9px;
	right: 6px;
	background: url("icons/person.svg") left top no-repeat;
	background-size: 16px;
	width: 16px;
	height: 16px;
	text-indent: -999em;
	z-index: 1;
}

label[for="password"], label[for="confirm"] {
	position: absolute;
	top: 10px;
	right: 7px;
	background: url("icons/lock-locked.svg") left top no-repeat;
	background-size: 14px;
	width: 14px;
	height: 14px;
	text-indent: -999em;
	z-index: 1;
}

.widget-password.wizard label[for="password"] {
	right: 31px;
}

label[for="verify"] {
	position: absolute;
	top: 9px;
	right: 6px;
	background: url("icons/shield.svg") left top no-repeat;
	background-size: 16px;
	width: 16px;
	height: 16px;
	text-indent: -999em;
	z-index: 1;
}

```

**Comment by netzarbeiter** [comment] 2022-09-08 11:36
Duplicate of https://github.com/contao/contao/issues/5202

**Closed as not planned** 2022-09-08 13:54 UTC
Labels: bug, unconfirmed
