### ISSUE TITLE
Module template selection wrong base directory

### ISSUE THREAD

**Issue by rorych** [contao/contao#6842] opened 2024-02-02 09:16 UTC
### Affected version(s)

5.3.0-RC2

### Description

Updating from Contao 5.2 to 5.3.0-RC2 the selected twig templates in modules of type "template" (Individuelles Template) from the folder frontend_module/template/ are declared "unknown" and "content_element/template" is suggested. This seems to be a bug.

Here an example:
<img width="832" alt="example" src="https://github.com/contao/contao/assets/2022054/09492338-7158-42d0-91f7-a26b91d79c09">

**Comment by fritzmg** [comment] 2024-02-02 09:22
I can reproduce the issue.

**Comment by leofeyer** [comment] 2024-02-02 16:20
This is because there is a frontend module and a content element with the same key.

<img width="656" alt="" src="https://github.com/contao/contao/assets/1192057/d72cb5f3-02d3-469e-835c-66d00149c258">

The second one wins. 🤦‍♂️

**Comment by leofeyer** [comment] 2024-02-02 16:22
It is even worse, the second call completely overwrites the first array. It seems like the `setDefaultIdentifiersByType()` method is not meant to be called multiple times.

**Comment by leofeyer** [comment] 2024-02-02 17:11
Oh, you are not going to like that. 🙈 It is an auto-configuration problem.

https://github.com/contao/contao/blob/b6a46ed04fc1166ffbd367d63c77d8752d7976cb/core-bundle/src/EventListener/DataContainer/TemplateOptionsListener.php#L26-L29

Instead of adding one callback to every table, it adds three:

<img width="484" alt="" src="https://github.com/contao/contao/assets/1192057/3d29cff5-4871-42fe-8fc1-824556dfd145">

And only the first one wins. This did not happen before when the tags were added in the `services.yaml` file.

**Comment by fritzmg** [comment] 2024-02-02 17:21
But that's then an issue with our `AsCallback` attribute/annotation, which needs to be fixed in any case. It should not matter how you tag your services.

**Comment by leofeyer** [comment] 2024-02-02 17:26
I thought so too, but I couldn't figure out what made the difference.

**Comment by fritzmg** [comment] 2024-02-02 18:00
Oh, I see, it's because we have to create 3 different instances of this service. And they all get tagged by all 3 tags - even though only _one_ of the tags is meant to be applied for each instance. So yes, for _this_ particular service we cannot use Attributes or Annotations.

**Comment by ausi** [comment] 2024-02-02 18:02
> So yes, for _this_ particular service we cannot use Attributes or Annotations.

As an alternative we could combine them into a singe service and set `$legacyTemplatePrefix` and `$legacyProxyClass` depending on the value of `$dc->table`.

**Comment by fritzmg** [comment] 2024-02-02 18:06
You mean pass a mapping array into the service for example? Or just hardcode it into the listener.

**Comment by ausi** [comment] 2024-02-02 19:12
I’d probably hardcode it, doesn’t look to me like this can be reused for a different use case anyway.

**Comment by m-vo** [comment] 2024-02-02 21:58
What a subtle problem! 🙈

I'm +1 for hardcoding - it's for the legacy logic only anyways.

**Comment by zoglo** [comment] 2024-02-02 23:33
Selecting `mod_navigation` (with legacy templates) is possible but it is also shown as `ce_navigation` within the module templates itself. I guess this is related?

![image](https://github.com/contao/contao/assets/55794780/93f803fd-df39-4b95-a687-2ba0dbf004e1)
![image](https://github.com/contao/contao/assets/55794780/036bc438-6dd0-4e07-b264-6bbfa64d35fd)

*Can reproduce it in the demo as well under 5.3.x*
![image](https://github.com/contao/contao/assets/55794780/3aac9108-80fb-4729-85d4-85faa791df26)


Please mind that the selected and overriden template within `/templates` is actually being used within the module.
Seems like it's just translated to being `ce_navigation` even if it actually is `mod_navigation`?

/cc @leofeyer @m-vo could this be a separate issue?

**Comment by fritzmg** [comment] 2024-02-03 09:42
No, it's the same issue, as far as I tested.

**Comment by fritzmg** [comment] 2024-02-03 13:00
@zoglo can you also confirm that #6852 fixes it?

**Comment by zoglo** [comment] 2024-02-03 21:47
Sorry that it took so long to check it out. I can confirm it is fixed now @fritzmg

**Closed as completed** 2024-02-09 09:55 UTC
Labels: bug
