### ISSUE TITLE
Calling unpublished sibling page of forward target causes redirect instead of immediate 404

### ISSUE THREAD

**Issue by gmpf** [contao/contao#488] opened 2019-05-13 17:45 UTC
Tested in Contao 4.4.39

## How to reproduce

* Activate `folderUrl`

* Create a page structure like this:
  ```
  foo
  foo/bar
  foo/baz
  ```

* Make `foo` an internal redirect (page type `forward`) to `foo/bar`.

* Unpublish `foo/baz`.

* Call `example.test/foo/baz.html`

Result: Redirect to `example.test/foo/bar/baz.html` (404).
Expected: Immediate 404.

## Cause

In `Frontend::getPageIdFromUrl()`, `PageModel::findByAliases()` is called[1], which purposefully does not find unpublished pages[2]. As a result, `baz` is used as an `auto_item` value added to `foo` instead. Then, as `foo` is a `forward` page, we get a redirect to `foo/bar` with `baz` added in `PageForward::getForwardUrl()`[3].

Here is some context on where this has come from:
https://github.com/contao/core/issues/4652
The intent is that the alias of an unpublished page does not prevent a fragment of that alias (in this case, `baz`) from being used as an `auto_item` value or full GET variable/value pair. It's nice that we don't have that limitation, but as a result, we have this redirect issue instead. :D

## What now?

I'm not sure how to solve this in a way that doesn't break any other aspect of `folderUrl`. I suppose one could add this to the very end of `PageForward::getForwardUrl()`, just before the `return` statement[4]:
```
$objTargetPage = \PageModel::findByAlias($objPage->alias . $strGet);
if ($objTargetPage !== null)
{
	while ($objTargetPage->next())
	{
		if ($objTargetPage->published == '1')
		{
			continue;
		}

		$objUnpublishedPage = $objTargetPage->current();
		$objUnpublishedPage->loadDetails();
		if ($objUnpublishedPage->language === $objPage->language)
		{
			throw new PageNotFoundException('Page not found');
		}
	}
}
```

It works, but it requires an extra DB request for the target page *plus* `loadDetails()`. Furthermore, far into `PageForward` is an unexpected place to have another check whether we might want to throw a `PageNotFoundException`.

It can also be considered a break in expected behavior, in case somebody actually needs a parameter to be passed via the forward page for some reason (maybe short URLs…?).

Possibly related: https://github.com/contao/contao/issues/316

---

[1] https://github.com/contao/contao/blob/947b6254e4420a22ba58f6baffb125da561dd459/core-bundle/src/Resources/contao/classes/Frontend.php#L136
[2] https://github.com/contao/contao/blob/947b6254e4420a22ba58f6baffb125da561dd459/core-bundle/src/Resources/contao/models/PageModel.php#L509-L513
[3] https://github.com/contao/contao/blob/947b6254e4420a22ba58f6baffb125da561dd459/core-bundle/src/Resources/contao/pages/PageForward.php#L90-L116 
[4] https://github.com/contao/contao/blob/947b6254e4420a22ba58f6baffb125da561dd459/core-bundle/src/Resources/contao/pages/PageForward.php#L123-L125

**Comment by leofeyer** [comment] 2019-07-12 10:00
Since this does not do any harm other than adding one unnecessary redirect, and given that we have switched to the Symfony CMF router in Contao 4.7, I would not fix this at all. Or does the issue occur in Contao 4.7 as well?

@aschempp /cc

**Comment by gmpf** [comment] 2019-07-12 10:08
> Since this does not do any harm other than adding one unnecessary redirect

If the redirect is a 301, the visitor gets stuck with a 404 even when the actual page (`foo/baz` in the example) gets re-published, because the redirect to `foo/bar/baz.html` is cached.

**Comment by aschempp** [comment] 2019-07-22 07:50
Shouldn't a 301 cache the redirect location, but not the resulting page?

**Comment by gmpf** [comment] 2019-07-22 08:21
> Shouldn't a 301 cache the redirect location, but not the resulting page?

Yes, that's what it does, but the location in this scenario is always a page that does not ever exist. Follow the reproduction steps and then do this:

- Re-publish `foo/baz`.
- Call `example.test/foo/baz.html` again.

The result remains the same.

This comes up every now and then when an editor edits a new, unpublished page in the back end, then opens it from there, forgetting to publish it beforehand. The issue occurs as described, the editor goes back and publishes the page, but is now stuck with the redirect. They then have to notice the incorrect URL and clear the browser cache.

Also, if any visitor has bookmarked a page that is unpublished for a while for whatever reason, and they get stuck with that redirect once, they never get the page back unless they realize what is happening and know how to fix it.

**Comment by leofeyer** [comment] 2019-08-28 16:28
This is a tricky one, because `foo/bar/baz.html` is an ambiguous route:

* Page `foo` with the parameters `[bar => baz]`
* Page `foo/bar` with the paramters `[auto_item => baz]`

Contao keeps redirecting until the route is no longer ambiguous, ending up with a 404 error on `foo/bar/bar/bar/baz.html` in my case (Contao 4.8).

**Comment by leofeyer** [comment] 2019-08-29 13:23
As discussed in Mumble on August 29th, the initial use case described by @gmpf is the expected behavior. The additional redirect in my case needs to be debugged.

Furthermore, we have discussed adding a checkbox to enable redirects if there are parameters:

| Checkbox | Parameters | Behavior |
| --- | --- | --- |
| Enabled | yes | Redirect |
| Enabled | no | Redirect |
| Disabled | yes | 404 |
| Disabled | no | Redirect |

**Comment by aschempp** [comment] 2020-09-07 09:19
Is there an actual reason to redirect with parameters at all?

**Comment by gmpf** [comment] 2020-09-07 09:40
> Is there an actual reason to redirect with parameters at all?

I was thinking about short URLs. E. g. you have a page `news` that redirects to a page with a longer alias `somewhere/in/page-tree/news-reader-page`, and that page contains a reader module. So you can link to `example.com/news/alias-of-news-article` instead of `example.com/somewhere/in/page-tree/news-reader-page/alias-of-news-article`. I've never done something like that, but it seems like a valid enough use case to me.

**Comment by fritzmg** [comment] 2023-08-22 09:27
imho this is a bug that definitely needs to be fixed in Contao 4.13 (see also #6216). Consider the following site structure:

* `foo` _301_
* `foo/bar` _regular_
* `foo/mar` _regular_

Responses:

* `example.com/foo`: `301`
* `example.com/foo/bar`: `200`
* `example.com/foo/mar`: `200`

Now delete the page with the alias `foo/bar`.

Responses:

* `example.com/foo`: `301`
* `example.com/foo/bar`: `301` ❗ 
* `example.com/foo/mar`: `200`

This is definitely an error - otherwise Contao will inadvertently tell crawlers that the content of the previously deleted page is still available under a new canonical URL defined by the `301` redirect - but that redirect has nothing to do with said URL.

**Comment by fritzmg** [comment] 2023-08-22 09:58
This issue exists both for internal _and_ external redirects btw. And external redirects do not even support forwarding the path parameters, so at the very least we need to fix it there.

For anyone who does not care about the feature of forwarding the path parameters for internal redirects and wanting to fix this issue for external redirect pages too, here is what you can do in the mean time:

```php
// src/Page/RedirectPageTrait.php
namespace App\Page;

use Contao\System;
use Symfony\Component\HttpFoundation\Request;

trait RedirectPageTrait
{
    private function hasPathParameter(): bool
    {
        if (empty($_GET)) {
            return false;
        }

        /** @var Request $request */
        $request = System::getContainer()->get('request_stack')->getCurrentRequest();

        foreach (array_keys($_GET) as $key) {
            if ('language' === $key) {
                continue;
            }

            if (\is_array($_GET[$key]))  {
                continue;
            }

            if ($request->query->has($key)) {
                continue;
            }

            // Current key is path parameter inserted by Contao
            return true;
        }

        return false;
    }
}

```
```php
// src/Page/ForwardPage.php
namespace App\Page;

use Contao\CoreBundle\Exception\PageNotFoundException;
use Contao\PageForward;

class ForwardPage extends PageForward
{
    use RedirectPageTrait;

    public function getResponse($objPage)
    {
        if ($this->hasPathParameter()) {
            throw new PageNotFoundException();
        }

        return parent::getResponse($objPage);
    }
}
```
```php
// src/Page/RedirectPage.php
namespace App\Page;

use Contao\CoreBundle\Exception\PageNotFoundException;
use Contao\PageRedirect;

class RedirectPage extends PageRedirect
{
    use RedirectPageTrait;

    public function getResponse($objPage)
    {
        if ($this->hasPathParameter()) {
            throw new PageNotFoundException();
        }

        return parent::getResponse($objPage);
    }
}
```
```php
// contao/config/config.php
use App\Page\ForwardPage;
use App\Page\RedirectPage;

$GLOBALS['TL_PTY']['forward'] = ForwardPage::class;
$GLOBALS['TL_PTY']['redirect'] = RedirectPage::class;
```

**Comment by leofeyer** [comment] 2023-08-22 11:29
Why would `example.com/foo/bar` return `301` if the page has been deleted? It should return `404` in this case.

**Comment by fritzmg** [comment] 2023-08-22 11:33
@leofeyer that is what this issue is about, see description above. Contao treats `bar` as an `auto_item` of `foo` and thus the `301` page (under the alias `foo`) is rendered and it in turn will redirect - while preserving the `auto_item` parameter - which is a deliberate feature of `PageForward` and thus the fix for this was tagged as a feature, as this cannot be removed without a BC break.

The behavior can be fixed for `PageRedirect` without a BC break though (as it does not support forwarding the path parameters).

**Comment by leofeyer** [comment] 2023-08-24 16:03
As discussed in the call, we want to fix this as [outlined above](https://github.com/contao/contao/issues/488#issuecomment-526183143) as bugfix for Contao 4.13. The checkbox shall be disabled by default and should be called "forward query parameters" or something alike.

**Comment by ausi** [comment] 2023-08-24 16:27
> …and should be called "forward query parameters" or something alike.

I’d name it something like “Forward parameters” with a help text of “Forward query and path parameters to the target page”

**Comment by leofeyer** [comment] 2023-08-30 10:24
Should it not rather be "Forward with parameters" and the help text "Forward to the target page even if there are query or path parameters"? To indicate that the page will not forward by default if there are parameters.

**Closed as completed** 2023-09-07 14:49 UTC
Labels: bug
