### ISSUE TITLE
The title of downloads no longer work in version 5.1

### ISSUE THREAD

**Issue by heimseiten** [contao/contao#5982] opened 2023-04-24 11:59 UTC
### Affected version(s)

5.1

### Description

In the content elements "Download" "Downloads" the titles don't show up in the frontend. In 4.13 it works.

**Comment by Toflar** [comment] 2023-04-24 12:21
Duplicate of https://github.com/contao/contao/issues/5975?

**Comment by heimseiten** [comment] 2023-04-24 14:15
Yes. Sorry 🙈. The fix solved the issue

Thank you!

**Closed as completed** 2023-04-24 14:15 UTC
Labels: bug, unconfirmed
