### ISSUE TITLE
TinyMCE Editor strips file insert-tag

### ISSUE THREAD

**Issue by MarkejN** [contao/contao#3474] opened 2021-09-15 12:18 UTC
**Affected version(s)**

Tested with Contao 4.12.1

**Description**

When I use the file picker in the tinyMCE editor,

`<p><a href="{{file::fd49ae5c-450f-11eb-b48c-00155d04a7a8|urlattr}}">test</a></p>`

is written correctly to the database. But the editor now incorrectly shows me

`<p><a href="fd49ae5c-450f-11eb-b48c-00155d04a7a8|urlattr">test</a></p>`

in the code view.  If I save further changes in the editor, then of course the broken link is also saved.

**Comment by fritzmg** [comment] 2021-09-15 12:42
Duplicate of https://github.com/contao/contao/issues/3430

Will be fixed with the next Contao bugfix release.

**Closed as completed by fritzmg** 2021-09-15 12:42 UTC
