### ISSUE TITLE
"Internal Server Error: 3 arguments are required, 2 given" when having a "%" char in the site name of the website startpoint

### ISSUE THREAD

**Issue by Alexander060101** [contao/contao#3420] opened 2021-09-04 20:36 UTC
**Affected version(s)**
Contao 4.9.20 running on PHP v.8.0.10

I was not able to replicate the issue on the demo site so it might be only with PHP 8.0.
I do not know on which version the demo site runs though.

**Description**
After a fresh installation while trying to set up my site structure I noticed this issue.
When adding the website startpoint with a "%" char in the site name I can not add a site inside that start point.
It fails with "Internal Server Error: 3 arguments are required, 2 given".
After I rename the start point to something without % it works just fine.

**Comment by ausi** [comment] 2021-09-05 08:46
I was not able to reproduce this issue.

Can you please enable the debug mode and try it again?
This should show a more detailed error message with a full stack trace.

**Comment by fritzmg** [comment] 2021-09-05 11:13
I was not able to reproduce the exact error as described in this issue, but I was able to reproduce a warning when trying to insert a new page within the site structure of a root that has `%` in its title: https://github.com/contao/contao/pull/3422

**Comment by Alexander060101** [comment] 2021-09-05 12:58
This is the full stack trace I get in debug mode:

```
ArgumentCountError:
3 arguments are required, 2 given

  at vendor/contao/core-bundle/src/Resources/contao/widgets/SerpPreview.php:73
  at sprintf()
     (vendor/contao/core-bundle/src/Resources/contao/widgets/SerpPreview.php:73)
  at Contao\SerpPreview->generate()
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Widget.php:651)
  at Contao\Widget->generateWithError()
     (vendor/contao/core-bundle/src/Resources/contao/templates/backend/be_widget.html5:3)
  at include('/var/www/vhosts/deutschrock.net/debug.deutschrock.net/vendor/contao/core-bundle/src/Resources/contao/templates/backend/be_widget.html5')
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/TemplateInheritance.php:100)
  at Contao\Widget->inherit()
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Widget.php:598)
  at Contao\Widget->parse()
     (vendor/contao/core-bundle/src/Resources/contao/classes/DataContainer.php:668)
  at Contao\DataContainer->row()
     (vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php:1985)
  at Contao\DC_Table->edit()
     (vendor/contao/core-bundle/src/Resources/contao/classes/Backend.php:644)
  at Contao\Backend->getBackendModule()
     (vendor/contao/core-bundle/src/Resources/contao/controllers/BackendMain.php:167)
  at Contao\BackendMain->run()
     (vendor/contao/core-bundle/src/Controller/BackendController.php:48)
  at Contao\CoreBundle\Controller\BackendController->mainAction()
     (vendor/symfony/http-kernel/HttpKernel.php:158)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (vendor/symfony/http-kernel/HttpKernel.php:80)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (vendor/symfony/http-kernel/Kernel.php:201)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (web/index.php:31)
```

**Comment by fritzmg** [comment] 2021-09-06 12:44
Yes, I can reproduce that actually with the same error. Closing in favor of #3422

**Closed as completed by fritzmg** 2021-09-06 12:44 UTC
Labels: bug, unconfirmed
