### ISSUE TITLE
Cannot select custom layout section template

### ISSUE THREAD

**Issue by patrickjDE** [contao/contao#677] opened 2019-08-27 14:05 UTC
**Affected version(s)**
4.8.1

**Description**  
It's not possible to select a template in the SectionWizard, the select is emtpy

**How to reproduce**  
Edit a Layout and try to create a custom section

It's caused by the changes from 32d0aa1374ff3a1356a5f3c90010331a718c17f7 and 645fc91627b7723f3c95ca56f6603349a6d15dfb.

**Comment by patrickjDE** [comment] 2019-08-27 15:31
You actually can select custom templates from the template folder, if some exist, but are then unable to select the default one.

Additionally custom templates provided by modules cannot be selected, but that's not specific to layout sections (see https://github.com/contao/contao/pull/657#issuecomment-525338293)

**Comment by leofeyer** [comment] 2019-08-27 15:37
What are the exact steps to reproduce this issue?

**Comment by fritzmg** [comment] 2019-08-27 16:04
@leofeyer 

1. Log into the back end of the Contao demo.
2. Edit a page layout.
3. Under __Custom layout sections__ create a custom layout section. Note that you are not able to select a template (usually would be `block_section`).
4. Save.
5. Under __Included modules__ create a new module for the previously created custom layout section and choose any module that would generate some HTML output (e.g. "Header - Logo").
6. Save.
7. Open the front end.

The output for the custom layout section will be 
```html
<div class="custom">
        </div>
```
presumably because no template could be selected.

**Comment by leofeyer** [comment] 2019-08-27 19:32
Does 0daf4fbd904f3e8c8f6e2eec29f731724fa4a7c5 fix the issue?

**Edit**: It seems it does not. 😢

**Comment by leofeyer** [comment] 2019-08-28 09:16
Fixed in 4070c7a07b434e542b59d63d1a5b696c2e45ff4e.

**Closed as completed by leofeyer** 2019-08-28 09:16 UTC
Labels: bug
