### ISSUE TITLE
Contao 4.6.12 and doctrine/dbal version 2.8.1, 2.9.0, 29.1, 2.9.2

### ISSUE THREAD

**Issue by sdahlmann** [contao/contao#272] opened 2019-01-12 17:52 UTC
When I install Contao 4.6.12 with doctrine / dbal version 2.8.1, 2.9.0, 29.1 or 2.9.2, I can not update the MySQL database in Contao.
If I mark doctrine / dbal version 2.9.0, 29.1 or 2.9.2 as a conflict, only version 2.8.1 will be installed and at the same time Contao 4.6.11 will be installed. Then I make a clean database update.
Question I have: Is the problem fixed, if doctrine / dbal version 2.9.3 comes out or does it have to install a new Contao version 4.6.13, which will be released with the problem fixed?

**Comment by xchs** [comment] 2019-01-12 18:33
Duplicate of https://github.com/contao/contao/issues/261

**Comment by xchs** [comment] 2019-01-12 18:39
A conflict entry for `"doctrine/dbal": "2.9.1 || 2.9.2"` should be sufficient to fix the problem in the meantime until Doctrine DBAL 2.9.3 is released.

**Closed as completed** 2019-01-13 09:43 UTC
