### ISSUE TITLE
Pages of type "Internal redirect" missing in navigation with set stop level

### ISSUE THREAD

**Issue by joehi** [contao/contao#466] opened 2019-05-01 11:45 UTC
**Affected version(s)**
4.7.5

**Description**  
Pages of type "Internal redirect" do not show up in the navigation when they appear on the same level which is set as stop leven in the navigation module. Normal pages appear in the navigation as expected.
This happened after upgrading to contao version 4.7.5. Up to version 4.7.4 everything was okay. Version 4.4.39 is not affected either.

**How to reproduce**  
Create some pages of type "Regular page" as well as pages of type "Internal redirect".

Page setup:
```
Start
Page 2
-Page 2.1
-Redirect 2.2
--Page 2.2.1
--Page 2.2.2
Redirect 3
-Page 3.1
-Page 3.2
```

Set in module navigation the following settings:
Start level = 0
Stop level = 0
Result: all pages are shown in navigation as expected

Set in module navigation the following settings:
Start level = 0
Stop level = 1
Result: "Redirect 3" is missing:
```
Start
Page 2
```

Set in module navigation the following settings:
Start level = 0
Stop level = 2
Result: "Redirect 2.2" ist missing:
```
Start
Page 2
-Page 2.1
Redirect 3
-Page 3.1
-Page 3.2
```

Set in module navigation the following settings:
Start level = 0
Stop level = 3
Result: all pages are shown in navigation as expected

**temporary Solution**
downgrade back to contao version 4.7.4

**Comment by fritzmg** [comment] 2019-05-01 11:49
I can confirm the issue. I think it only happens if the _target page_ is excluded by the stop level.

**Comment by Kahmoon** [comment] 2019-05-04 06:02
Is there a hotfix until 4.7.6 is released. A pretty big site from me is using many forward navigation elements and almost half of the navigation is actually not shown :-(.

Frank

**Comment by fritzmg** [comment] 2019-05-04 10:13
@Kahmoon well the short term solution is to switch back to Contao 4.7.5.

**Comment by fritzmg** [comment] 2019-05-04 10:37
The problem is caused by these changes in `Module`: 

https://github.com/contao/contao/commit/868a114bc3ca9bb3b98f11b85d59191bbffaf84c#diff-23a51a86d2ad053ad93aa675360288c8L341

The `isPublic` property of the `PageModel` will only be set in the `loadDetails()` function. Thus we need something like this:
```diff
	case 'forward':
		if ($objSubpage->jumpTo)
		{
			$objNext = PageModel::findPublishedById($objSubpage->jumpTo);
		}
		else
		{
			$objNext = PageModel::findFirstPublishedRegularByPid($objSubpage->id);
		}
+
+		// Load the details (see contao/contao#466)
+		if ($objNext instanceof PageModel)
+		{
+			$objNext->loadDetails();
+		}

		// Hide the link if the target page is invisible
		if (!$objNext instanceof PageModel || (!$objNext->isPublic && !BE_USER_LOGGED_IN))
		{
			continue 2;
		}
```
It works without stop levels, because then all the sub pages are loaded with details - because the navigation builds itself depth-first - and
```php
$href = $objSubpage->getFrontendUrl();
```
loads the details of the page.

**Comment by leofeyer** [comment] 2019-05-06 11:15
Fixed in ba1e039fe86bcd97d1a8f2757e9a4c365be2a86b.

**Closed as completed by leofeyer** 2019-05-06 11:15 UTC
Labels: bug

**Comment by fritzmg** [comment] 2019-05-06 11:24
Btw. @leofeyer wouldn't it make sense to overwrite `__get()` in the PageModel and execute `loadDetails()` for any non-database properties?

**Comment by leofeyer** [comment] 2019-05-06 11:30
Interesting idea. @contao/developers WDYT?

**Comment by aschempp** [comment] 2019-05-06 18:52
I like the idea as well, but I would probably hardcode for the "loadDetails" fields.

**Comment by leofeyer** [comment] 2019-05-07 06:25
> I like the idea as well, but I would probably hardcode for the "loadDetails" fields.

Do you mean the "isPublic" field?

**Comment by aschempp** [comment] 2019-05-07 07:06
I mean any field that is inherited. However, that might not work as there is also a hook…

> wouldn't it make sense to overwrite __get() in the PageModel and execute loadDetails() for any non-database properties?

There are fields that are database properties but are still inherited. Those need to be handled as well…

**Comment by fritzmg** [comment] 2019-05-07 07:44
Yeah, it would need to be a maintained list of properties.

> I mean any field that is inherited. However, that might not work as there is also a hook…

Hm, which hook are you referring to?

**Comment by Toflar** [comment] 2019-05-07 07:53
The new one we've introduced in master. We could also revert that and have a list of properties one can extend. Would maybe also be a good idea because those are the fields that in theory could be stored in a field in the back end instead of loaded on demand on every page impression.

**Comment by fritzmg** [comment] 2019-05-07 08:00
Ah, I see. Hmm... well the hook is only executed anyway, if `loadDetails()` is executed. Hence it relies on the correct usage of `loadDetails()`. And this proposed change would ensure, that at least for maintained properties, the `loadDetails()` function is always executed.

So - don't we need both? The hook plus an extensible list of `PageModel` properties that are loaded via `loadDetails()`? The list alone would not suffice, would it? You still need the logic to actually fill your own custom `PageModel` property somewhere.

**Comment by leofeyer** [comment] 2019-05-09 10:58
I had already added this to the `PageModel` class:

```php
/**
 * Return an object property
 *
 * @param string $strKey The property key
 *
 * @return mixed|null The property value or null
 */
public function __get($strKey)
{
	static $arrDynamic = array
	(
		'trail',
		'mainAlias',
		'mainTitle',
		'mainPageTitle',
		'parentAlias',
		'parentTitle',
		'parentPageTitle',
		'folderUrl',
		'isPublic',
		'rootId',
		'rootAlias',
		'rootTitle',
		'rootPageTitle',
		'rootSorting',
		'domain',
		'rootLanguage',
		'rootIsPublic',
		'rootIsFallback',
		'rootUseSSL',
		'rootFallbackLanguage',
		'subpages',
		'minifyMarkup',
		'layoutId',
		'hasJQuery',
		'hasMooTools',
		'isMobile',
		'template',
		'templateGroup'
	);

	if (!isset($this->arrData[$strKey]) && \in_array($strKey, $arrDynamic))
	{
		throw new \RuntimeException(sprintf('It seems that $page->%s is not set. Did you call loadDetails()?', $strKey));
	}

	return parent::__get($strKey);
}
```

However, since it is a behavior change, I did not commit the changes. We could use the routine to automatically execute `loadDetails()` though, couldn't we?

**Comment by Toflar** [comment] 2019-05-09 11:02
It needs to be extensible anyway.

**Comment by aschempp** [comment] 2019-05-09 11:35
Should we not run `loadDetails` automatically?

However, nothing will work automatically. The field `domain` can have a value if the page was previously a `root` type, but now it should be inherited…

**Comment by dmolineus** [comment] 2019-05-16 09:00
Calling `loadDetails` automatically would prevent that the model could be saved. This might cause some unexpected side effects.

https://github.com/contao/core-bundle/blob/8a6bcd28e54c1ab6bea5d35be3f328146b399a41/src/Resources/contao/models/PageModel.php#L1025

**Comment by fritzmg** [comment] 2019-05-16 09:02
@dmolineus yes, but `loadDetails` should only be called if you want to access the details anyway. And then you will not be able to save the model anymore, no matter if it was called automatically for you or if it was called by you.
