### ISSUE TITLE
The dump() function is no longer displayed in the Symfony debug bar

### ISSUE THREAD

**Issue by ufeldmann** [contao/contao#7310] opened 2024-06-28 07:51 UTC
### Affected version(s)

5.3.10

### Description

The dump() function is no longer displayed in the Symfony debug bar in 5.3.10.
It works in 5.3.9. 
I was also able to reproduce it in the demo installation.

Thanks for checking.

**Comment by michb** [comment] 2024-06-28 09:02
What kind of `dump` are you using
```php
<?php dump($foo); ?>
```

```twig
{{ dump(foo) }}
```
```twig
{% dump foo %}
```

**Comment by ufeldmann** [comment] 2024-06-28 09:14
Sorry, I just tried

`<?php dump($foo); ?>`

In the demo installation I just added a quick test dump inside the TextController.
If debug is not activated it will be shown above the content. But if debug is activated there is no dump result inside the Symfony Debug.

**Comment by fritzmg** [comment] 2024-06-28 10:30
I can confirm the issue as well. Downgrading to `5.3.9` let's the `dump()` show up in the toolbar again.

**Comment by leofeyer** [comment] 2024-06-28 10:35
I don‘t see any change that could have caused this though. 🤔

**Comment by fritzmg** [comment] 2024-06-28 10:38
~git bisect says this is the commit that caused it: https://github.com/contao/contao/commit/2b4ccc372ec0a6e610db9468a922c62db39afe84~ nvm, the git bisect result is wrong - still don't know which commit it actually is though.

**Comment by Toflar** [comment] 2024-06-28 11:07
It's due to the new `WebWorker`. I have debugged this. If you uncomment the `kernel.terminate` event, the dumps come back. Makes no sense but that's the change.

**Comment by Toflar** [comment] 2024-06-28 11:46
Fixed in https://github.com/contao/contao/pull/7315.

**Closed as completed by Toflar** 2024-06-28 11:46 UTC
Labels: bug
