### ISSUE TITLE
no new article by adding a new page to site structure

### ISSUE THREAD

**Issue by magicsepp** [contao/contao#2620] opened 2021-01-04 11:49 UTC
**Affected version(s)**

Contao 4.10.5?

**Description**

select a new page in site structure - with or with out layout there is no new article see pictire
![Screenshot_2021-01-04 Artikel](https://user-images.githubusercontent.com/1285182/103532308-4df11d00-4e8b-11eb-89dc-a095cd9fedd0.png)

**Comment by fritzmg** [comment] 2021-01-04 11:51
Duplicate of #2179

**Closed as completed by fritzmg** 2021-01-04 11:51 UTC
