### ISSUE TITLE
Override templates located in sub folders not working

### ISSUE THREAD

**Issue by Defcon0** [contao/contao#1021] opened 2019-11-27 09:10 UTC
**Affected version(s)**
4.4

**Description**  
I have the following setup:

A multi-domain project with multiple themes (tl_theme). Each theme has its own templates-folder (let's say `project1` and `project2`).

Now I have two templates named `fe_page.html5` in the following folders:

`<root>/templates/project1/fe_page.html5`
`<root>/templates/project2/fe_page.html5`

Now when I visit both pages everything works as expected.

Then I wanted to bring more structure to my templates by using sub folders (as done in the core):

`<root>/templates/project1/frontend/fe_page.html5`
`<root>/templates/project2/frontend/fe_page.html5`

Now it doesn't work anymore. Both sites use the second template now (in project2).

Maybe this is because somewhere in the code contao is only checking for

`<root>/templates/<template group name>/fe_page.html5`

If not found, it seems to search recursively (*) and the last one wins. Hence `<root>/templates/project2/frontend/fe_page.html5` is used.

Is this a bug? And if so, my solution would be that the step (*) that searches recursively in `templates` should only search recursively in `templates/<current template group`. If something is found, takt it, if not search in `templates` like before.

Bye Defcon0

**Comment by fritzmg** [comment] 2019-11-27 09:14
You can't have additional subfolders. A subfolder in the `templates/` directory is assigned to a theme. Any template in this subfolder is then only available/used in that theme. Templates in sub-subfolders are ignored.

**Comment by Defcon0** [comment] 2019-11-27 09:26
I understand, but having a `templates` folder in large projects with 75+ templates without any sub folder structurization is no fun to have :-(

What's wrong with the solution I proposed above?

**Comment by m-vo** [comment] 2019-11-27 09:57
It's not a bug but a legitimate feature I think. :smile:

**Comment by leofeyer** [comment] 2019-12-10 11:50
The template loader does not search recursively.

https://github.com/contao/contao/blob/09ba4829c44fa7155198e1393ebf22ebbb5359d8/core-bundle/src/Resources/contao/library/Contao/TemplateLoader.php#L92-L112

It just checks the theme templates folder and the global templates folder with a simple `file_exists()` call. A recursive search would noticeably decrease the performance, because these lookups cannot be cached.

**Comment by Defcon0** [comment] 2019-12-10 14:32
I understand your opinion. Would the following be an option:

We support 1 level of nesting. I think the maximum level of nesting in contao modules is just this.

The current state that we cannot have sub folders at all is quite frustrating :(

And one thing I didn't understand: Why can't these lookups be cached? Wouldn't it be acceptable to have caching (even in dev mode)?

**Comment by ausi** [comment] 2019-12-10 19:23
This would change how the templates folder works in Contao and would be a BC break.

For example if you have Theme 1 which uses the root templates folder and Theme 2 that uses the folder `theme2`. With your suggested change now Theme 1 would load the `theme2/fe_page.html5` template from the subfolder which is probably not expected.

**Comment by Defcon0** [comment] 2019-12-10 19:39
You're right. But if a developer decides to create subfolders for his themes, he would probably also have set `templates/theme1` as the templates folder theme 1.

My expectation would be the following prioritization (descending order):

1. `templates/<template group name>/` -> search recursively (1 level at maximum)
2. `templates/<template group name>/` -> search directly in the first level without searching recursively (the current behavior)
3. `templates` -> search recursively like it's the current behavior

Or do you have an other solution for dealing with the fact that with the current state we have template folders with a large amount of template files without any structure in it?

In addition to this if contao is moving to more and more make use of symfony: are there any plans how to deal with that situation with symfony's twig template overriding strategy (escpecially taking into a account multi domain systems)?

**Comment by leofeyer** [comment] 2022-06-09 10:13
@m-vo This will be supported in Contao 5, won‘t it?

**Comment by aschempp** [comment] 2022-08-26 06:26
ping @m-vo

**Comment by m-vo** [comment] 2022-08-31 18:28
In Contao 5 you can have Twig templates in sub directories. If a `.twig-root` file is added to the respective root, the names of the sub directories inside this root will be part of the template names. If `templates/something/.twig-root` exists, a template `bar.html.twig` inside `templates/something/foo` would be available as `@Contao/foo/bar.html.twig` (or respectively `foo/bar` if only looking at the type).

We use this for the new content elements in Contao 5: `ce_text` became `content_element/text`, i.e. a `text.html.twig` file inside a `content_element` directory in a Contao template folder that has a `.twig-root` file present. Note, that the actual name of the root directory does not matter (as before).

Is that what you were trying to achieve?

**Comment by ausi** [comment] 2022-09-01 08:05
Maybe we could make the `/templates` folder (and every theme folder) an implicit twig-root, because we did not allow nesting html5 templates there so there is already a different behavior for html5 templates.

**Comment by m-vo** [comment] 2022-09-02 14:01
See #5242

**Closed as completed by m-vo** 2022-09-02 14:01 UTC
Labels: feature, BC break
