### ISSUE TITLE
Favicon wird im Header nicht eingebunden

### ISSUE THREAD

**Issue by chriza** [contao/contao#2986] opened 2021-05-01 06:04 UTC
Contao 4.11.2

In den Website-Einstellungen habe ich ein Favicon angewählt. Dieses wird im Header nicht referenziert, was von den SEO-Tools bemängelt wird.

**Comment by xchs** [comment] 2021-05-01 15:21
Siehe z. B. https://github.com/contao/contao/issues/2457

**Comment by RWesemann** [comment] 2021-05-06 17:25
> Siehe z. B. #2457

Das ist zwar korrekt, dass das Favicon nicht im Header referenziert und nur die URL generiert wird, das funktioniert aber trotzdem nicht. Kann man auch unter https://demo.contao.org nachvollziehen, wenn man zuvor die Favicon-Links aus den zusätzlichen Head-Tags aus dem Seitenlayout entfernt.

**Comment by fritzmg** [comment] 2021-05-06 17:57
> das funktioniert aber trotzdem nicht

What exactly does not work?

**Comment by RWesemann** [comment] 2021-05-06 18:04
> > das funktioniert aber trotzdem nicht
> 
> What exactly does not work?

The favicon is not accessible via the URL `(https://example.com/favicon.ico)` if the favicon was included via the site structure.

**Comment by RWesemann** [comment] 2021-05-06 18:38
I have to put this into perspective, because you can't track it that clearly on https://demo.contao.org. 
In my first test, I removed the favicon links from the additional head tags in the page layout and the favicon, which is assigned under the page structure, was no longer displayed. 
I have now tested this again, but now the favicon under the URL (`https://example.com/favicon.ico`) always appears, even if I remove all assignments in the page structure. Maybe this is cached or there is a physical file in the directory?

**Comment by fritzmg** [comment] 2021-05-06 18:46
> The favicon is not accessible via the URL `(https://example.com/favicon.ico)` if the favicon was included via the site structure.

Yes, I can confirm that. PR: https://github.com/contao/contao/pull/2989

**Comment by asaage** [comment] 2021-05-07 08:54
Favicons behave always a bit quirky in terms of caching - at least that's my experience.
Since the contao-feature does not cover all the apple- and android-touch-icons anyway i tend to use https://realfavicongenerator.net/ and add the links to fe_page manually.

**Comment by fritzmg** [comment] 2021-05-07 09:22
The point of the setting in the site structure is (also) to be able to provide custom root `/favicon.ico` resources for **non-HTML** responses **for each of your domains individually**. For example, if you open an URL like `https://example.com/files/foobar.jpg` or `https://example.com/files/foobar.mp4` etc. directly in your browser, the browser will have no meta information that would be otherwise present in regular HTML responses about favicon resources. Thus it will always automatically access `https://example.com/favicon.ico`. The feature in Contao enables you to show a different favicons for requests like

* https://example.com/files/foobar.jpg
* https://foobar.com/files/foobar.jpg

even though both domains point to the same Contao instance. If you did not define a favicon in your website root, both of these URLs will show the same favicon (or none), since there can only be one physical resource of course.

As this is working as intended (disregarding the current bug now covered in #2989) I am closing this as a duplicate of #2457. I don't think Contao should automatically add the root `favicon.ico` to the `<head>` automatically.

**Closed as completed by fritzmg** 2021-05-07 09:22 UTC
