### ISSUE TITLE
Back link broken due to "referer" issue in session when DCAs have 3+ levels of ptable/ctables

### ISSUE THREAD

**Issue by rhymeadam** [contao/contao#2722] opened 2021-02-10 09:37 UTC
Hi all, I am able to reproduce this in the Contao Demo which is 4.9 and on 4.10 installations as well.  Here are the steps:

Create a new theme so there are 2 to choose from.

<img width="1380" alt="Screen Shot 2021-02-10 at 4 09 37 AM" src="https://user-images.githubusercontent.com/36767740/107489733-f82d2600-6b56-11eb-8760-86a717800f9b.png">
<img width="1373" alt="Screen Shot 2021-02-10 at 4 10 05 AM" src="https://user-images.githubusercontent.com/36767740/107489996-4a6e4700-6b57-11eb-93b8-94f2fa18a9b2.png">

Create a new stylesheet in the Contao Demo theme.

<img width="1373" alt="Screen Shot 2021-02-10 at 4 10 19 AM" src="https://user-images.githubusercontent.com/36767740/107490059-607c0780-6b57-11eb-8ad0-e9cdd98e40d8.png">
<img width="1376" alt="Screen Shot 2021-02-10 at 4 10 40 AM" src="https://user-images.githubusercontent.com/36767740/107490087-67a31580-6b57-11eb-874d-35e842e11fd0.png">

Create a style in that stylesheet.

<img width="1374" alt="Screen Shot 2021-02-10 at 4 10 51 AM" src="https://user-images.githubusercontent.com/36767740/107490164-80abc680-6b57-11eb-8d38-fe4cd8446aba.png">
<img width="1378" alt="Screen Shot 2021-02-10 at 4 11 18 AM" src="https://user-images.githubusercontent.com/36767740/107490189-87d2d480-6b57-11eb-9b9d-470b6946cbbe.png">

Click the "Themes" link in the left column navigation (id="tl_navigation"), then go to the new theme and create a stylesheet.

<img width="494" alt="Screen Shot 2021-02-10 at 4 12 38 AM" src="https://user-images.githubusercontent.com/36767740/107491247-e2206500-6b58-11eb-98d7-8a152708772c.png">
<img width="1363" alt="Screen Shot 2021-02-10 at 4 11 37 AM" src="https://user-images.githubusercontent.com/36767740/107490240-9de09500-6b57-11eb-990e-218d8ca03f14.png">
<img width="1375" alt="Screen Shot 2021-02-10 at 4 11 49 AM" src="https://user-images.githubusercontent.com/36767740/107490333-c10b4480-6b57-11eb-959f-ea431460f237.png">
<img width="1376" alt="Screen Shot 2021-02-10 at 4 12 04 AM" src="https://user-images.githubusercontent.com/36767740/107490347-c6688f00-6b57-11eb-8e07-c889c03b7bd2.png">

Create a new style in that stylesheet.

<img width="1375" alt="Screen Shot 2021-02-10 at 4 12 15 AM" src="https://user-images.githubusercontent.com/36767740/107490401-d7190500-6b57-11eb-99c8-c6875a87a0ea.png">
<img width="1376" alt="Screen Shot 2021-02-10 at 4 12 30 AM" src="https://user-images.githubusercontent.com/36767740/107490414-db452280-6b57-11eb-8cdb-bf2f10c83325.png">

Click the "Themes" link in the left column navigation (id="tl_navigation") again.

<img width="494" alt="Screen Shot 2021-02-10 at 4 12 38 AM" src="https://user-images.githubusercontent.com/36767740/107490471-eef08900-6b57-11eb-81f0-73a55eec8e3c.png">

Click the CSS icon for the new theme.

<img width="1367" alt="Screen Shot 2021-02-10 at 4 12 50 AM" src="https://user-images.githubusercontent.com/36767740/107490526-ff086880-6b57-11eb-8bd2-f065286e964b.png">

Edit the new theme's stylesheet.

<img width="1374" alt="Screen Shot 2021-02-10 at 4 13 01 AM" src="https://user-images.githubusercontent.com/36767740/107490580-10ea0b80-6b58-11eb-9aef-e54e4b9004f2.png">

Click the back button.

<img width="1373" alt="Screen Shot 2021-02-10 at 4 13 09 AM" src="https://user-images.githubusercontent.com/36767740/107490637-23644500-6b58-11eb-8114-a848a14bc2a5.png">

Instead of going back to the new theme's stylesheet parentView, it goes to the original Contao Demo theme's parentView.

<img width="1374" alt="Screen Shot 2021-02-10 at 4 13 16 AM" src="https://user-images.githubusercontent.com/36767740/107490740-4989e500-6b58-11eb-822e-b42e356e4e29.png">

I believe swapping the arrays in the "array_merge" on the following line fixes this, but I haven't tested it out fully yet.  I understand that the stylesheets in Contao are going to be removed, but other extensions and customizations that we have built depend on this functionality to work properly.  Please let me know if this can be fixed sometime soon.  Thanks!

https://github.com/contao/core-bundle/blob/7c86adf2e04faae96bd303989a64543d60b22b7b/src/EventListener/StoreRefererListener.php#L85

**Comment by aschempp** [comment] 2021-02-18 07:44
Thanks for the extensive review! I always though this is a known limitation of our back end (due to storing referrer in the session etc.), but maybe it can be improved 😊

**Comment by Toflar** [comment] 2021-11-17 15:54
Indeed it was the wrong way around. I also had to adjust the unit tests quite a bit because they tested this incorrectly (which is also why this wasn't noticed in the first place).
Thanks for the excellent description which helped me to reproduce the issue easily! 😊 
Closing this in favor of https://github.com/contao/contao/pull/3690.

**Closed as completed by Toflar** 2021-11-17 15:54 UTC
Labels: bug
