### ISSUE TITLE
SymlinksCommand missing ContainerAware capability

### ISSUE THREAD

**Issue by Jidoka1902** [contao/contao#493] opened 2019-05-17 21:39 UTC
**Affected version(s)**
4.4.39
**Description**  
SymlinksCommand misses the capability of ContainerAwareness. 

Either extending the ContainerAwareCommand or implementing the ContainerAwareInterface and using the ContainerAwareTrait (which is the new symfon way) will fix this.
**How to reproduce**  
try to create a new folder within the filsystem backend

**Comment by xchs** [comment] 2019-05-17 21:45
Duplicate of https://github.com/contao/contao/issues/462

**Comment by xchs** [comment] 2019-05-17 21:48
Duplicate of https://github.com/contao/contao/issues/462

**Closed as completed** 2019-05-18 08:48 UTC
