### ISSUE TITLE
addWizardClass breaks compatibility with older versions

### ISSUE THREAD

**Issue by bennyborn** [contao/contao#1307] opened 2020-02-11 12:20 UTC
**Affected version(s)**
4.9.0-RC1

**Description**
Any extension that uses any picker in a DCA which needed the `wizard` CSS-class will break the styling with 4.9 because of the new `addWizardClass` attribute. I've seen no way to be compatible with 4.4 and 4.9 without distinguishing between the versions within every `eval` of every field.

![image](https://user-images.githubusercontent.com/226890/74236063-a8601880-4cd0-11ea-87d0-9a0efaeb575e.png)
> With wizard class from 4.4

![image](https://user-images.githubusercontent.com/226890/74236194-01c84780-4cd1-11ea-9505-efd9de8fd6ef.png)
> Without wizard class as of 4.9

Maybe the handling within https://github.com/contao/contao/blob/4.9/core-bundle/src/Resources/contao/classes/DataContainer.php#L520-L532 could be improved so 4.9 removes the wizard class if we explicitly say `'addWizardClass'=>false`. This way we'd have at least a chance to be backwards compatible.

**Comment by aschempp** [comment] 2020-02-11 15:28
I think we should remove `'addWizardClass'=>false`. Instead of "removing" the wizard class, we should add CSS that "overrides" that class. For example, the class `dcawizard` should re-set the input width to 100%, which would already make the icon look good …

**Comment by leofeyer** [comment] 2020-02-13 13:51
@bennyborn Can you elaborate on your problem please? I fail to see how the `addWizardClass` attribute is causing the problem – the core only uses it for the `tl_files.name` field.

**Comment by bennyborn** [comment] 2020-02-13 19:58
@leofeyer The problem is simple. Prior to 4.9 you need to add `'tl_class=>'wizard'` in `eval` if your field is using one in order to get the item of the wizard correctly placed. With 4.9 having the wizard-class attached causes the wizard icon to be placed incorrectly (as shown in the OG post).

No wizard class < 4.9 => Icon placed incorrectly
With wizard class >= 4.9 => Icon placed incorrectly

There seems to be currently no way to have the icon placed correctly in all versions.

**Comment by leofeyer** [comment] 2020-02-17 17:42
> Prior to 4.9 you need to add 'tl_class=>'wizard' in eval if your field is using one in order to get the item of the wizard correctly placed

I think that this statement is wrong already, as @Toflar has changed the wizard CSS handling in Contao 4.4.3 (see https://github.com/contao/core-bundle/pull/1011). Since then, the `wizard` class is added automatically and the new `addWizardClass` option has only been added to disable this automatism.

Can you provide detailed instructions on how to reproduce the problem in the Contao Official Demo?

**Comment by bennyborn** [comment] 2020-02-18 07:56
>Toflar has changed the wizard CSS handling in Contao 4.4.3 (see [contao/core-bundle#1011]
(https://github.com/contao/core-bundle/pull/1011))

I totally did not know about that. It seems leaving out the wizard class completely and adding `'addWizardClass'=>false` seems to work fine for 4.4 and 4.9.

**Comment by leofeyer** [comment] 2020-02-18 08:11
I think I found the issue though: If there is no `wizard` class, the icon has `vertical-align: baseline`, but if the class is added, it changes to `vertical-align: middle`. This should be fixed.

**Closed as completed** 2020-02-18 09:10 UTC
Labels: bug
