### ISSUE TITLE
Content element “Download” - overwrite link is wrong

### ISSUE THREAD

**Issue by jochi44** [contao/contao#6753] opened 2024-01-21 11:15 UTC
### Affected version(s)

5.3.0-RC1

### Description

Note: I’ve tested this with a file of type “pdf”.

Option “Overwrite Link”
IS: In the frontend the entered “Link title” is shown.
SHOULD: Display the entered “Link text”.
IS: In the output html the <a> gets the attribute “title” from “Link text”.
SHOULD: The <a> attribute “title” should get the value from “Link title”.

**Comment by asaage** [comment] 2024-01-21 12:25
Please compare to https://github.com/contao/contao/issues/5975 - it might be on purpose i did not check iif the the overwrite feature works the same though.

**Comment by fritzmg** [comment] 2024-01-21 16:23
For **Link text** the description says

> The link text will be displayed instead of the target URL.

For **Link title** the descriptions says

> The link title is added as title attribute in the HTML markup.

As far as I tested, both statements are true and everything is working as intended.

**Comment by jochi44** [comment] 2024-01-22 10:56
@fritzmg I did some additional testing, it's confusing.
Can you please try to fill BOTH fields (Link text and Link title) at the same time with different values?
I think in this case the output is wrong as the entered "Link text" is not shown in the frontend.
The entered "Link title" is shown instead.
When hovering over the link, the "Link text" is shown.
Shouldn't it be vice versa?

If this is the intended behaviour feel free to close this issue.

**Comment by fritzmg** [comment] 2024-01-22 11:27
Hm, I was able to reproduce it now, not sure what happened before.

Anyway, it's the same issue as [here](https://github.com/contao/contao/issues/6174) but for the `download` content element.

**Comment by fritzmg** [comment] 2024-01-22 11:36
Closing in favor of #6760

**Closed as completed by fritzmg** 2024-01-22 11:36 UTC
Labels: bug
