### ISSUE TITLE
Remove deferred images data if source file does not exist

### ISSUE THREAD

**Issue by qzminski** [contao/contao#2324] opened 2020-09-22 11:20 UTC
**Affected version(s)**

Contao 4.9.5 (probably others as well)

**Description**

The deferred images JSON files should be removed if the source file no longer exists. Reproducible by adding an image, calling the URL for it to generate the deferred image information files, then deleting the original. Step by step:

1. Create an image size (ideally with some responsive sizes).
2. Put an image on the website, select the created size.
3. The main image loads; copy one the responsive size URLs (don't open it just yet).
4. Remove the image source file.
5. Open the copied responsive size URL –> error.

It should probably return 404 instead and remove the obsolete JSON file.

"Stack trace":
- https://github.com/contao/image/blob/master/src/Image.php#L61
- https://github.com/contao/image/blob/master/src/DeferredResizer.php#L185
- https://github.com/contao/image/blob/master/src/DeferredResizer.php#L106

/cc @Toflar @ausi

**Comment by aschempp** [comment] 2020-09-22 11:49
probably duplicate of https://github.com/contao/contao/issues/1995 ?

**Comment by qzminski** [comment] 2020-09-22 11:50
Oh looks like, yes. Except of the fact that JSON file should be removed then as well, not only 404 returned.

**Comment by ausi** [comment] 2020-09-23 06:47
See https://github.com/contao/contao/issues/1995#issuecomment-696684721

**Closed as completed by ausi** 2020-09-23 06:47 UTC
