### ISSUE TITLE
Set-Cookie header multiple times

### ISSUE THREAD

**Issue by ghost** [contao/contao#35] opened 2018-08-28 11:06 UTC
<a href="https://github.com/saress"><img src="https://avatars2.githubusercontent.com/u/1481301?v=4" align="left" width="42" height="42"></img></a> [Comment](https://github.com/contao/core-bundle/pull/29#issuecomment-416534919) by @saress
August 28th, 2018, 12:34 GMT

Hi Leo,

we have updated 2 different installations from 4.4.20 to 4.4.22 today and the changes in MergeHttpHeadersListener.php cause a "Bad gateway 502" error in the frontend. After replacing the file with the old one, everything works fine again. 

Kind regards,
Saress

**Comment by leofeyer** [comment] 2018-08-28 11:08
This is most likely caused by

https://github.com/contao/contao/blob/1d6a49dbcb1114f3ee1c72edad624dac733f27b3/core-bundle/src/EventListener/MergeHttpHeadersListener.php#L159-L162

Can you please remove `, false` and try again?

**Comment by saress** [comment] 2018-08-28 11:33
Hi Leo,

thanks a lot, this fixes the problem.

Kind regards,
Saress

**Comment by leofeyer** [comment] 2018-08-28 15:05
Fixed in 9ab3e513636f39c2118514d26c6fa1aa2554d448.

**Closed as completed by leofeyer** 2018-08-28 15:05 UTC
Labels: bug
