### ISSUE TITLE
Previewing news entries causes logout from the backend

### ISSUE THREAD

**Issue by plorenz-etes** [contao/contao#278] opened 2019-01-16 11:12 UTC
**Affected version(s)**

Tested with Contao 4.4.32

**Description** / **How to reproduce**  

When editing news entries in the backend, pressing the "preview" button on the top opens a new tab showing a preview of the news article (as expected). However, this also logs you out of the backend, so if you reload the preview, change preview settings or click any link in the backend, you will get redirected to the login page.

**Details**

I have tracked the issue down in the source code. It seems like Frontend::getLoginStatus() fails to validate the session and therefore removes the session cookie. The function gets called by FrontendIndex::__construct twice, one time for the backend and one time for the frontend - but the first check already fails.

I hope this is reproducible for you as I didn't have a clean test installation for verification.

**Comment by xchs** [comment] 2019-01-16 18:14
I cannot reproduce this in my demo installation (running Contao 4.4.33).

**Comment by plorenz-etes** [comment] 2019-01-22 08:14
I finally had the time to try reproducing the issue on a clean installation, but it seems that this issue is not reproducible. I'll try to further investigate the affected installation and report back what I found.

**Comment by leofeyer** [comment] 2019-01-22 10:04
Closing the ticket for now then.

**Closed as completed** 2019-01-22 10:03 UTC
