### ISSUE TITLE
Bug during installation with contao 4.13.2

### ISSUE THREAD

**Issue by t0-git** [contao/contao#3649] opened 2021-11-06 23:42 UTC
**Affected version(s)**

4.13.2

**Description**

I successfully installed the latest contao manager (1.4.8) to install contao 4.13.2. No error during the installation, all is okay. At then end, I click on update database, which redirects me to contao/install. But it doesn't exist. I searched inside all the directories of the web server, but no folder like this was created. I hope I didn't miss something inside the documentation, but I think something is not working properly. And I have the same problem when I try to do this from CLI using composer.

**Comment by ausi** [comment] 2021-11-07 07:20
There is no Contao version 4.13.2 yet. Did you mean 4.12.3?

**Comment by aschempp** [comment] 2021-11-07 07:21
`contao/install` is not an actual file but a virtual route. I assume you have Contao 4.12.2 - you should have a `web/index.php` file that handles all routes.

Make sure your webserver redirect all requests to that `index.php`. Apache should do this automatically through the bundled `.htaccess` file. If you have Nginx, you (or your server admin) might need to update the server config. 


Since this is not a bug in Contao, I'm closing this issue to keep things tidy. Community support is available in our forums or our Slack channel (see https://to.contao.org/support). If you have additional questions or feedback on this issue, please feel free to respond here though!

**Closed as completed by aschempp** 2021-11-07 07:21 UTC

**Comment by t0-git** [comment] 2021-11-07 15:05
Yes I meant 4.12.3, apologies.
I'm sorry if it's not the good place to talk about it, I'll discuss it on Slack. web/index.php (which is accessible at 127.0.0.1/index.php) redirects to contao/install, even if I have the bundled .htaccess file in the web directory.
