### ISSUE TITLE
Contao 4.10.2 / Colorbox / filetype in uppercase

### ISSUE THREAD

**Issue by vossmedien** [contao/contao#2377] opened 2020-09-29 13:35 UTC
We updated our Installation from 4.4 to 4.10 and now we have a problem with our Colorbox-Images.
If the filetype (".jpg") is in uppercase (".JPG") the colorbox will stop working and the link to open the colorbox will not inserted.
if its ".jpg" everything is working fine.

Any way to fix that?

Thank you!

Christian

**Comment by fritzmg** [comment] 2020-09-29 13:38
Duplicate of #2358

**Closed as completed** 2020-09-29 13:42 UTC
