### ISSUE TITLE
Selection of frontend module of type "root_page_dependent_modules" is somehow broken in the backend

### ISSUE THREAD

**Issue by jochi44** [contao/contao#7404] opened 2024-08-01 20:31 UTC
### Affected version(s)

5.3.x

### Description

Steps to reproduce:
LAYOUT -> Themes -> Icon "Frontend modules" -> New -> select module type "Root page dependent modules"

Error in /var/logs:

```
[2024-08-01T22:24:59.871823+02:00] request.INFO: Matched route "contao_backend". {"route":"contao_backend","route_parameters":{"_route":"contao_backend","_scope":"backend","_controller":"Contao\\CoreBundle\\Controller\\BackendController::mainAction"},"request_uri":"https://abc.tld/contao?act=edit&do=themes&id=5&ref=9o84ouAE&rt=60b78e103353d3e.TvItpTqcZ4E_v6GSORdR2FPjm0OnKVQK0HCBt16WgvI.OqVpl2n5VexV0cjeC0UliiePozDlWxZduTrE7gzXurgEkVvOe6kM83ePzg&table=tl_module","method":"POST"} {"request_uri":"https://abc.tld/contao?act=edit&do=themes&id=5&ref=9o84ouAE&rt=60b78e103353d3e.TvItpTqcZ4E_v6GSORdR2FPjm0OnKVQK0HCBt16WgvI.OqVpl2n5VexV0cjeC0UliiePozDlWxZduTrE7gzXurgEkVvOe6kM83ePzg&table=tl_module","request_method":"POST"}
[2024-08-01T22:24:59.933425+02:00] php.ERROR: Warning: foreach() argument must be of type array|object, null given {"exception":"[object] (ErrorException(code: 0): Warning: foreach() argument must be of type array|object, null given at /var/www/test/vendor/contao/core-bundle/contao/widgets/RootPageDependentSelect.php:31)"} {"request_uri":"https://abc.tld/contao?act=edit&do=themes&id=5&ref=9o84ouAE&rt=60b78e103353d3e.TvItpTqcZ4E_v6GSORdR2FPjm0OnKVQK0HCBt16WgvI.OqVpl2n5VexV0cjeC0UliiePozDlWxZduTrE7gzXurgEkVvOe6kM83ePzg&table=tl_module","request_method":"POST"}
[2024-08-01T22:24:59.941158+02:00] contao.general.INFO: Version 1 of record "tl_module.id=5" has been created (parent records: tl_theme.id=1) {"contao":{"Contao\\CoreBundle\\Monolog\\ContaoContext":"{\"func\":\"Contao\\\\Versions::create\",\"action\":\"GENERAL\",\"username\":\"MyUserName\",\"browser\":\"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/127.0.0.0 Safari\\/537.36 Edg\\/127.0.0.0\",\"uri\":\"https:\\/\\/abc.tld\\/contao?act=edit&do=themes&id=5&ref=9o84ouAE&rt=60b78e103353d3e.TvItpTqcZ4E_v6GSORdR2FPjm0OnKVQK0HCBt16WgvI.OqVpl2n5VexV0cjeC0UliiePozDlWxZduTrE7gzXurgEkVvOe6kM83ePzg&table=tl_module\",\"pageId\":null}"}} {"request_uri":"https://abc.tld/contao?act=edit&do=themes&id=5&ref=9o84ouAE&rt=60b78e103353d3e.TvItpTqcZ4E_v6GSORdR2FPjm0OnKVQK0HCBt16WgvI.OqVpl2n5VexV0cjeC0UliiePozDlWxZduTrE7gzXurgEkVvOe6kM83ePzg&table=tl_module","request_method":"POST","contao":{"Contao\\CoreBundle\\Monolog\\ContaoContext":"{\"func\":\"Contao\\\\Versions::create\",\"action\":\"GENERAL\",\"username\":\"MyUserName\",\"browser\":\"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/127.0.0.0 Safari\\/537.36 Edg\\/127.0.0.0\",\"uri\":\"https:\\/\\/abc.tld\\/contao?act=edit&do=themes&id=5&ref=9o84ouAE&rt=60b78e103353d3e.TvItpTqcZ4E_v6GSORdR2FPjm0OnKVQK0HCBt16WgvI.OqVpl2n5VexV0cjeC0UliiePozDlWxZduTrE7gzXurgEkVvOe6kM83ePzg&table=tl_module\",\"pageId\":null}"}}
[2024-08-01T22:24:59.977194+02:00] messenger.INFO: Stopping worker. {"transport_names":["contao_prio_high"]} {"request_uri":"https://abc.tld/contao?act=edit&do=themes&id=5&ref=9o84ouAE&rt=60b78e103353d3e.TvItpTqcZ4E_v6GSORdR2FPjm0OnKVQK0HCBt16WgvI.OqVpl2n5VexV0cjeC0UliiePozDlWxZduTrE7gzXurgEkVvOe6kM83ePzg&table=tl_module","request_method":"POST"}
[2024-08-01T22:25:00.048603+02:00] request.INFO: Matched route "contao_backend". {"route":"contao_backend","route_parameters":{"_route":"contao_backend","_scope":"backend","_controller":"Contao\\CoreBundle\\Controller\\BackendController::mainAction"},"request_uri":"https://abc.tld/contao?act=edit&do=themes&id=5&ref=9o84ouAE&rt=60b78e103353d3e.TvItpTqcZ4E_v6GSORdR2FPjm0OnKVQK0HCBt16WgvI.OqVpl2n5VexV0cjeC0UliiePozDlWxZduTrE7gzXurgEkVvOe6kM83ePzg&table=tl_module","method":"GET"} {"request_uri":"https://abc.tld/contao?act=edit&do=themes&id=5&ref=9o84ouAE&rt=60b78e103353d3e.TvItpTqcZ4E_v6GSORdR2FPjm0OnKVQK0HCBt16WgvI.OqVpl2n5VexV0cjeC0UliiePozDlWxZduTrE7gzXurgEkVvOe6kM83ePzg&table=tl_module","request_method":"GET"}
[2024-08-01T22:25:00.113177+02:00] php.ERROR: Warning: foreach() argument must be of type array|object, null given {"exception":"[object] (ErrorException(code: 0): Warning: foreach() argument must be of type array|object, null given at /var/www/test/vendor/contao/core-bundle/contao/widgets/RootPageDependentSelect.php:31)"} {"request_uri":"https://abc.tld/contao?act=edit&do=themes&id=5&ref=9o84ouAE&rt=60b78e103353d3e.TvItpTqcZ4E_v6GSORdR2FPjm0OnKVQK0HCBt16WgvI.OqVpl2n5VexV0cjeC0UliiePozDlWxZduTrE7gzXurgEkVvOe6kM83ePzg&table=tl_module","request_method":"GET"}
[2024-08-01T22:25:00.157863+02:00] messenger.INFO: Sending message Contao\CoreBundle\Messenger\Message\SearchIndexMessage with contao_prio_low sender using Symfony\Component\Messenger\Bridge\Doctrine\Transport\DoctrineTransport {"class":"Contao\\CoreBundle\\Messenger\\Message\\SearchIndexMessage","alias":"contao_prio_low","sender":"Symfony\\Component\\Messenger\\Bridge\\Doctrine\\Transport\\DoctrineTransport"} {"request_uri":"https://abc.tld/contao?act=edit&do=themes&id=5&ref=9o84ouAE&rt=60b78e103353d3e.TvItpTqcZ4E_v6GSORdR2FPjm0OnKVQK0HCBt16WgvI.OqVpl2n5VexV0cjeC0UliiePozDlWxZduTrE7gzXurgEkVvOe6kM83ePzg&table=tl_module","request_method":"GET"}
[2024-08-01T22:25:00.169879+02:00] messenger.INFO: Stopping worker. {"transport_names":["contao_prio_high"]} {"request_uri":"https://abc.tld/contao?act=edit&do=themes&id=5&ref=9o84ouAE&rt=60b78e103353d3e.TvItpTqcZ4E_v6GSORdR2FPjm0OnKVQK0HCBt16WgvI.OqVpl2n5VexV0cjeC0UliiePozDlWxZduTrE7gzXurgEkVvOe6kM83ePzg&table=tl_module","request_method":"GET"}
```

If you then select the NEXT module type "Custom template" the "Internal Server Error" screen appears with this error message:

`Tried to list template options for the modern fragment type "frontend_module/root_page_dependent_modules" but could not find any template. Did you forget to create the default template?`

Didn't test on 5.3.11.

**Comment by zoglo** [comment] 2024-08-01 21:08
Just tested this in the current demo so this affects `5.3.x` as well.

Might have to do with the switch from `root_page_dependent_modules` to any module using twig templates (currently `html`, `unfiltered_html`, `template`).

Leaving this for more information:

**Related stack trace:**
```php
LogicException:
Tried to list template options for the modern fragment type "frontend_module/root_page_dependent_modules" but could not find any template. Did you forget to create the default template?

  at C:\Projekte\GitHub\zoglo\contao\5.3\core-bundle\src\EventListener\DataContainer\TemplateOptionsListener.php:92
  at Contao\CoreBundle\EventListener\DataContainer\TemplateOptionsListener->__invoke(object(DC_Table))
     (C:\Projekte\GitHub\zoglo\contao\5.3\core-bundle\contao\library\Contao\Widget.php:1308)
  at Contao\Widget::getAttributesFromDca(array('inputType' => 'select', 'eval' => array('chosen' => true, 'tl_class' => 'w50', 'required' => false), 'sql' => 'varchar(64) COLLATE ascii_bin NOT NULL default \'\'', 'options_callback' => array('contao.listener.data_container.template_options', '__invoke'), 'label' => array('Module template', 'Here you can select the module template.')), 'customTpl', '', 'customTpl', 'tl_module', object(DC_Table))
     (C:\Projekte\GitHub\zoglo\contao\5.3\core-bundle\contao\classes\DataContainer.php:481)
  at Contao\DataContainer->row()
     (C:\Projekte\GitHub\zoglo\contao\5.3\core-bundle\contao\drivers\DC_Table.php:2145)
  at Contao\DC_Table->edit()
     (C:\Projekte\GitHub\zoglo\contao\5.3\core-bundle\contao\classes\Backend.php:546)
  at Contao\Backend->getBackendModule('themes', null)
     (C:\Projekte\GitHub\zoglo\contao\5.3\core-bundle\contao\controllers\BackendMain.php:144)
  at Contao\BackendMain->run()
     (C:\Projekte\GitHub\zoglo\contao\5.3\core-bundle\src\Controller\BackendController.php:44)
  at Contao\CoreBundle\Controller\BackendController->mainAction()
     (C:\Projekte\Test_Environment\contao\5\vendor\symfony\http-kernel\HttpKernel.php:181)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (C:\Projekte\Test_Environment\contao\5\vendor\symfony\http-kernel\HttpKernel.php:76)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (C:\Projekte\Test_Environment\contao\5\vendor\symfony\http-kernel\Kernel.php:197)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (C:\Projekte\Test_Environment\contao\5\public\index.php:42)   
```

**Comment by fritzmg** [comment] 2024-08-02 08:48
The issue is, that our `TemplateOptionsListener` is executed before the new `type` is saved to the database. Within the `TemplateOptionsListener` we use `$dc->getCurrentRecord()` which in turn will execute `DataContainer::preloadCurrentRecords()` - which will load the _current_ state of the database into the `$arrCurrentRecordCache`, i.e. without the _new_ `type`.

**Comment by fritzmg** [comment] 2024-08-02 08:52
@ausi we removed the `$noCache` argument in https://github.com/contao/contao/commit/0fe1a8ca2894a9b96550d1d32406982f9b3532b5 - but I currently don't see how we could fix this without such an argument 🤔

**Comment by Toflar** [comment] 2024-08-02 10:11
Need to access the data of the current request? I have that in many projects. For example I have this code in the `onbeforesubmit` callback for generating an alias:

```
$alias = \array_key_exists('alias', $data) ? $data['alias'] : $dataContainer->getCurrentRecord()['alias'] ?? null;
```

In this case `$data` is provided by the callback but it's the same logic -> taking the one that is about to be updated and if not, fallback to the one in the db.

**Comment by fritzmg** [comment] 2024-08-02 10:13
And how do you get the data of the current record? The only way seems to be `$dc->activeRecord` which is deprecated in favor of `$dc->getCurrentRecord()`.

**Comment by Toflar** [comment] 2024-08-02 10:16
In case of the onbeforesubmit callback it's part of the callback argument. Other than that you need to get it from the request.

**Comment by fritzmg** [comment] 2024-08-02 10:17
In this case it's an `options_callback`. Always having to do `$request->request->get('type') ?? $dc->getCurrentRecord()['type']` everywhere seems a bit counterintuitive.

**Comment by Toflar** [comment] 2024-08-02 10:22
Yeah, we can add two new methods to the `DataContainer` that do this. One to fetch only the isolated new data from the request and one that merges the new with the current record data which is the method needed to fix this issue here. I would just build 2 methods so that a dev can explicitly say what they want.
We've deprecated `activeRecord` because it was a mixture between what's in the DB and what's going to be there and depending where you called it, it was just random. So 2 methods that are explicit.

**Comment by fritzmg** [comment] 2024-08-02 10:47
But then the current deprecation message is wrong, is it not? `$dc->getCurrentRecord()` is not the actual replacement for `$dc->activeRecord`. Should we now fix `$dc->getCurrentRecord()` to behave like `$dc->activeRecord`, and introduce another method that loads the data from the database? But then again the latter seems superfluous, since you can do that yourself anyway.

**Comment by leofeyer** [comment] 2024-08-02 10:48
If possible, we should not alter the behavior of `$dc->getCurrentRecord()` because people are already using it.

**Comment by fritzmg** [comment] 2024-08-02 10:53
> If possible, we should not alter the behavior of `$dc->getCurrentRecord()` because people are already using it.

They might not realize the changed behaviour though. And I would guess that outside of the contao bundles not many are using this method yet, as you'd still use `$dc->activeRecord` everywhere in order to stay compatible with 4.13. And even if your extension is Contao 5 only, you might still use `$dc->activeRecord`, as it's only deprecated.

**Comment by Toflar** [comment] 2024-08-02 11:17
No, no. There is no 1:1 replacement for `activeRecord`. It doesn't exist and it won't ever exist. `activeRecord` was a pure nonsense object with undeterministic values. So deprecating it is correct. Just the recommendation needs to be adjusted. Which method to call depends on the use case.

**Comment by fritzmg** [comment] 2024-08-02 11:19
So we introduce e.g. `$dc->getActiveRecord()` that represents the record merged with the values from the current request (i.e. the record represented by the current edit view) and change the deprecation message accordingly.

**Comment by Toflar** [comment] 2024-08-02 12:00
I'll create a PR for the methods as I think they should be :)

**Comment by Toflar** [comment] 2024-08-02 16:05
See https://github.com/contao/contao/pull/7407. I just thought having some code could make this easier to discuss.

**Closed as completed** 2024-08-08 10:13 UTC
Labels: bug
