### ISSUE TITLE
Database and Dotenv

### ISSUE THREAD

**Issue by epsreps** [contao/contao#6712] opened 2024-01-13 10:55 UTC
### Affected version(s)

4.13.35

### Description

It seems like the database credentials are not written to System->container->parameters when using database credentials via DATABASE_URL in env.local. When you write the database credentials in parameters.yml, you can find these in TL_CONFIG / System->getContainer->parameters as expected. Is this a ContaoKernel-thing? 
Getting these values would be very helpfull, for using in custom extensions.

(Tested in various 4.13 versions)

**Comment by m-vo** [comment] 2024-01-13 11:02
The current behaviour is correct, they should never be dumped anywhere in your config. Dbal gets configured with this config (it's their config) and will then theoretically be available in the driver service.

But why would you ever need this?

**Comment by fritzmg** [comment] 2024-01-13 12:40
> It seems like the database credentials are not written to System->container->parameters

What exactly do you mean or what are you trying to do?

**Comment by epsreps** [comment] 2024-01-13 12:50
Many thanks for your clarification. I had a simple DB Backup Extension (mysqldump) working fine for years, where i got the credentials from TL_CONFIG / System->container. I was just wondering about the differences between the installation setup via parameters.yml and env.local. So i'll overthink it using the newly contao backup solution.

**Comment by aschempp** [comment] 2024-01-13 20:40
If you are using the Contao Managed Edition, you can retrieve .env parameters using the `vendor/bin/contao-api`. But I would think using the backup command would be better. 

Closing since this is not a bug or feature request for Contao.

**Closed as completed by aschempp** 2024-01-13 20:40 UTC
Labels: bug, unconfirmed
