### ISSUE TITLE
Language redirect for regional codes ("de-at")

### ISSUE THREAD

**Issue by reluem** [contao/contao#430] opened 2019-04-10 09:44 UTC
**Affected version(s)**
4.7.2 & 4.7.3

**Description**
Since ~ Contao 4.7, the language redirect to /de is not working anymore in Safari on Mac or iOS, if the browser language is "de-at" or "de-de".

**How to reproduce**  
Here are my headers according to https://www.whatismybrowser.com/detect/what-http-headers-is-my-browser-sending. No fancy alterations to my Safari headers, I tested this with several computers in Austria.
<img width="622" alt="image" src="https://user-images.githubusercontent.com/17430489/55868195-4270a500-5b84-11e9-9d2b-39be0d3cb208.png">

If I use these headers in a ` curl -s -i -H 'Accept-Language: de-at' https://themes.contao.org/`, I am redirected to https://themes.contao.org/en. Same with the 'de-de' header from my iOS Safari.

On a demo Site with Contao 4.4 it correctly redirects to /de.
Same on the Contao 3.x that terminal42 is running: `curl -s -i -H 'Accept-Language: de-at' https:/www.terminal42.ch/` redirects to /de

**Comment by leofeyer** [comment] 2019-04-10 11:49
Fixed in f1070fc74be3c356ebdcb26deb03b29727759ae5 (thank you @aschempp).

**Comment by reluem** [comment] 2019-04-11 12:15
Something is strange. Now with 4.7.4 the regional language is correctly converted.
Here are two dumps on the `$languages` array [here](https://github.com/contao/contao/blob/f1070fc74be3c356ebdcb26deb03b29727759ae5/core-bundle/src/Routing/RouteProvider.php#L380). One before the conversion showing only my regional language code, one after the conversion.
`array:1 [▼
  0 => "de_AT"
]
`
`
array:2 [▼
  "de-AT" => 0
  "de" => 1
]`

My site, however, is still directing me to the /en version.

Do I have to do some additional steps? I deleted the /var/cache and browser cache already.
Also the original curl with `'de-at'` is still directed to /en …

**Comment by leofeyer** [comment] 2019-04-12 08:39
I can confirm that it still does not work. 😢 

```
Array
(
    [0] => de-CH
    [1] => de
)
```

Even though `$languages` contains `de`, I am redirected to `/en/`.

@aschempp This is how `$routes` looks like after sorting:

```
Array
(
    [tl_page.25.root] => Symfony\Component\Routing\Route Object
    (
        [_locale] => de
        [pageModel] => Contao\PageModel Object
        (
            [arrData:protected] => Array
            (
                [type] => regular
                [language] => de
            )
        )
    )
    [tl_page.3.root] => Symfony\Component\Routing\Route Object
    (
        [_locale] => en
        [pageModel] => Contao\PageModel Object
        (
            [arrData:protected] => Array
            (
                [type] => regular
                [language] => en
            )
        )
    )
    [tl_page.23.root] => Symfony\Component\Routing\Route Object
    (
        [_locale] => de
        [pageModel] => Contao\PageModel Object
        (
            [arrData:protected] => Array
            (
                [type] => root
                [language] => de
            )
        )
    )
    [tl_page.1.root] => Symfony\Component\Routing\Route Object
    (
        [_locale] => en
        [pageModel] => Contao\PageModel Object
        (
            [arrData:protected] => Array
            (
                [type] => root
                [language] => en
            )
        )
    )
    [tl_page.25.fallback] => Symfony\Component\Routing\Route Object
    (
        [_locale] => de
        [pageModel] => Contao\PageModel Object
        (
            [arrData:protected] => Array
            (
                [type] => regular
                [language] => de
            )
        )
    )
    [tl_page.3.fallback] => Symfony\Component\Routing\Route Object
    (
        [_locale] => en
        [pageModel] => Contao\PageModel Object
        (
            [arrData:protected] => Array
            (
                [type] => regular
                [language] => en
            )
        )
    )
    [tl_page.23.fallback] => Symfony\Component\Routing\Route Object
    (
        [_locale] => de
        [pageModel] => Contao\PageModel Object
        (
            [arrData:protected] => Array
            (
                [type] => root
                [language] => de
            )
        )
    )
    [tl_page.1.fallback] => Symfony\Component\Routing\Route Object
    (
        [_locale] => en
        [pageModel] => Contao\PageModel Object
        (
            [arrData:protected] => Array
            (
                [type] => root
                [language] => en
            )
        )
    )
)
```

So the first route that matches is `tl_page.25.fallback` and it should redirect to `/de/`:

<img width="783" alt="" src="https://user-images.githubusercontent.com/1192057/56025830-36671d80-5d13-11e9-8c6f-caa4264b4f24.png">

**Comment by aschempp** [comment] 2019-04-12 09:28
Can you check the web profiler routing information? It's not really accurate, but it might show why a page does not match.

**Comment by leofeyer** [comment] 2019-04-12 09:32
Oh yes, it does. 👍 

<img width="1047" alt="" src="https://user-images.githubusercontent.com/1192057/56027607-a88d3180-5d16-11e9-9ddd-441f28d7af4b.png">

So we actually would need a `'{$page->rootLanguage}' in request.getLanguages() or request.getLanguages() matches '/{$page->rootLanguage}-[A-Z]{2}/'` here:

https://github.com/contao/contao/blob/0824f28770ba9273ac7695d7232290ab0c99b527/core-bundle/src/Routing/RouteProvider.php#L298-L300

But I don't think that will work.

**Edit:** It does not: `Warning: preg_match() expects parameter 2 to be string, array given` Do we need a custom expression language provider?

**Comment by leofeyer** [comment] 2019-04-12 09:35
BTW, isn't the sorting of the fallback pages wrong?

- tl_page.25.fallback: regular, **de**
- tl_page.3.fallback: regular, en
- tl_page.23.fallback: root, **de**
- tl_page.1.fallback: root, en

Shoudn't the `de` routes come first?

**Comment by aschempp** [comment] 2019-04-12 11:22
Regular pages always come first, because they can have a path. The fallback pages (not the root ones!) match all paths of that domain (and language).

**Comment by leofeyer** [comment] 2019-04-12 15:21
See #435.

**Closed as completed by leofeyer** 2019-04-12 15:21 UTC
Labels: bug
