### ISSUE TITLE
Content element “Downloads” - add option open in new window

### ISSUE THREAD

**Issue by jochi44** [contao/contao#6757] opened 2024-01-21 11:18 UTC
### Description

Feature request for PDFs:
When checking the box “Show in browser” a new option “Full-size view/new window” should become available for having the file to be opened in a new browser window.

**Comment by ausi** [comment] 2024-01-22 09:58
Duplicate of https://github.com/contao/contao/issues/6755

You don’t need to open a separate issue for every content element, you can add the information to the first ticket that this affects both the “Download” as well as the “Downloads” elment.

**Closed as not planned by ausi** 2024-01-22 09:58 UTC
Labels: feature

**Comment by fritzmg** [comment] 2024-01-22 10:00
~@ausi this is actually separate.~ I am not sure why @jochi44 opened the other tickets, since apparently it was already clear to them anyway that the “Full-size view/new window” has no effect on the downloads themselves. But regardless, the feature makes sense (i.e. being able to add `target="_blank"` to the actual download link).

// oh nvm, you meant https://github.com/contao/contao/issues/6755 - yes
