### ISSUE TITLE
Issue when saving a new template folder

### ISSUE THREAD

**Issue by xchs** [contao/contao#293] opened 2019-01-19 22:21 UTC
**Affected version(s)**

Contao 4.7.0-RC2

**Description**

When saving a new template folder, Contao displays the following error message if the folder is created using the "_**Save**_" button only:

```hint
Forbidden

What's the matter?

File or folder "templates/__new__" is not mounted or cannot be found.
```

**How to reproduce**  

* Log into the Contao back end
* Open "_Layout_" > "_Templates_"
* Create a "_New folder_"
* Paste the new folder somewhere
* Insert a name for the new folder (e.g. `foobar`)
* Save the new folder with the button "_**Save**_" (not "_Save and close_"!)

NB: Despite the error message, the new template folder is still created.

**Comment by leofeyer** [comment] 2019-01-23 12:20
This can be fixed by replacing

```php
$this->redirect($this->addToUrl('id='.$this->urlEncode($this->intId)));
```

with

```php
$this->redirect($this->addToUrl('id='.$this->urlEncode($this->strPath . '/' . $this->varValue)));
```

in `DC_Folder` at line `1567`. However, it seems that this bug occurs in Contao 4.4 and 4.6 as well, doesn't it?

**Comment by xchs** [comment] 2019-01-23 13:43
> However, it seems that this bug occurs in Contao 4.4 and 4.6 as well, doesn't it?

The problem only occurs in Contao 4.7 (at least in my demo installations).

**Comment by leofeyer** [comment] 2019-01-23 13:46
I was able to reproduce it in Contao 4.6 as well.

**Comment by xchs** [comment] 2019-01-23 13:57
Interestingly, it works for me in Contao 4.6.13. :

**Comment by leofeyer** [comment] 2019-01-24 08:50
Hm, now I cannot reproduce it in Contao 4.6 anymore, either. 🤔

**Comment by leofeyer** [comment] 2019-01-24 10:06
It seems I had accidentally changed it in b546be78e90c5289c5ce317f330b3d0821defa87. Reverted in cd012300d4f66a9a0ce53ab63d0601b52f1d0394.

**Closed as completed by leofeyer** 2019-01-24 10:06 UTC
Labels: bug

**Comment by Znrl** [comment] 2020-02-19 07:55
Should this be fixed?
I get this error in 4.9 when saving template folders as well as renaming templates (clicking "save").

**Comment by leofeyer** [comment] 2020-02-19 08:06
See #1355
