### ISSUE TITLE
Content Element YouTube using Splash-Image: Version Conflict

### ISSUE THREAD

**Issue by berecont** [contao/contao#4499] opened 2022-04-11 11:53 UTC
### Affected version(s)

4.13.2

### Description

Version conflict by using splash-image
- checkbox true to use a spash-image
- add some image
- click save

brings something like this:
```
Version conflict
Another user has created version 5 while you were editing version 4 of this record.
Your changes have been now been saved as version 6 and have potentially overwritten the changes of version 5, therefore please compare the versions below:
```  
Same by uncheck 'use a splash-image'

Can be reproduced in the Onlinedemo

**Comment by fritzmg** [comment] 2022-04-11 12:09
Duplicate of https://github.com/contao/contao/issues/4454

**Closed as completed** 2022-04-13 14:16 UTC
Labels: bug, unconfirmed
