### ISSUE TITLE
Extensions break labels in tl_page

### ISSUE THREAD

**Issue by bennyborn** [contao/contao#2483] opened 2020-11-04 07:46 UTC
**Affected version(s)**

Contao 4.9, happening since 4.9.6
Contao 4.10

**Description**

Similar to #1311 the labels in `tl_page` are not being loaded correctly when editing a page.
I haven't had the chance to analyze this further but was able to pin it down to the exact 4.9 release this started
to happen in (which was 4.9.6) and it only seems to happen after `var/cache` is cleared.

This happened in a "clean" installation with only the following two extensions added:
https://github.com/numero2/contao-proper-filenames
https://github.com/numero2/contao-marketing-suite

Neither of those extensions cause a problem prior to the mentioned version.

**Steps to reproduce**
1. Fresh installation of Contao 4.9.6
2. Add the two extensions
3. Manually clear the `var/cache` directory
4. Take a look at the editing mask of the Site structure

![image](https://user-images.githubusercontent.com/226890/98082898-cc284780-1e79-11eb-9abb-8f3226fbebd0.png)

**Comment by fritzmg** [comment] 2020-11-04 10:17
> 3\. Manually clear the `var/cache` directory

If you manually clear the cache without warming it for production, then the internal cache of Contao will not be present. For production you need to execute the following:

```
vendor/bin/contao-console cache:clear --no-warmup
vendor/bin/contao-console cache:warmup
```

(or composer install)

**Comment by fritzmg** [comment] 2020-11-04 10:22
However, I can reproduce the problem in the `dev` environment as well.

**Comment by bytehead** [comment] 2020-11-04 10:24
That's weird. In my `dev` env I never have a warmed (contao) cache and everything works as expected with the labels... 🤔

**Comment by fritzmg** [comment] 2020-11-04 10:28
> That's weird. In my `dev` env I never have a warmed (contao) cache and everything works as expected with the labels... 🤔

Yes, no need to do it for `dev`. But if your clear the cache without warming it and then make a request in `prod`, the internal cache of Contao won't be built. But that turns out to be unrelated to the problem anyway - it would just make `prod` slower.

**Comment by bennyborn** [comment] 2020-11-04 10:54
>But if your clear the cache without warming it and then make a request in `prod`, the internal cache of Contao won't be built. But that turns out to be unrelated to the problem anyway - it would just make `prod` slower.

Just to be sure: While I'm aware that the cache should ideally not be cleared by just `rm -rf var/cache/*` we do agree that there is something unintended happening?

**Comment by fritzmg** [comment] 2020-11-04 10:56
Yes, see https://github.com/contao/contao/issues/2483#issuecomment-721645556 ;)

**Comment by leofeyer** [comment] 2020-12-10 15:46
I think that this should be fixed by #2540, too. @bennyborn Can you please confirm?

**Comment by bennyborn** [comment] 2020-12-10 16:21
@leofeyer I'm already on christmas vacation but maybe my colleague @michb can take a look at it.

**Comment by michb** [comment] 2020-12-11 12:34
Checked this issue against current 4.9.10 and 4.10.5 and it seems to be fixed.

**Comment by leofeyer** [comment] 2020-12-11 13:20
🎉

**Closed as completed by leofeyer** 2020-12-11 13:20 UTC
Labels: bug
