### ISSUE TITLE
Attempted to load class "Versions" from namespace "PackageVersions". Did you forget a "use" statement for another namespace?

### ISSUE THREAD

**Issue by Seefahrer** [contao/contao#3963] opened 2022-01-19 09:40 UTC
### Affected version(s)

4.13.0-RC1

### Description

When invoking „Preview“ in the backend fllwg error occurs and the site no longer reachable:

`request.CRITICAL: Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\ClassNotFoundError: "Attempted to load class "ContaoContext" from namespace "Contao". Did you forget a "use" statement for e.g. "Contao\CoreBundle\Asset\ContaoContext" or "Contao\CoreBundle\Monolog\ContaoContext"?" at /www/htdocs/w00c556f/cmsc4ME/vendor/contao/core-bundle/src/Resources/contao/library/Contao/Automator.php line 152 {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\ClassNotFoundError(code: 0): Attempted to load class \"ContaoContext\" from namespace \"Contao\".\nDid you forget a \"use\" statement for e.g. \"Contao\\CoreBundle\\Asset\\ContaoContext\" or \"Contao\\CoreBundle\\Monolog\\ContaoContext\"? at /www/htdocs/w00c556f/cmsc4ME/vendor/contao/core-bundle/src/Resources/contao/library/Contao/Automator.php:152)"} []`

A similar error occurs from time to time, i.e. I cannot deliberately reproduce it:

`request.CRITICAL: Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\ClassNotFoundError: "Attempted to load class "Versions" from namespace "PackageVersions". Did you forget a "use" statement for another namespace?" at /www/htdocs/w00c556f/cmsc4ME/vendor/contao/core-bundle/src/Util/PackageUtil.php line 31 {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\ClassNotFoundError(code: 0): Attempted to load class \"Versions\" from namespace \"PackageVersions\".\nDid you forget a \"use\" statement for another namespace? at /www/htdocs/w00c556f/cmsc4ME/vendor/contao/core-bundle/src/Util/PackageUtil.php:31)"} []
`

**Comment by bytehead** [comment] 2022-01-19 09:42
Duplicate of #3948

**Comment by bytehead** [comment] 2022-01-19 09:56
For the second error see #3953

**Closed as completed** 2022-01-19 09:59 UTC
