### ISSUE TITLE
File manager: select & search files

### ISSUE THREAD

**Issue by ngdot** [contao/contao#479] opened 2019-05-09 13:45 UTC
**Affected version(s)**
4.*

**Description**  
If you selecting files from the file browser that are filtered, files that were picked before are not chosen anymore.

**How to reproduce**  
Go to a downloads element that contain picked files, search for a new file to pick, pick it. Now the downloads element contain only the last picked. 

I don't know if it's really a bug, but its really unhandly if you are working with a lot of files, sometimes its much easier to search for a file name with the search instead of looking into each existing folder manuelly.

It would be awesome, if the files that are picked before filtering were saved.
So it is possible to add files via the search without losing the picked files before.

**Comment by fritzmg** [comment] 2019-05-09 13:53
Duplicate of https://github.com/contao/core-bundle/issues/1487

**Closed as completed** 2019-05-09 19:11 UTC
