### ISSUE TITLE
[4.4.49] Warning: array_key_exists() expects parameter 2 to be array, null given

### ISSUE THREAD

**Issue by Defcon0** [contao/contao#1757] opened 2020-05-19 07:54 UTC
**Affected version(s)**

Contao 4.4.49

**Description**

Since the update to contao 4.4.49 (in Contao 4.4.48, it works) we get the following issue:

![screen](https://user-images.githubusercontent.com/1485098/82299942-712b9280-99b6-11ea-82fa-c52af95fc73c.png)

When not using app_dev.php the error doesn't occur since it's a warning.

Maybe it's related to https://github.com/contao/contao/pull/1689 ?

**Comment by fritzmg** [comment] 2020-05-19 08:07
Duplicate of https://github.com/contao/contao/pull/1741

**Closed as completed** 2020-05-19 09:35 UTC
