### ISSUE TITLE
pages with 'show never' occure in sitemap.xml

### ISSUE THREAD

**Issue by tonsinn** [contao/contao#6989] opened 2024-03-11 07:00 UTC
### Affected version(s)

5.3.1

### Description

Even a page has 'show never' in 'Show in HTML sitemap' its page alias occures in sitemap.xml.
Also this page is hidden in the navigation menu and is excluded from the search index.

**Comment by asaage** [comment] 2024-03-11 07:25
The HTML sitemap is not the XML-sitemap.
This is a duplicate of #6728 and was considerd a no-issue.
You'd have to use the robots field to influence indexing.

**Closed as not planned** 2024-03-11 07:35 UTC
Labels: bug, unconfirmed
