### ISSUE TITLE
Maintenance: The "Purge the search index" job does not delete the database entries

### ISSUE THREAD

**Issue by xchs** [contao/contao#5995] opened 2023-04-27 20:45 UTC
### Affected version(s)

4.13.21

### Description

How to reproduce:
* Open the **Maintenance** back end module
* Select the "**Purge the search index**" job
![image](https://user-images.githubusercontent.com/1218766/234985557-23db6257-3c0b-4f3b-8b96-c87745694822.png)
* Click on the "**Purge data**" button
* Contao shows the message that "_The data has been purged_" but the entries are still present:
![image](https://user-images.githubusercontent.com/1218766/234986030-c3cc8adb-a2be-45b3-970c-14703336a894.png)
![image](https://user-images.githubusercontent.com/1218766/234986139-83e1608a-70fd-478d-9e97-871cb4ca099d.png)

**Comment by fritzmg** [comment] 2023-04-27 21:04
I cannot reproduce the issue.

**Comment by xchs** [comment] 2023-04-27 22:15
I can reproduce it with this Contao configuration:

`config/config.yml`

```yaml
# Contao configuration
contao:
    search:
        default_indexer:
            enable: false
 ```
If I enable the Contao Search Indexer, then it works as expected, i.e. the maintenance job purges the database entries.

However, if the Contao Search Indexer is disabled (`contao.search.default_indexer.enable: false`) I cannot purge the entries anymore. How is that related? The purge job should work independently of the indexer, shouldn't it?

**Comment by fritzmg** [comment] 2023-04-28 08:05
Duplicate of #1393 then.

**Closed as not planned** 2023-04-28 08:13 UTC
Labels: bug, unconfirmed
