### ISSUE TITLE
Member-Login: "Invalid Request Token" if member logs in after logout

### ISSUE THREAD

**Issue by chwchw** [contao/contao#11] opened 2018-08-20 12:16 UTC
**Affected version(s)**
contao/core-bundle:4.4.21
contao/installation-bundle:4.4.21

**Description**  
If a member logs in after he has logged out the following error is displayed:
![screen shot 2018-08-20 at 14 05 11](https://user-images.githubusercontent.com/8430041/44339621-5bf09f80-a482-11e8-9320-2f25a09fd12a.png)

**How to reproduce**  
Login > Logout > Login

**Comment by Defcon0** [comment] 2018-08-20 18:44
Same here, in Contao 4.4.20 everything seemed to be working fine.

I noticed that it only happens in app.php, not in app_dev.php. When clearing all cookies and opening my page in app.php, PHPSESSID is *not* set until I try to login. That fails and if I try again, it works, because then the PHPSESSID has been set.

**Comment by leofeyer** [comment] 2018-08-21 16:12
Does this only affect Contao 4.4? Because I have just tried it in the online demo (Contao 4.5) and the problem does not occur there.

**Comment by Defcon0** [comment] 2018-08-21 16:28
Mhm, didn‘t try that, sry.

**Comment by xchs** [comment] 2018-08-21 16:29
I can only reproduce it in Contao 4.4.

**Comment by cliffparnitzky** [comment] 2018-08-21 18:51
Yep, reproduced in Contao 4.4. ... Contao 4.5 is fine.

**Comment by Defcon0** [comment] 2018-08-23 15:55
What's the time horizon for 4.4.22? Don't want to push, just for information so that I can tell that to my customer ;-) No need for a detailed info, but will it be 1 day, 1 week, 1 month... ? Thanks!

If it took longer, I would just downgrade to 4.4.20.

**Comment by leofeyer** [comment] 2018-08-27 13:06
Fixed in 7a980dd6e4eeae542cb59c33ce2a49518d9f0457.

**Closed as completed by leofeyer** 2018-08-27 13:06 UTC
Labels: bug
