### ISSUE TITLE
Debug Mode menu item is never active

### ISSUE THREAD

**Issue by aschempp** [contao/contao#1405] opened 2020-02-26 09:42 UTC
when enabling the debug mode, the _Debug Mode_ does not change state. If the debug mode is active, the menu item should be active as well. This was the case but seems lost in the new menu implementation in Contao 4.9

**Comment by fritzmg** [comment] 2020-02-26 09:53
Duplicate of #1367

**Closed as completed** 2020-02-26 11:18 UTC
