### ISSUE TITLE
Version conflict at contao 4.9.28

### ISSUE THREAD

**Issue by liquid-a** [contao/contao#4508] opened 2022-04-13 17:13 UTC
### Affected version(s)

4.9.28

### Description

For about a week now, I have had constant version conflicts with various installations of Contao 4.9.28 (with different hosts). There is only one user on all installations and the error message is obviously unfounded. It occurs when saving pages, articles as well as elements or page layouts. It occurs irregularly, but very frequently. 
The latest version of 4.9.28 is installed, Composer update is done, all caches are cleared, all modules are up to date... Could not solve the problem myself so far. Is it possible that this is also a bug in Contao or in the Contao Manager? I don't have this problem with older versions (e.g. 4.9.20).

**Comment by fritzmg** [comment] 2022-04-13 17:14
Duplicate of https://github.com/contao/contao/issues/4454

**Closed as completed by fritzmg** 2022-04-13 17:14 UTC
Labels: bug, unconfirmed
