### ISSUE TITLE
'allowHtml' => true does not work in frontend with 'inputType' => 'textarea'

### ISSUE THREAD

**Issue by heimseiten** [contao/contao#1878] opened 2020-06-26 13:16 UTC
**Affected version**
Contao 4.9

**Description**
If the table tl_member is extended with a field `'inputType' => 'textarea'`, the setting `'allowHtml' => true` does not work when edited in the frontend. If the field is changed to `'inputType' => 'text'` and nothing else is changed, it works.

For example, when saving the string `<br>` in the frontend, in the `database` the string `&lt;br&gt;` is saved.

```
$GLOBALS['TL_DCA']['tl_member']['fields']['profil'] = [
    'label'     => &$GLOBALS['TL_LANG']['tl_member']['profil'],
    'inputType' => 'textarea',
    'eval'      => array(
        'mandatory'=>true,
        'feGroup'=>'personal',
        'feViewable'=>true,
        'feEditable'=>true,
        'allowHtml' => true
    ),
    'sql'       => "text NULL"
];
```

**Comment by leofeyer** [comment] 2020-07-24 10:10
Is this a duplicate of #736?

**Comment by heimseiten** [comment] 2020-07-30 09:12
Yes I think so. With rawValue I get the correct value with HTML tags. But because I don't know how to save the value with HTML tags I switched to 'inputType' => 'text'.

**Comment by leofeyer** [comment] 2020-07-30 10:18
Duplicate of #736

**Closed as completed by leofeyer** 2020-07-30 10:18 UTC
