### ISSUE TITLE
Back end login password icon

### ISSUE THREAD

**Issue by netzarbeiter** [contao/contao#5202] opened 2022-08-18 16:00 UTC
### Affected version(s)

4.13.8

### Description

https://demo.contao.org/contao/login

![backend](https://user-images.githubusercontent.com/1942550/185441629-28dd077e-9404-4132-9a1b-152111251e67.png)

Replace 31px by 6px.

```css
label[for="password"], 
label[for="confirm"] {
        …
	right: 6px;
        …
}
```

**Comment by leofeyer** [comment] 2022-08-18 16:09
Duplicate of #5203

**Comment by leofeyer** [comment] 2022-08-18 16:10
Well, actually my issue is the duplicate. 😄

**Comment by leofeyer** [comment] 2022-08-18 16:12
We have to find a solution that works for both the login screen and the "change password" screen (see #5165). This also affects Contao 4.13.

**Comment by netzarbeiter** [comment] 2022-08-18 16:15
How about the additional class? https://github.com/contao/contao/pull/4840

**Closed as completed** 2022-08-29 11:03 UTC
Labels: bug
