### ISSUE TITLE
English default registration password confirmation 

### ISSUE THREAD

**Issue by rburch** [contao/contao#5183] opened 2022-08-17 12:40 UTC
### Description

It seems obvious but I've had multiple people trying to register and getting stuck in the password confirmation because it is just labeled confirmation. People see it and don't always realize they just need to put their password in again. They get stuck and send a support email. I manually update it, but sometimes forget to. I suggest we update "Confirmation" to "Confirm password" as the english default. That makes more clear what the registration form is asking for.

**Comment by fritzmg** [comment] 2022-08-17 12:43
Duplicate of https://github.com/contao/contao/issues/2972 (basically your issue is a translation of the other issue). Also this has already been changed. Which Contao version are you using?

**Comment by rburch** [comment] 2022-08-17 12:50
Okay great. The site is 4.9.31. so it must have been changed after that version.

**Comment by fritzmg** [comment] 2022-08-17 12:53
No, it was changed in Contao 4.9.15. See here: 

https://github.com/contao/contao/blob/c02b2bd415302dadd0bb2af8efce47af5547ded3/core-bundle/src/Resources/contao/languages/en/default.xlf#L1098

**Comment by rburch** [comment] 2022-08-18 12:20
I don't think that's the line that pulls in the label for the registration. Could it be this line?
<img width="638" alt="Screen Shot 2022-08-18 at 8 17 32 AM" src="https://user-images.githubusercontent.com/1537395/185393053-d43fb1b0-b2f6-4345-9455-e1053295c1a1.png">

Here's my registration form in contao 4.9.31
<img width="1302" alt="Screen Shot 2022-08-18 at 8 18 07 AM" src="https://user-images.githubusercontent.com/1537395/185393184-a2f00b07-eadb-4a4f-9483-28fc099a052a.png">

**Comment by fritzmg** [comment] 2022-08-18 13:26
That is true, `FormPassword` currently uses `$GLOBALS['TL_LANG']['MSC']['confirmation']`, which is still "Confirmation", rather than `$GLOBALS['TL_LANG']['MSC']['confirm'][0]` (which would be "Confirm password").

**Closed as completed** 2022-08-26 10:09 UTC
Labels: bug
